// Code generated by ent, DO NOT EDIT.

package beeplatform

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the beeplatform type in the database.
	Label = "bee_platform"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldBeeID holds the string denoting the bee_id field in the database.
	FieldBeeID = "bee_id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldUpstreamAccountKey holds the string denoting the upstream_account_key field in the database.
	FieldUpstreamAccountKey = "upstream_account_key"
	// FieldIdentityVersion holds the string denoting the identity_version field in the database.
	FieldIdentityVersion = "identity_version"
	// FieldSubscriptionTier holds the string denoting the subscription_tier field in the database.
	FieldSubscriptionTier = "subscription_tier"
	// FieldConcurrency holds the string denoting the concurrency field in the database.
	FieldConcurrency = "concurrency"
	// FieldQuotaSnapshot holds the string denoting the quota_snapshot field in the database.
	FieldQuotaSnapshot = "quota_snapshot"
	// FieldQuotaUpdatedAt holds the string denoting the quota_updated_at field in the database.
	FieldQuotaUpdatedAt = "quota_updated_at"
	// FieldLastTaskAt holds the string denoting the last_task_at field in the database.
	FieldLastTaskAt = "last_task_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldExtra holds the string denoting the extra field in the database.
	FieldExtra = "extra"
	// EdgeBee holds the string denoting the bee edge name in mutations.
	EdgeBee = "bee"
	// Table holds the table name of the beeplatform in the database.
	Table = "bee_platform"
	// BeeTable is the table that holds the bee relation/edge.
	BeeTable = "bee_platform"
	// BeeInverseTable is the table name for the Bee entity.
	// It exists in this package in order to avoid circular dependency with the "bee" package.
	BeeInverseTable = "bee"
	// BeeColumn is the table column denoting the bee relation/edge.
	BeeColumn = "bee_id"
)

// Columns holds all SQL columns for beeplatform fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldBeeID,
	FieldPlatform,
	FieldUpstreamAccountKey,
	FieldIdentityVersion,
	FieldSubscriptionTier,
	FieldConcurrency,
	FieldQuotaSnapshot,
	FieldQuotaUpdatedAt,
	FieldLastTaskAt,
	FieldStatus,
	FieldExtra,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// UpstreamAccountKeyValidator is a validator for the "upstream_account_key" field. It is called by the builders before save.
	UpstreamAccountKeyValidator func(string) error
	// DefaultIdentityVersion holds the default value on creation for the "identity_version" field.
	DefaultIdentityVersion int16
	// SubscriptionTierValidator is a validator for the "subscription_tier" field. It is called by the builders before save.
	SubscriptionTierValidator func(string) error
	// ConcurrencyValidator is a validator for the "concurrency" field. It is called by the builders before save.
	ConcurrencyValidator func(int) error
	// DefaultQuotaSnapshot holds the default value on creation for the "quota_snapshot" field.
	DefaultQuotaSnapshot func() map[string]interface{}
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultExtra holds the default value on creation for the "extra" field.
	DefaultExtra func() map[string]interface{}
)

// OrderOption defines the ordering options for the BeePlatform queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByBeeID orders the results by the bee_id field.
func ByBeeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBeeID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByUpstreamAccountKey orders the results by the upstream_account_key field.
func ByUpstreamAccountKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamAccountKey, opts...).ToFunc()
}

// ByIdentityVersion orders the results by the identity_version field.
func ByIdentityVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdentityVersion, opts...).ToFunc()
}

// BySubscriptionTier orders the results by the subscription_tier field.
func BySubscriptionTier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionTier, opts...).ToFunc()
}

// ByConcurrency orders the results by the concurrency field.
func ByConcurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConcurrency, opts...).ToFunc()
}

// ByQuotaUpdatedAt orders the results by the quota_updated_at field.
func ByQuotaUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaUpdatedAt, opts...).ToFunc()
}

// ByLastTaskAt orders the results by the last_task_at field.
func ByLastTaskAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastTaskAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByBeeField orders the results by bee field.
func ByBeeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBeeStep(), sql.OrderByField(field, opts...))
	}
}
func newBeeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BeeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, BeeTable, BeeColumn),
	)
}
