// Code generated by ent, DO NOT EDIT.

package beeplatform

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldDeletedAt, v))
}

// BeeID applies equality check predicate on the "bee_id" field. It's identical to BeeIDEQ.
func BeeID(v int64) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldBeeID, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldPlatform, v))
}

// UpstreamAccountKey applies equality check predicate on the "upstream_account_key" field. It's identical to UpstreamAccountKeyEQ.
func UpstreamAccountKey(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldUpstreamAccountKey, v))
}

// IdentityVersion applies equality check predicate on the "identity_version" field. It's identical to IdentityVersionEQ.
func IdentityVersion(v int16) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldIdentityVersion, v))
}

// SubscriptionTier applies equality check predicate on the "subscription_tier" field. It's identical to SubscriptionTierEQ.
func SubscriptionTier(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldSubscriptionTier, v))
}

// Concurrency applies equality check predicate on the "concurrency" field. It's identical to ConcurrencyEQ.
func Concurrency(v int) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldConcurrency, v))
}

// QuotaUpdatedAt applies equality check predicate on the "quota_updated_at" field. It's identical to QuotaUpdatedAtEQ.
func QuotaUpdatedAt(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldQuotaUpdatedAt, v))
}

// LastTaskAt applies equality check predicate on the "last_task_at" field. It's identical to LastTaskAtEQ.
func LastTaskAt(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldLastTaskAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNotNull(FieldDeletedAt))
}

// BeeIDEQ applies the EQ predicate on the "bee_id" field.
func BeeIDEQ(v int64) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldBeeID, v))
}

// BeeIDNEQ applies the NEQ predicate on the "bee_id" field.
func BeeIDNEQ(v int64) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNEQ(FieldBeeID, v))
}

// BeeIDIn applies the In predicate on the "bee_id" field.
func BeeIDIn(vs ...int64) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldIn(FieldBeeID, vs...))
}

// BeeIDNotIn applies the NotIn predicate on the "bee_id" field.
func BeeIDNotIn(vs ...int64) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNotIn(FieldBeeID, vs...))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldContainsFold(FieldPlatform, v))
}

// UpstreamAccountKeyEQ applies the EQ predicate on the "upstream_account_key" field.
func UpstreamAccountKeyEQ(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldUpstreamAccountKey, v))
}

// UpstreamAccountKeyNEQ applies the NEQ predicate on the "upstream_account_key" field.
func UpstreamAccountKeyNEQ(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNEQ(FieldUpstreamAccountKey, v))
}

// UpstreamAccountKeyIn applies the In predicate on the "upstream_account_key" field.
func UpstreamAccountKeyIn(vs ...string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldIn(FieldUpstreamAccountKey, vs...))
}

// UpstreamAccountKeyNotIn applies the NotIn predicate on the "upstream_account_key" field.
func UpstreamAccountKeyNotIn(vs ...string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNotIn(FieldUpstreamAccountKey, vs...))
}

// UpstreamAccountKeyGT applies the GT predicate on the "upstream_account_key" field.
func UpstreamAccountKeyGT(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldGT(FieldUpstreamAccountKey, v))
}

// UpstreamAccountKeyGTE applies the GTE predicate on the "upstream_account_key" field.
func UpstreamAccountKeyGTE(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldGTE(FieldUpstreamAccountKey, v))
}

// UpstreamAccountKeyLT applies the LT predicate on the "upstream_account_key" field.
func UpstreamAccountKeyLT(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldLT(FieldUpstreamAccountKey, v))
}

// UpstreamAccountKeyLTE applies the LTE predicate on the "upstream_account_key" field.
func UpstreamAccountKeyLTE(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldLTE(FieldUpstreamAccountKey, v))
}

// UpstreamAccountKeyContains applies the Contains predicate on the "upstream_account_key" field.
func UpstreamAccountKeyContains(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldContains(FieldUpstreamAccountKey, v))
}

// UpstreamAccountKeyHasPrefix applies the HasPrefix predicate on the "upstream_account_key" field.
func UpstreamAccountKeyHasPrefix(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldHasPrefix(FieldUpstreamAccountKey, v))
}

// UpstreamAccountKeyHasSuffix applies the HasSuffix predicate on the "upstream_account_key" field.
func UpstreamAccountKeyHasSuffix(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldHasSuffix(FieldUpstreamAccountKey, v))
}

// UpstreamAccountKeyEqualFold applies the EqualFold predicate on the "upstream_account_key" field.
func UpstreamAccountKeyEqualFold(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEqualFold(FieldUpstreamAccountKey, v))
}

// UpstreamAccountKeyContainsFold applies the ContainsFold predicate on the "upstream_account_key" field.
func UpstreamAccountKeyContainsFold(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldContainsFold(FieldUpstreamAccountKey, v))
}

// IdentityVersionEQ applies the EQ predicate on the "identity_version" field.
func IdentityVersionEQ(v int16) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldIdentityVersion, v))
}

// IdentityVersionNEQ applies the NEQ predicate on the "identity_version" field.
func IdentityVersionNEQ(v int16) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNEQ(FieldIdentityVersion, v))
}

// IdentityVersionIn applies the In predicate on the "identity_version" field.
func IdentityVersionIn(vs ...int16) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldIn(FieldIdentityVersion, vs...))
}

// IdentityVersionNotIn applies the NotIn predicate on the "identity_version" field.
func IdentityVersionNotIn(vs ...int16) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNotIn(FieldIdentityVersion, vs...))
}

// IdentityVersionGT applies the GT predicate on the "identity_version" field.
func IdentityVersionGT(v int16) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldGT(FieldIdentityVersion, v))
}

// IdentityVersionGTE applies the GTE predicate on the "identity_version" field.
func IdentityVersionGTE(v int16) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldGTE(FieldIdentityVersion, v))
}

// IdentityVersionLT applies the LT predicate on the "identity_version" field.
func IdentityVersionLT(v int16) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldLT(FieldIdentityVersion, v))
}

// IdentityVersionLTE applies the LTE predicate on the "identity_version" field.
func IdentityVersionLTE(v int16) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldLTE(FieldIdentityVersion, v))
}

// SubscriptionTierEQ applies the EQ predicate on the "subscription_tier" field.
func SubscriptionTierEQ(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldSubscriptionTier, v))
}

// SubscriptionTierNEQ applies the NEQ predicate on the "subscription_tier" field.
func SubscriptionTierNEQ(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNEQ(FieldSubscriptionTier, v))
}

// SubscriptionTierIn applies the In predicate on the "subscription_tier" field.
func SubscriptionTierIn(vs ...string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldIn(FieldSubscriptionTier, vs...))
}

// SubscriptionTierNotIn applies the NotIn predicate on the "subscription_tier" field.
func SubscriptionTierNotIn(vs ...string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNotIn(FieldSubscriptionTier, vs...))
}

// SubscriptionTierGT applies the GT predicate on the "subscription_tier" field.
func SubscriptionTierGT(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldGT(FieldSubscriptionTier, v))
}

// SubscriptionTierGTE applies the GTE predicate on the "subscription_tier" field.
func SubscriptionTierGTE(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldGTE(FieldSubscriptionTier, v))
}

// SubscriptionTierLT applies the LT predicate on the "subscription_tier" field.
func SubscriptionTierLT(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldLT(FieldSubscriptionTier, v))
}

// SubscriptionTierLTE applies the LTE predicate on the "subscription_tier" field.
func SubscriptionTierLTE(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldLTE(FieldSubscriptionTier, v))
}

// SubscriptionTierContains applies the Contains predicate on the "subscription_tier" field.
func SubscriptionTierContains(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldContains(FieldSubscriptionTier, v))
}

// SubscriptionTierHasPrefix applies the HasPrefix predicate on the "subscription_tier" field.
func SubscriptionTierHasPrefix(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldHasPrefix(FieldSubscriptionTier, v))
}

// SubscriptionTierHasSuffix applies the HasSuffix predicate on the "subscription_tier" field.
func SubscriptionTierHasSuffix(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldHasSuffix(FieldSubscriptionTier, v))
}

// SubscriptionTierIsNil applies the IsNil predicate on the "subscription_tier" field.
func SubscriptionTierIsNil() predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldIsNull(FieldSubscriptionTier))
}

// SubscriptionTierNotNil applies the NotNil predicate on the "subscription_tier" field.
func SubscriptionTierNotNil() predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNotNull(FieldSubscriptionTier))
}

// SubscriptionTierEqualFold applies the EqualFold predicate on the "subscription_tier" field.
func SubscriptionTierEqualFold(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEqualFold(FieldSubscriptionTier, v))
}

// SubscriptionTierContainsFold applies the ContainsFold predicate on the "subscription_tier" field.
func SubscriptionTierContainsFold(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldContainsFold(FieldSubscriptionTier, v))
}

// ConcurrencyEQ applies the EQ predicate on the "concurrency" field.
func ConcurrencyEQ(v int) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldConcurrency, v))
}

// ConcurrencyNEQ applies the NEQ predicate on the "concurrency" field.
func ConcurrencyNEQ(v int) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNEQ(FieldConcurrency, v))
}

// ConcurrencyIn applies the In predicate on the "concurrency" field.
func ConcurrencyIn(vs ...int) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldIn(FieldConcurrency, vs...))
}

// ConcurrencyNotIn applies the NotIn predicate on the "concurrency" field.
func ConcurrencyNotIn(vs ...int) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNotIn(FieldConcurrency, vs...))
}

// ConcurrencyGT applies the GT predicate on the "concurrency" field.
func ConcurrencyGT(v int) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldGT(FieldConcurrency, v))
}

// ConcurrencyGTE applies the GTE predicate on the "concurrency" field.
func ConcurrencyGTE(v int) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldGTE(FieldConcurrency, v))
}

// ConcurrencyLT applies the LT predicate on the "concurrency" field.
func ConcurrencyLT(v int) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldLT(FieldConcurrency, v))
}

// ConcurrencyLTE applies the LTE predicate on the "concurrency" field.
func ConcurrencyLTE(v int) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldLTE(FieldConcurrency, v))
}

// QuotaUpdatedAtEQ applies the EQ predicate on the "quota_updated_at" field.
func QuotaUpdatedAtEQ(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldQuotaUpdatedAt, v))
}

// QuotaUpdatedAtNEQ applies the NEQ predicate on the "quota_updated_at" field.
func QuotaUpdatedAtNEQ(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNEQ(FieldQuotaUpdatedAt, v))
}

// QuotaUpdatedAtIn applies the In predicate on the "quota_updated_at" field.
func QuotaUpdatedAtIn(vs ...time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldIn(FieldQuotaUpdatedAt, vs...))
}

// QuotaUpdatedAtNotIn applies the NotIn predicate on the "quota_updated_at" field.
func QuotaUpdatedAtNotIn(vs ...time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNotIn(FieldQuotaUpdatedAt, vs...))
}

// QuotaUpdatedAtGT applies the GT predicate on the "quota_updated_at" field.
func QuotaUpdatedAtGT(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldGT(FieldQuotaUpdatedAt, v))
}

// QuotaUpdatedAtGTE applies the GTE predicate on the "quota_updated_at" field.
func QuotaUpdatedAtGTE(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldGTE(FieldQuotaUpdatedAt, v))
}

// QuotaUpdatedAtLT applies the LT predicate on the "quota_updated_at" field.
func QuotaUpdatedAtLT(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldLT(FieldQuotaUpdatedAt, v))
}

// QuotaUpdatedAtLTE applies the LTE predicate on the "quota_updated_at" field.
func QuotaUpdatedAtLTE(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldLTE(FieldQuotaUpdatedAt, v))
}

// QuotaUpdatedAtIsNil applies the IsNil predicate on the "quota_updated_at" field.
func QuotaUpdatedAtIsNil() predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldIsNull(FieldQuotaUpdatedAt))
}

// QuotaUpdatedAtNotNil applies the NotNil predicate on the "quota_updated_at" field.
func QuotaUpdatedAtNotNil() predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNotNull(FieldQuotaUpdatedAt))
}

// LastTaskAtEQ applies the EQ predicate on the "last_task_at" field.
func LastTaskAtEQ(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldLastTaskAt, v))
}

// LastTaskAtNEQ applies the NEQ predicate on the "last_task_at" field.
func LastTaskAtNEQ(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNEQ(FieldLastTaskAt, v))
}

// LastTaskAtIn applies the In predicate on the "last_task_at" field.
func LastTaskAtIn(vs ...time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldIn(FieldLastTaskAt, vs...))
}

// LastTaskAtNotIn applies the NotIn predicate on the "last_task_at" field.
func LastTaskAtNotIn(vs ...time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNotIn(FieldLastTaskAt, vs...))
}

// LastTaskAtGT applies the GT predicate on the "last_task_at" field.
func LastTaskAtGT(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldGT(FieldLastTaskAt, v))
}

// LastTaskAtGTE applies the GTE predicate on the "last_task_at" field.
func LastTaskAtGTE(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldGTE(FieldLastTaskAt, v))
}

// LastTaskAtLT applies the LT predicate on the "last_task_at" field.
func LastTaskAtLT(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldLT(FieldLastTaskAt, v))
}

// LastTaskAtLTE applies the LTE predicate on the "last_task_at" field.
func LastTaskAtLTE(v time.Time) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldLTE(FieldLastTaskAt, v))
}

// LastTaskAtIsNil applies the IsNil predicate on the "last_task_at" field.
func LastTaskAtIsNil() predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldIsNull(FieldLastTaskAt))
}

// LastTaskAtNotNil applies the NotNil predicate on the "last_task_at" field.
func LastTaskAtNotNil() predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNotNull(FieldLastTaskAt))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.BeePlatform {
	return predicate.BeePlatform(sql.FieldContainsFold(FieldStatus, v))
}

// HasBee applies the HasEdge predicate on the "bee" edge.
func HasBee() predicate.BeePlatform {
	return predicate.BeePlatform(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BeeTable, BeeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBeeWith applies the HasEdge predicate on the "bee" edge with a given conditions (other predicates).
func HasBeeWith(preds ...predicate.Bee) predicate.BeePlatform {
	return predicate.BeePlatform(func(s *sql.Selector) {
		step := newBeeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BeePlatform) predicate.BeePlatform {
	return predicate.BeePlatform(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BeePlatform) predicate.BeePlatform {
	return predicate.BeePlatform(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BeePlatform) predicate.BeePlatform {
	return predicate.BeePlatform(sql.NotPredicates(p))
}
