// Code generated by ent, DO NOT EDIT.

package web3scannercursor

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the web3scannercursor type in the database.
	Label = "web3scanner_cursor"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldScannerKey holds the string denoting the scanner_key field in the database.
	FieldScannerKey = "scanner_key"
	// FieldChainID holds the string denoting the chain_id field in the database.
	FieldChainID = "chain_id"
	// FieldTokenContract holds the string denoting the token_contract field in the database.
	FieldTokenContract = "token_contract"
	// FieldScanStartBlock holds the string denoting the scan_start_block field in the database.
	FieldScanStartBlock = "scan_start_block"
	// FieldLastScannedBlock holds the string denoting the last_scanned_block field in the database.
	FieldLastScannedBlock = "last_scanned_block"
	// FieldLastFinalizedBlock holds the string denoting the last_finalized_block field in the database.
	FieldLastFinalizedBlock = "last_finalized_block"
	// FieldLeaseOwner holds the string denoting the lease_owner field in the database.
	FieldLeaseOwner = "lease_owner"
	// FieldLeaseToken holds the string denoting the lease_token field in the database.
	FieldLeaseToken = "lease_token"
	// FieldLeaseExpiresAt holds the string denoting the lease_expires_at field in the database.
	FieldLeaseExpiresAt = "lease_expires_at"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldLastSuccessAt holds the string denoting the last_success_at field in the database.
	FieldLastSuccessAt = "last_success_at"
	// Table holds the table name of the web3scannercursor in the database.
	Table = "web3_scanner_cursors"
)

// Columns holds all SQL columns for web3scannercursor fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldScannerKey,
	FieldChainID,
	FieldTokenContract,
	FieldScanStartBlock,
	FieldLastScannedBlock,
	FieldLastFinalizedBlock,
	FieldLeaseOwner,
	FieldLeaseToken,
	FieldLeaseExpiresAt,
	FieldLastError,
	FieldLastSuccessAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ScannerKeyValidator is a validator for the "scanner_key" field. It is called by the builders before save.
	ScannerKeyValidator func(string) error
	// ChainIDValidator is a validator for the "chain_id" field. It is called by the builders before save.
	ChainIDValidator func(int64) error
	// TokenContractValidator is a validator for the "token_contract" field. It is called by the builders before save.
	TokenContractValidator func(string) error
	// ScanStartBlockValidator is a validator for the "scan_start_block" field. It is called by the builders before save.
	ScanStartBlockValidator func(int64) error
	// LastScannedBlockValidator is a validator for the "last_scanned_block" field. It is called by the builders before save.
	LastScannedBlockValidator func(int64) error
	// LastFinalizedBlockValidator is a validator for the "last_finalized_block" field. It is called by the builders before save.
	LastFinalizedBlockValidator func(int64) error
	// LeaseOwnerValidator is a validator for the "lease_owner" field. It is called by the builders before save.
	LeaseOwnerValidator func(string) error
	// LeaseTokenValidator is a validator for the "lease_token" field. It is called by the builders before save.
	LeaseTokenValidator func(string) error
)

// OrderOption defines the ordering options for the Web3ScannerCursor queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByScannerKey orders the results by the scanner_key field.
func ByScannerKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScannerKey, opts...).ToFunc()
}

// ByChainID orders the results by the chain_id field.
func ByChainID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChainID, opts...).ToFunc()
}

// ByTokenContract orders the results by the token_contract field.
func ByTokenContract(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenContract, opts...).ToFunc()
}

// ByScanStartBlock orders the results by the scan_start_block field.
func ByScanStartBlock(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScanStartBlock, opts...).ToFunc()
}

// ByLastScannedBlock orders the results by the last_scanned_block field.
func ByLastScannedBlock(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastScannedBlock, opts...).ToFunc()
}

// ByLastFinalizedBlock orders the results by the last_finalized_block field.
func ByLastFinalizedBlock(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastFinalizedBlock, opts...).ToFunc()
}

// ByLeaseOwner orders the results by the lease_owner field.
func ByLeaseOwner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeaseOwner, opts...).ToFunc()
}

// ByLeaseToken orders the results by the lease_token field.
func ByLeaseToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeaseToken, opts...).ToFunc()
}

// ByLeaseExpiresAt orders the results by the lease_expires_at field.
func ByLeaseExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeaseExpiresAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByLastSuccessAt orders the results by the last_success_at field.
func ByLastSuccessAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSuccessAt, opts...).ToFunc()
}
