// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/bee"
	"github.com/Wei-Shaw/sub2api/ent/beeplatform"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/google/uuid"
)

// BeeUpdate is the builder for updating Bee entities.
type BeeUpdate struct {
	config
	hooks    []Hook
	mutation *BeeMutation
}

// Where appends a list predicates to the BeeUpdate builder.
func (_u *BeeUpdate) Where(ps ...predicate.Bee) *BeeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BeeUpdate) SetUpdatedAt(v time.Time) *BeeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *BeeUpdate) SetDeletedAt(v time.Time) *BeeUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *BeeUpdate) SetNillableDeletedAt(v *time.Time) *BeeUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *BeeUpdate) ClearDeletedAt() *BeeUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *BeeUpdate) SetUserID(v int64) *BeeUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BeeUpdate) SetNillableUserID(v *int64) *BeeUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *BeeUpdate) SetDeviceID(v uuid.UUID) *BeeUpdate {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *BeeUpdate) SetNillableDeviceID(v *uuid.UUID) *BeeUpdate {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *BeeUpdate) SetName(v string) *BeeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BeeUpdate) SetNillableName(v *string) *BeeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *BeeUpdate) SetStatus(v string) *BeeUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BeeUpdate) SetNillableStatus(v *string) *BeeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCredentialHash sets the "credential_hash" field.
func (_u *BeeUpdate) SetCredentialHash(v string) *BeeUpdate {
	_u.mutation.SetCredentialHash(v)
	return _u
}

// SetNillableCredentialHash sets the "credential_hash" field if the given value is not nil.
func (_u *BeeUpdate) SetNillableCredentialHash(v *string) *BeeUpdate {
	if v != nil {
		_u.SetCredentialHash(*v)
	}
	return _u
}

// SetCredentialCreatedAt sets the "credential_created_at" field.
func (_u *BeeUpdate) SetCredentialCreatedAt(v time.Time) *BeeUpdate {
	_u.mutation.SetCredentialCreatedAt(v)
	return _u
}

// SetNillableCredentialCreatedAt sets the "credential_created_at" field if the given value is not nil.
func (_u *BeeUpdate) SetNillableCredentialCreatedAt(v *time.Time) *BeeUpdate {
	if v != nil {
		_u.SetCredentialCreatedAt(*v)
	}
	return _u
}

// SetAppVersion sets the "app_version" field.
func (_u *BeeUpdate) SetAppVersion(v string) *BeeUpdate {
	_u.mutation.SetAppVersion(v)
	return _u
}

// SetNillableAppVersion sets the "app_version" field if the given value is not nil.
func (_u *BeeUpdate) SetNillableAppVersion(v *string) *BeeUpdate {
	if v != nil {
		_u.SetAppVersion(*v)
	}
	return _u
}

// ClearAppVersion clears the value of the "app_version" field.
func (_u *BeeUpdate) ClearAppVersion() *BeeUpdate {
	_u.mutation.ClearAppVersion()
	return _u
}

// SetLastConnectedAt sets the "last_connected_at" field.
func (_u *BeeUpdate) SetLastConnectedAt(v time.Time) *BeeUpdate {
	_u.mutation.SetLastConnectedAt(v)
	return _u
}

// SetNillableLastConnectedAt sets the "last_connected_at" field if the given value is not nil.
func (_u *BeeUpdate) SetNillableLastConnectedAt(v *time.Time) *BeeUpdate {
	if v != nil {
		_u.SetLastConnectedAt(*v)
	}
	return _u
}

// ClearLastConnectedAt clears the value of the "last_connected_at" field.
func (_u *BeeUpdate) ClearLastConnectedAt() *BeeUpdate {
	_u.mutation.ClearLastConnectedAt()
	return _u
}

// SetLastDisconnectedAt sets the "last_disconnected_at" field.
func (_u *BeeUpdate) SetLastDisconnectedAt(v time.Time) *BeeUpdate {
	_u.mutation.SetLastDisconnectedAt(v)
	return _u
}

// SetNillableLastDisconnectedAt sets the "last_disconnected_at" field if the given value is not nil.
func (_u *BeeUpdate) SetNillableLastDisconnectedAt(v *time.Time) *BeeUpdate {
	if v != nil {
		_u.SetLastDisconnectedAt(*v)
	}
	return _u
}

// ClearLastDisconnectedAt clears the value of the "last_disconnected_at" field.
func (_u *BeeUpdate) ClearLastDisconnectedAt() *BeeUpdate {
	_u.mutation.ClearLastDisconnectedAt()
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *BeeUpdate) SetLastSeenAt(v time.Time) *BeeUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *BeeUpdate) SetNillableLastSeenAt(v *time.Time) *BeeUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (_u *BeeUpdate) ClearLastSeenAt() *BeeUpdate {
	_u.mutation.ClearLastSeenAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *BeeUpdate) SetUser(v *User) *BeeUpdate {
	return _u.SetUserID(v.ID)
}

// AddPlatformIDs adds the "platforms" edge to the BeePlatform entity by IDs.
func (_u *BeeUpdate) AddPlatformIDs(ids ...int64) *BeeUpdate {
	_u.mutation.AddPlatformIDs(ids...)
	return _u
}

// AddPlatforms adds the "platforms" edges to the BeePlatform entity.
func (_u *BeeUpdate) AddPlatforms(v ...*BeePlatform) *BeeUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlatformIDs(ids...)
}

// Mutation returns the BeeMutation object of the builder.
func (_u *BeeUpdate) Mutation() *BeeMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *BeeUpdate) ClearUser() *BeeUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearPlatforms clears all "platforms" edges to the BeePlatform entity.
func (_u *BeeUpdate) ClearPlatforms() *BeeUpdate {
	_u.mutation.ClearPlatforms()
	return _u
}

// RemovePlatformIDs removes the "platforms" edge to BeePlatform entities by IDs.
func (_u *BeeUpdate) RemovePlatformIDs(ids ...int64) *BeeUpdate {
	_u.mutation.RemovePlatformIDs(ids...)
	return _u
}

// RemovePlatforms removes "platforms" edges to BeePlatform entities.
func (_u *BeeUpdate) RemovePlatforms(v ...*BeePlatform) *BeeUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlatformIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BeeUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BeeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BeeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BeeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BeeUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if bee.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized bee.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := bee.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *BeeUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := bee.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Bee.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := bee.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Bee.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CredentialHash(); ok {
		if err := bee.CredentialHashValidator(v); err != nil {
			return &ValidationError{Name: "credential_hash", err: fmt.Errorf(`ent: validator failed for field "Bee.credential_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppVersion(); ok {
		if err := bee.AppVersionValidator(v); err != nil {
			return &ValidationError{Name: "app_version", err: fmt.Errorf(`ent: validator failed for field "Bee.app_version": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Bee.user"`)
	}
	return nil
}

func (_u *BeeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bee.Table, bee.Columns, sqlgraph.NewFieldSpec(bee.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bee.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(bee.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(bee.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(bee.FieldDeviceID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(bee.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(bee.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CredentialHash(); ok {
		_spec.SetField(bee.FieldCredentialHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.CredentialCreatedAt(); ok {
		_spec.SetField(bee.FieldCredentialCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AppVersion(); ok {
		_spec.SetField(bee.FieldAppVersion, field.TypeString, value)
	}
	if _u.mutation.AppVersionCleared() {
		_spec.ClearField(bee.FieldAppVersion, field.TypeString)
	}
	if value, ok := _u.mutation.LastConnectedAt(); ok {
		_spec.SetField(bee.FieldLastConnectedAt, field.TypeTime, value)
	}
	if _u.mutation.LastConnectedAtCleared() {
		_spec.ClearField(bee.FieldLastConnectedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastDisconnectedAt(); ok {
		_spec.SetField(bee.FieldLastDisconnectedAt, field.TypeTime, value)
	}
	if _u.mutation.LastDisconnectedAtCleared() {
		_spec.ClearField(bee.FieldLastDisconnectedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(bee.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenAtCleared() {
		_spec.ClearField(bee.FieldLastSeenAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bee.UserTable,
			Columns: []string{bee.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bee.UserTable,
			Columns: []string{bee.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlatformsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bee.PlatformsTable,
			Columns: []string{bee.PlatformsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(beeplatform.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlatformsIDs(); len(nodes) > 0 && !_u.mutation.PlatformsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bee.PlatformsTable,
			Columns: []string{bee.PlatformsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(beeplatform.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlatformsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bee.PlatformsTable,
			Columns: []string{bee.PlatformsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(beeplatform.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BeeUpdateOne is the builder for updating a single Bee entity.
type BeeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BeeMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BeeUpdateOne) SetUpdatedAt(v time.Time) *BeeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *BeeUpdateOne) SetDeletedAt(v time.Time) *BeeUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *BeeUpdateOne) SetNillableDeletedAt(v *time.Time) *BeeUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *BeeUpdateOne) ClearDeletedAt() *BeeUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *BeeUpdateOne) SetUserID(v int64) *BeeUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BeeUpdateOne) SetNillableUserID(v *int64) *BeeUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *BeeUpdateOne) SetDeviceID(v uuid.UUID) *BeeUpdateOne {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *BeeUpdateOne) SetNillableDeviceID(v *uuid.UUID) *BeeUpdateOne {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *BeeUpdateOne) SetName(v string) *BeeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BeeUpdateOne) SetNillableName(v *string) *BeeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *BeeUpdateOne) SetStatus(v string) *BeeUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BeeUpdateOne) SetNillableStatus(v *string) *BeeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCredentialHash sets the "credential_hash" field.
func (_u *BeeUpdateOne) SetCredentialHash(v string) *BeeUpdateOne {
	_u.mutation.SetCredentialHash(v)
	return _u
}

// SetNillableCredentialHash sets the "credential_hash" field if the given value is not nil.
func (_u *BeeUpdateOne) SetNillableCredentialHash(v *string) *BeeUpdateOne {
	if v != nil {
		_u.SetCredentialHash(*v)
	}
	return _u
}

// SetCredentialCreatedAt sets the "credential_created_at" field.
func (_u *BeeUpdateOne) SetCredentialCreatedAt(v time.Time) *BeeUpdateOne {
	_u.mutation.SetCredentialCreatedAt(v)
	return _u
}

// SetNillableCredentialCreatedAt sets the "credential_created_at" field if the given value is not nil.
func (_u *BeeUpdateOne) SetNillableCredentialCreatedAt(v *time.Time) *BeeUpdateOne {
	if v != nil {
		_u.SetCredentialCreatedAt(*v)
	}
	return _u
}

// SetAppVersion sets the "app_version" field.
func (_u *BeeUpdateOne) SetAppVersion(v string) *BeeUpdateOne {
	_u.mutation.SetAppVersion(v)
	return _u
}

// SetNillableAppVersion sets the "app_version" field if the given value is not nil.
func (_u *BeeUpdateOne) SetNillableAppVersion(v *string) *BeeUpdateOne {
	if v != nil {
		_u.SetAppVersion(*v)
	}
	return _u
}

// ClearAppVersion clears the value of the "app_version" field.
func (_u *BeeUpdateOne) ClearAppVersion() *BeeUpdateOne {
	_u.mutation.ClearAppVersion()
	return _u
}

// SetLastConnectedAt sets the "last_connected_at" field.
func (_u *BeeUpdateOne) SetLastConnectedAt(v time.Time) *BeeUpdateOne {
	_u.mutation.SetLastConnectedAt(v)
	return _u
}

// SetNillableLastConnectedAt sets the "last_connected_at" field if the given value is not nil.
func (_u *BeeUpdateOne) SetNillableLastConnectedAt(v *time.Time) *BeeUpdateOne {
	if v != nil {
		_u.SetLastConnectedAt(*v)
	}
	return _u
}

// ClearLastConnectedAt clears the value of the "last_connected_at" field.
func (_u *BeeUpdateOne) ClearLastConnectedAt() *BeeUpdateOne {
	_u.mutation.ClearLastConnectedAt()
	return _u
}

// SetLastDisconnectedAt sets the "last_disconnected_at" field.
func (_u *BeeUpdateOne) SetLastDisconnectedAt(v time.Time) *BeeUpdateOne {
	_u.mutation.SetLastDisconnectedAt(v)
	return _u
}

// SetNillableLastDisconnectedAt sets the "last_disconnected_at" field if the given value is not nil.
func (_u *BeeUpdateOne) SetNillableLastDisconnectedAt(v *time.Time) *BeeUpdateOne {
	if v != nil {
		_u.SetLastDisconnectedAt(*v)
	}
	return _u
}

// ClearLastDisconnectedAt clears the value of the "last_disconnected_at" field.
func (_u *BeeUpdateOne) ClearLastDisconnectedAt() *BeeUpdateOne {
	_u.mutation.ClearLastDisconnectedAt()
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *BeeUpdateOne) SetLastSeenAt(v time.Time) *BeeUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *BeeUpdateOne) SetNillableLastSeenAt(v *time.Time) *BeeUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (_u *BeeUpdateOne) ClearLastSeenAt() *BeeUpdateOne {
	_u.mutation.ClearLastSeenAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *BeeUpdateOne) SetUser(v *User) *BeeUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddPlatformIDs adds the "platforms" edge to the BeePlatform entity by IDs.
func (_u *BeeUpdateOne) AddPlatformIDs(ids ...int64) *BeeUpdateOne {
	_u.mutation.AddPlatformIDs(ids...)
	return _u
}

// AddPlatforms adds the "platforms" edges to the BeePlatform entity.
func (_u *BeeUpdateOne) AddPlatforms(v ...*BeePlatform) *BeeUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlatformIDs(ids...)
}

// Mutation returns the BeeMutation object of the builder.
func (_u *BeeUpdateOne) Mutation() *BeeMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *BeeUpdateOne) ClearUser() *BeeUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearPlatforms clears all "platforms" edges to the BeePlatform entity.
func (_u *BeeUpdateOne) ClearPlatforms() *BeeUpdateOne {
	_u.mutation.ClearPlatforms()
	return _u
}

// RemovePlatformIDs removes the "platforms" edge to BeePlatform entities by IDs.
func (_u *BeeUpdateOne) RemovePlatformIDs(ids ...int64) *BeeUpdateOne {
	_u.mutation.RemovePlatformIDs(ids...)
	return _u
}

// RemovePlatforms removes "platforms" edges to BeePlatform entities.
func (_u *BeeUpdateOne) RemovePlatforms(v ...*BeePlatform) *BeeUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlatformIDs(ids...)
}

// Where appends a list predicates to the BeeUpdate builder.
func (_u *BeeUpdateOne) Where(ps ...predicate.Bee) *BeeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BeeUpdateOne) Select(field string, fields ...string) *BeeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Bee entity.
func (_u *BeeUpdateOne) Save(ctx context.Context) (*Bee, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BeeUpdateOne) SaveX(ctx context.Context) *Bee {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BeeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BeeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BeeUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if bee.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized bee.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := bee.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *BeeUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := bee.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Bee.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := bee.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Bee.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CredentialHash(); ok {
		if err := bee.CredentialHashValidator(v); err != nil {
			return &ValidationError{Name: "credential_hash", err: fmt.Errorf(`ent: validator failed for field "Bee.credential_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppVersion(); ok {
		if err := bee.AppVersionValidator(v); err != nil {
			return &ValidationError{Name: "app_version", err: fmt.Errorf(`ent: validator failed for field "Bee.app_version": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Bee.user"`)
	}
	return nil
}

func (_u *BeeUpdateOne) sqlSave(ctx context.Context) (_node *Bee, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bee.Table, bee.Columns, sqlgraph.NewFieldSpec(bee.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Bee.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bee.FieldID)
		for _, f := range fields {
			if !bee.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bee.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bee.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(bee.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(bee.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(bee.FieldDeviceID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(bee.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(bee.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CredentialHash(); ok {
		_spec.SetField(bee.FieldCredentialHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.CredentialCreatedAt(); ok {
		_spec.SetField(bee.FieldCredentialCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AppVersion(); ok {
		_spec.SetField(bee.FieldAppVersion, field.TypeString, value)
	}
	if _u.mutation.AppVersionCleared() {
		_spec.ClearField(bee.FieldAppVersion, field.TypeString)
	}
	if value, ok := _u.mutation.LastConnectedAt(); ok {
		_spec.SetField(bee.FieldLastConnectedAt, field.TypeTime, value)
	}
	if _u.mutation.LastConnectedAtCleared() {
		_spec.ClearField(bee.FieldLastConnectedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastDisconnectedAt(); ok {
		_spec.SetField(bee.FieldLastDisconnectedAt, field.TypeTime, value)
	}
	if _u.mutation.LastDisconnectedAtCleared() {
		_spec.ClearField(bee.FieldLastDisconnectedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(bee.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenAtCleared() {
		_spec.ClearField(bee.FieldLastSeenAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bee.UserTable,
			Columns: []string{bee.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bee.UserTable,
			Columns: []string{bee.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlatformsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bee.PlatformsTable,
			Columns: []string{bee.PlatformsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(beeplatform.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlatformsIDs(); len(nodes) > 0 && !_u.mutation.PlatformsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bee.PlatformsTable,
			Columns: []string{bee.PlatformsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(beeplatform.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlatformsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bee.PlatformsTable,
			Columns: []string{bee.PlatformsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(beeplatform.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Bee{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
