// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/bee"
	"github.com/Wei-Shaw/sub2api/ent/beeplatform"
)

// BeePlatformCreate is the builder for creating a BeePlatform entity.
type BeePlatformCreate struct {
	config
	mutation *BeePlatformMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *BeePlatformCreate) SetCreatedAt(v time.Time) *BeePlatformCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BeePlatformCreate) SetNillableCreatedAt(v *time.Time) *BeePlatformCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BeePlatformCreate) SetUpdatedAt(v time.Time) *BeePlatformCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BeePlatformCreate) SetNillableUpdatedAt(v *time.Time) *BeePlatformCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *BeePlatformCreate) SetDeletedAt(v time.Time) *BeePlatformCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *BeePlatformCreate) SetNillableDeletedAt(v *time.Time) *BeePlatformCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetBeeID sets the "bee_id" field.
func (_c *BeePlatformCreate) SetBeeID(v int64) *BeePlatformCreate {
	_c.mutation.SetBeeID(v)
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *BeePlatformCreate) SetPlatform(v string) *BeePlatformCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetUpstreamAccountKey sets the "upstream_account_key" field.
func (_c *BeePlatformCreate) SetUpstreamAccountKey(v string) *BeePlatformCreate {
	_c.mutation.SetUpstreamAccountKey(v)
	return _c
}

// SetIdentityVersion sets the "identity_version" field.
func (_c *BeePlatformCreate) SetIdentityVersion(v int16) *BeePlatformCreate {
	_c.mutation.SetIdentityVersion(v)
	return _c
}

// SetNillableIdentityVersion sets the "identity_version" field if the given value is not nil.
func (_c *BeePlatformCreate) SetNillableIdentityVersion(v *int16) *BeePlatformCreate {
	if v != nil {
		_c.SetIdentityVersion(*v)
	}
	return _c
}

// SetSubscriptionTier sets the "subscription_tier" field.
func (_c *BeePlatformCreate) SetSubscriptionTier(v string) *BeePlatformCreate {
	_c.mutation.SetSubscriptionTier(v)
	return _c
}

// SetNillableSubscriptionTier sets the "subscription_tier" field if the given value is not nil.
func (_c *BeePlatformCreate) SetNillableSubscriptionTier(v *string) *BeePlatformCreate {
	if v != nil {
		_c.SetSubscriptionTier(*v)
	}
	return _c
}

// SetConcurrency sets the "concurrency" field.
func (_c *BeePlatformCreate) SetConcurrency(v int) *BeePlatformCreate {
	_c.mutation.SetConcurrency(v)
	return _c
}

// SetQuotaSnapshot sets the "quota_snapshot" field.
func (_c *BeePlatformCreate) SetQuotaSnapshot(v map[string]interface{}) *BeePlatformCreate {
	_c.mutation.SetQuotaSnapshot(v)
	return _c
}

// SetQuotaUpdatedAt sets the "quota_updated_at" field.
func (_c *BeePlatformCreate) SetQuotaUpdatedAt(v time.Time) *BeePlatformCreate {
	_c.mutation.SetQuotaUpdatedAt(v)
	return _c
}

// SetNillableQuotaUpdatedAt sets the "quota_updated_at" field if the given value is not nil.
func (_c *BeePlatformCreate) SetNillableQuotaUpdatedAt(v *time.Time) *BeePlatformCreate {
	if v != nil {
		_c.SetQuotaUpdatedAt(*v)
	}
	return _c
}

// SetLastTaskAt sets the "last_task_at" field.
func (_c *BeePlatformCreate) SetLastTaskAt(v time.Time) *BeePlatformCreate {
	_c.mutation.SetLastTaskAt(v)
	return _c
}

// SetNillableLastTaskAt sets the "last_task_at" field if the given value is not nil.
func (_c *BeePlatformCreate) SetNillableLastTaskAt(v *time.Time) *BeePlatformCreate {
	if v != nil {
		_c.SetLastTaskAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *BeePlatformCreate) SetStatus(v string) *BeePlatformCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetExtra sets the "extra" field.
func (_c *BeePlatformCreate) SetExtra(v map[string]interface{}) *BeePlatformCreate {
	_c.mutation.SetExtra(v)
	return _c
}

// SetBee sets the "bee" edge to the Bee entity.
func (_c *BeePlatformCreate) SetBee(v *Bee) *BeePlatformCreate {
	return _c.SetBeeID(v.ID)
}

// Mutation returns the BeePlatformMutation object of the builder.
func (_c *BeePlatformCreate) Mutation() *BeePlatformMutation {
	return _c.mutation
}

// Save creates the BeePlatform in the database.
func (_c *BeePlatformCreate) Save(ctx context.Context) (*BeePlatform, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BeePlatformCreate) SaveX(ctx context.Context) *BeePlatform {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BeePlatformCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BeePlatformCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BeePlatformCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if beeplatform.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized beeplatform.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := beeplatform.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if beeplatform.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized beeplatform.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := beeplatform.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IdentityVersion(); !ok {
		v := beeplatform.DefaultIdentityVersion
		_c.mutation.SetIdentityVersion(v)
	}
	if _, ok := _c.mutation.QuotaSnapshot(); !ok {
		if beeplatform.DefaultQuotaSnapshot == nil {
			return fmt.Errorf("ent: uninitialized beeplatform.DefaultQuotaSnapshot (forgotten import ent/runtime?)")
		}
		v := beeplatform.DefaultQuotaSnapshot()
		_c.mutation.SetQuotaSnapshot(v)
	}
	if _, ok := _c.mutation.Extra(); !ok {
		if beeplatform.DefaultExtra == nil {
			return fmt.Errorf("ent: uninitialized beeplatform.DefaultExtra (forgotten import ent/runtime?)")
		}
		v := beeplatform.DefaultExtra()
		_c.mutation.SetExtra(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *BeePlatformCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BeePlatform.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BeePlatform.updated_at"`)}
	}
	if _, ok := _c.mutation.BeeID(); !ok {
		return &ValidationError{Name: "bee_id", err: errors.New(`ent: missing required field "BeePlatform.bee_id"`)}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "BeePlatform.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := beeplatform.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "BeePlatform.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpstreamAccountKey(); !ok {
		return &ValidationError{Name: "upstream_account_key", err: errors.New(`ent: missing required field "BeePlatform.upstream_account_key"`)}
	}
	if v, ok := _c.mutation.UpstreamAccountKey(); ok {
		if err := beeplatform.UpstreamAccountKeyValidator(v); err != nil {
			return &ValidationError{Name: "upstream_account_key", err: fmt.Errorf(`ent: validator failed for field "BeePlatform.upstream_account_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IdentityVersion(); !ok {
		return &ValidationError{Name: "identity_version", err: errors.New(`ent: missing required field "BeePlatform.identity_version"`)}
	}
	if v, ok := _c.mutation.SubscriptionTier(); ok {
		if err := beeplatform.SubscriptionTierValidator(v); err != nil {
			return &ValidationError{Name: "subscription_tier", err: fmt.Errorf(`ent: validator failed for field "BeePlatform.subscription_tier": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Concurrency(); !ok {
		return &ValidationError{Name: "concurrency", err: errors.New(`ent: missing required field "BeePlatform.concurrency"`)}
	}
	if v, ok := _c.mutation.Concurrency(); ok {
		if err := beeplatform.ConcurrencyValidator(v); err != nil {
			return &ValidationError{Name: "concurrency", err: fmt.Errorf(`ent: validator failed for field "BeePlatform.concurrency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.QuotaSnapshot(); !ok {
		return &ValidationError{Name: "quota_snapshot", err: errors.New(`ent: missing required field "BeePlatform.quota_snapshot"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "BeePlatform.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := beeplatform.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BeePlatform.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Extra(); !ok {
		return &ValidationError{Name: "extra", err: errors.New(`ent: missing required field "BeePlatform.extra"`)}
	}
	if len(_c.mutation.BeeIDs()) == 0 {
		return &ValidationError{Name: "bee", err: errors.New(`ent: missing required edge "BeePlatform.bee"`)}
	}
	return nil
}

func (_c *BeePlatformCreate) sqlSave(ctx context.Context) (*BeePlatform, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BeePlatformCreate) createSpec() (*BeePlatform, *sqlgraph.CreateSpec) {
	var (
		_node = &BeePlatform{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(beeplatform.Table, sqlgraph.NewFieldSpec(beeplatform.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(beeplatform.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(beeplatform.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(beeplatform.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(beeplatform.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.UpstreamAccountKey(); ok {
		_spec.SetField(beeplatform.FieldUpstreamAccountKey, field.TypeString, value)
		_node.UpstreamAccountKey = value
	}
	if value, ok := _c.mutation.IdentityVersion(); ok {
		_spec.SetField(beeplatform.FieldIdentityVersion, field.TypeInt16, value)
		_node.IdentityVersion = value
	}
	if value, ok := _c.mutation.SubscriptionTier(); ok {
		_spec.SetField(beeplatform.FieldSubscriptionTier, field.TypeString, value)
		_node.SubscriptionTier = &value
	}
	if value, ok := _c.mutation.Concurrency(); ok {
		_spec.SetField(beeplatform.FieldConcurrency, field.TypeInt, value)
		_node.Concurrency = value
	}
	if value, ok := _c.mutation.QuotaSnapshot(); ok {
		_spec.SetField(beeplatform.FieldQuotaSnapshot, field.TypeJSON, value)
		_node.QuotaSnapshot = value
	}
	if value, ok := _c.mutation.QuotaUpdatedAt(); ok {
		_spec.SetField(beeplatform.FieldQuotaUpdatedAt, field.TypeTime, value)
		_node.QuotaUpdatedAt = &value
	}
	if value, ok := _c.mutation.LastTaskAt(); ok {
		_spec.SetField(beeplatform.FieldLastTaskAt, field.TypeTime, value)
		_node.LastTaskAt = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(beeplatform.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Extra(); ok {
		_spec.SetField(beeplatform.FieldExtra, field.TypeJSON, value)
		_node.Extra = value
	}
	if nodes := _c.mutation.BeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   beeplatform.BeeTable,
			Columns: []string{beeplatform.BeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bee.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BeeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BeePlatform.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BeePlatformUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *BeePlatformCreate) OnConflict(opts ...sql.ConflictOption) *BeePlatformUpsertOne {
	_c.conflict = opts
	return &BeePlatformUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BeePlatform.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BeePlatformCreate) OnConflictColumns(columns ...string) *BeePlatformUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BeePlatformUpsertOne{
		create: _c,
	}
}

type (
	// BeePlatformUpsertOne is the builder for "upsert"-ing
	//  one BeePlatform node.
	BeePlatformUpsertOne struct {
		create *BeePlatformCreate
	}

	// BeePlatformUpsert is the "OnConflict" setter.
	BeePlatformUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *BeePlatformUpsert) SetUpdatedAt(v time.Time) *BeePlatformUpsert {
	u.Set(beeplatform.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BeePlatformUpsert) UpdateUpdatedAt() *BeePlatformUpsert {
	u.SetExcluded(beeplatform.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *BeePlatformUpsert) SetDeletedAt(v time.Time) *BeePlatformUpsert {
	u.Set(beeplatform.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *BeePlatformUpsert) UpdateDeletedAt() *BeePlatformUpsert {
	u.SetExcluded(beeplatform.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *BeePlatformUpsert) ClearDeletedAt() *BeePlatformUpsert {
	u.SetNull(beeplatform.FieldDeletedAt)
	return u
}

// SetBeeID sets the "bee_id" field.
func (u *BeePlatformUpsert) SetBeeID(v int64) *BeePlatformUpsert {
	u.Set(beeplatform.FieldBeeID, v)
	return u
}

// UpdateBeeID sets the "bee_id" field to the value that was provided on create.
func (u *BeePlatformUpsert) UpdateBeeID() *BeePlatformUpsert {
	u.SetExcluded(beeplatform.FieldBeeID)
	return u
}

// SetPlatform sets the "platform" field.
func (u *BeePlatformUpsert) SetPlatform(v string) *BeePlatformUpsert {
	u.Set(beeplatform.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *BeePlatformUpsert) UpdatePlatform() *BeePlatformUpsert {
	u.SetExcluded(beeplatform.FieldPlatform)
	return u
}

// SetUpstreamAccountKey sets the "upstream_account_key" field.
func (u *BeePlatformUpsert) SetUpstreamAccountKey(v string) *BeePlatformUpsert {
	u.Set(beeplatform.FieldUpstreamAccountKey, v)
	return u
}

// UpdateUpstreamAccountKey sets the "upstream_account_key" field to the value that was provided on create.
func (u *BeePlatformUpsert) UpdateUpstreamAccountKey() *BeePlatformUpsert {
	u.SetExcluded(beeplatform.FieldUpstreamAccountKey)
	return u
}

// SetIdentityVersion sets the "identity_version" field.
func (u *BeePlatformUpsert) SetIdentityVersion(v int16) *BeePlatformUpsert {
	u.Set(beeplatform.FieldIdentityVersion, v)
	return u
}

// UpdateIdentityVersion sets the "identity_version" field to the value that was provided on create.
func (u *BeePlatformUpsert) UpdateIdentityVersion() *BeePlatformUpsert {
	u.SetExcluded(beeplatform.FieldIdentityVersion)
	return u
}

// AddIdentityVersion adds v to the "identity_version" field.
func (u *BeePlatformUpsert) AddIdentityVersion(v int16) *BeePlatformUpsert {
	u.Add(beeplatform.FieldIdentityVersion, v)
	return u
}

// SetSubscriptionTier sets the "subscription_tier" field.
func (u *BeePlatformUpsert) SetSubscriptionTier(v string) *BeePlatformUpsert {
	u.Set(beeplatform.FieldSubscriptionTier, v)
	return u
}

// UpdateSubscriptionTier sets the "subscription_tier" field to the value that was provided on create.
func (u *BeePlatformUpsert) UpdateSubscriptionTier() *BeePlatformUpsert {
	u.SetExcluded(beeplatform.FieldSubscriptionTier)
	return u
}

// ClearSubscriptionTier clears the value of the "subscription_tier" field.
func (u *BeePlatformUpsert) ClearSubscriptionTier() *BeePlatformUpsert {
	u.SetNull(beeplatform.FieldSubscriptionTier)
	return u
}

// SetConcurrency sets the "concurrency" field.
func (u *BeePlatformUpsert) SetConcurrency(v int) *BeePlatformUpsert {
	u.Set(beeplatform.FieldConcurrency, v)
	return u
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *BeePlatformUpsert) UpdateConcurrency() *BeePlatformUpsert {
	u.SetExcluded(beeplatform.FieldConcurrency)
	return u
}

// AddConcurrency adds v to the "concurrency" field.
func (u *BeePlatformUpsert) AddConcurrency(v int) *BeePlatformUpsert {
	u.Add(beeplatform.FieldConcurrency, v)
	return u
}

// SetQuotaSnapshot sets the "quota_snapshot" field.
func (u *BeePlatformUpsert) SetQuotaSnapshot(v map[string]interface{}) *BeePlatformUpsert {
	u.Set(beeplatform.FieldQuotaSnapshot, v)
	return u
}

// UpdateQuotaSnapshot sets the "quota_snapshot" field to the value that was provided on create.
func (u *BeePlatformUpsert) UpdateQuotaSnapshot() *BeePlatformUpsert {
	u.SetExcluded(beeplatform.FieldQuotaSnapshot)
	return u
}

// SetQuotaUpdatedAt sets the "quota_updated_at" field.
func (u *BeePlatformUpsert) SetQuotaUpdatedAt(v time.Time) *BeePlatformUpsert {
	u.Set(beeplatform.FieldQuotaUpdatedAt, v)
	return u
}

// UpdateQuotaUpdatedAt sets the "quota_updated_at" field to the value that was provided on create.
func (u *BeePlatformUpsert) UpdateQuotaUpdatedAt() *BeePlatformUpsert {
	u.SetExcluded(beeplatform.FieldQuotaUpdatedAt)
	return u
}

// ClearQuotaUpdatedAt clears the value of the "quota_updated_at" field.
func (u *BeePlatformUpsert) ClearQuotaUpdatedAt() *BeePlatformUpsert {
	u.SetNull(beeplatform.FieldQuotaUpdatedAt)
	return u
}

// SetLastTaskAt sets the "last_task_at" field.
func (u *BeePlatformUpsert) SetLastTaskAt(v time.Time) *BeePlatformUpsert {
	u.Set(beeplatform.FieldLastTaskAt, v)
	return u
}

// UpdateLastTaskAt sets the "last_task_at" field to the value that was provided on create.
func (u *BeePlatformUpsert) UpdateLastTaskAt() *BeePlatformUpsert {
	u.SetExcluded(beeplatform.FieldLastTaskAt)
	return u
}

// ClearLastTaskAt clears the value of the "last_task_at" field.
func (u *BeePlatformUpsert) ClearLastTaskAt() *BeePlatformUpsert {
	u.SetNull(beeplatform.FieldLastTaskAt)
	return u
}

// SetStatus sets the "status" field.
func (u *BeePlatformUpsert) SetStatus(v string) *BeePlatformUpsert {
	u.Set(beeplatform.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BeePlatformUpsert) UpdateStatus() *BeePlatformUpsert {
	u.SetExcluded(beeplatform.FieldStatus)
	return u
}

// SetExtra sets the "extra" field.
func (u *BeePlatformUpsert) SetExtra(v map[string]interface{}) *BeePlatformUpsert {
	u.Set(beeplatform.FieldExtra, v)
	return u
}

// UpdateExtra sets the "extra" field to the value that was provided on create.
func (u *BeePlatformUpsert) UpdateExtra() *BeePlatformUpsert {
	u.SetExcluded(beeplatform.FieldExtra)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BeePlatform.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BeePlatformUpsertOne) UpdateNewValues() *BeePlatformUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(beeplatform.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BeePlatform.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BeePlatformUpsertOne) Ignore() *BeePlatformUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BeePlatformUpsertOne) DoNothing() *BeePlatformUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BeePlatformCreate.OnConflict
// documentation for more info.
func (u *BeePlatformUpsertOne) Update(set func(*BeePlatformUpsert)) *BeePlatformUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BeePlatformUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BeePlatformUpsertOne) SetUpdatedAt(v time.Time) *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BeePlatformUpsertOne) UpdateUpdatedAt() *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *BeePlatformUpsertOne) SetDeletedAt(v time.Time) *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *BeePlatformUpsertOne) UpdateDeletedAt() *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *BeePlatformUpsertOne) ClearDeletedAt() *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.ClearDeletedAt()
	})
}

// SetBeeID sets the "bee_id" field.
func (u *BeePlatformUpsertOne) SetBeeID(v int64) *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetBeeID(v)
	})
}

// UpdateBeeID sets the "bee_id" field to the value that was provided on create.
func (u *BeePlatformUpsertOne) UpdateBeeID() *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdateBeeID()
	})
}

// SetPlatform sets the "platform" field.
func (u *BeePlatformUpsertOne) SetPlatform(v string) *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *BeePlatformUpsertOne) UpdatePlatform() *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdatePlatform()
	})
}

// SetUpstreamAccountKey sets the "upstream_account_key" field.
func (u *BeePlatformUpsertOne) SetUpstreamAccountKey(v string) *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetUpstreamAccountKey(v)
	})
}

// UpdateUpstreamAccountKey sets the "upstream_account_key" field to the value that was provided on create.
func (u *BeePlatformUpsertOne) UpdateUpstreamAccountKey() *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdateUpstreamAccountKey()
	})
}

// SetIdentityVersion sets the "identity_version" field.
func (u *BeePlatformUpsertOne) SetIdentityVersion(v int16) *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetIdentityVersion(v)
	})
}

// AddIdentityVersion adds v to the "identity_version" field.
func (u *BeePlatformUpsertOne) AddIdentityVersion(v int16) *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.AddIdentityVersion(v)
	})
}

// UpdateIdentityVersion sets the "identity_version" field to the value that was provided on create.
func (u *BeePlatformUpsertOne) UpdateIdentityVersion() *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdateIdentityVersion()
	})
}

// SetSubscriptionTier sets the "subscription_tier" field.
func (u *BeePlatformUpsertOne) SetSubscriptionTier(v string) *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetSubscriptionTier(v)
	})
}

// UpdateSubscriptionTier sets the "subscription_tier" field to the value that was provided on create.
func (u *BeePlatformUpsertOne) UpdateSubscriptionTier() *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdateSubscriptionTier()
	})
}

// ClearSubscriptionTier clears the value of the "subscription_tier" field.
func (u *BeePlatformUpsertOne) ClearSubscriptionTier() *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.ClearSubscriptionTier()
	})
}

// SetConcurrency sets the "concurrency" field.
func (u *BeePlatformUpsertOne) SetConcurrency(v int) *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetConcurrency(v)
	})
}

// AddConcurrency adds v to the "concurrency" field.
func (u *BeePlatformUpsertOne) AddConcurrency(v int) *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.AddConcurrency(v)
	})
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *BeePlatformUpsertOne) UpdateConcurrency() *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdateConcurrency()
	})
}

// SetQuotaSnapshot sets the "quota_snapshot" field.
func (u *BeePlatformUpsertOne) SetQuotaSnapshot(v map[string]interface{}) *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetQuotaSnapshot(v)
	})
}

// UpdateQuotaSnapshot sets the "quota_snapshot" field to the value that was provided on create.
func (u *BeePlatformUpsertOne) UpdateQuotaSnapshot() *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdateQuotaSnapshot()
	})
}

// SetQuotaUpdatedAt sets the "quota_updated_at" field.
func (u *BeePlatformUpsertOne) SetQuotaUpdatedAt(v time.Time) *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetQuotaUpdatedAt(v)
	})
}

// UpdateQuotaUpdatedAt sets the "quota_updated_at" field to the value that was provided on create.
func (u *BeePlatformUpsertOne) UpdateQuotaUpdatedAt() *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdateQuotaUpdatedAt()
	})
}

// ClearQuotaUpdatedAt clears the value of the "quota_updated_at" field.
func (u *BeePlatformUpsertOne) ClearQuotaUpdatedAt() *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.ClearQuotaUpdatedAt()
	})
}

// SetLastTaskAt sets the "last_task_at" field.
func (u *BeePlatformUpsertOne) SetLastTaskAt(v time.Time) *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetLastTaskAt(v)
	})
}

// UpdateLastTaskAt sets the "last_task_at" field to the value that was provided on create.
func (u *BeePlatformUpsertOne) UpdateLastTaskAt() *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdateLastTaskAt()
	})
}

// ClearLastTaskAt clears the value of the "last_task_at" field.
func (u *BeePlatformUpsertOne) ClearLastTaskAt() *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.ClearLastTaskAt()
	})
}

// SetStatus sets the "status" field.
func (u *BeePlatformUpsertOne) SetStatus(v string) *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BeePlatformUpsertOne) UpdateStatus() *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdateStatus()
	})
}

// SetExtra sets the "extra" field.
func (u *BeePlatformUpsertOne) SetExtra(v map[string]interface{}) *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetExtra(v)
	})
}

// UpdateExtra sets the "extra" field to the value that was provided on create.
func (u *BeePlatformUpsertOne) UpdateExtra() *BeePlatformUpsertOne {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdateExtra()
	})
}

// Exec executes the query.
func (u *BeePlatformUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BeePlatformCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BeePlatformUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BeePlatformUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BeePlatformUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BeePlatformCreateBulk is the builder for creating many BeePlatform entities in bulk.
type BeePlatformCreateBulk struct {
	config
	err      error
	builders []*BeePlatformCreate
	conflict []sql.ConflictOption
}

// Save creates the BeePlatform entities in the database.
func (_c *BeePlatformCreateBulk) Save(ctx context.Context) ([]*BeePlatform, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BeePlatform, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BeePlatformMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BeePlatformCreateBulk) SaveX(ctx context.Context) []*BeePlatform {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BeePlatformCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BeePlatformCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BeePlatform.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BeePlatformUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *BeePlatformCreateBulk) OnConflict(opts ...sql.ConflictOption) *BeePlatformUpsertBulk {
	_c.conflict = opts
	return &BeePlatformUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BeePlatform.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BeePlatformCreateBulk) OnConflictColumns(columns ...string) *BeePlatformUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BeePlatformUpsertBulk{
		create: _c,
	}
}

// BeePlatformUpsertBulk is the builder for "upsert"-ing
// a bulk of BeePlatform nodes.
type BeePlatformUpsertBulk struct {
	create *BeePlatformCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BeePlatform.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BeePlatformUpsertBulk) UpdateNewValues() *BeePlatformUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(beeplatform.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BeePlatform.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BeePlatformUpsertBulk) Ignore() *BeePlatformUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BeePlatformUpsertBulk) DoNothing() *BeePlatformUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BeePlatformCreateBulk.OnConflict
// documentation for more info.
func (u *BeePlatformUpsertBulk) Update(set func(*BeePlatformUpsert)) *BeePlatformUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BeePlatformUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BeePlatformUpsertBulk) SetUpdatedAt(v time.Time) *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BeePlatformUpsertBulk) UpdateUpdatedAt() *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *BeePlatformUpsertBulk) SetDeletedAt(v time.Time) *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *BeePlatformUpsertBulk) UpdateDeletedAt() *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *BeePlatformUpsertBulk) ClearDeletedAt() *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.ClearDeletedAt()
	})
}

// SetBeeID sets the "bee_id" field.
func (u *BeePlatformUpsertBulk) SetBeeID(v int64) *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetBeeID(v)
	})
}

// UpdateBeeID sets the "bee_id" field to the value that was provided on create.
func (u *BeePlatformUpsertBulk) UpdateBeeID() *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdateBeeID()
	})
}

// SetPlatform sets the "platform" field.
func (u *BeePlatformUpsertBulk) SetPlatform(v string) *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *BeePlatformUpsertBulk) UpdatePlatform() *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdatePlatform()
	})
}

// SetUpstreamAccountKey sets the "upstream_account_key" field.
func (u *BeePlatformUpsertBulk) SetUpstreamAccountKey(v string) *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetUpstreamAccountKey(v)
	})
}

// UpdateUpstreamAccountKey sets the "upstream_account_key" field to the value that was provided on create.
func (u *BeePlatformUpsertBulk) UpdateUpstreamAccountKey() *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdateUpstreamAccountKey()
	})
}

// SetIdentityVersion sets the "identity_version" field.
func (u *BeePlatformUpsertBulk) SetIdentityVersion(v int16) *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetIdentityVersion(v)
	})
}

// AddIdentityVersion adds v to the "identity_version" field.
func (u *BeePlatformUpsertBulk) AddIdentityVersion(v int16) *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.AddIdentityVersion(v)
	})
}

// UpdateIdentityVersion sets the "identity_version" field to the value that was provided on create.
func (u *BeePlatformUpsertBulk) UpdateIdentityVersion() *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdateIdentityVersion()
	})
}

// SetSubscriptionTier sets the "subscription_tier" field.
func (u *BeePlatformUpsertBulk) SetSubscriptionTier(v string) *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetSubscriptionTier(v)
	})
}

// UpdateSubscriptionTier sets the "subscription_tier" field to the value that was provided on create.
func (u *BeePlatformUpsertBulk) UpdateSubscriptionTier() *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdateSubscriptionTier()
	})
}

// ClearSubscriptionTier clears the value of the "subscription_tier" field.
func (u *BeePlatformUpsertBulk) ClearSubscriptionTier() *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.ClearSubscriptionTier()
	})
}

// SetConcurrency sets the "concurrency" field.
func (u *BeePlatformUpsertBulk) SetConcurrency(v int) *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetConcurrency(v)
	})
}

// AddConcurrency adds v to the "concurrency" field.
func (u *BeePlatformUpsertBulk) AddConcurrency(v int) *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.AddConcurrency(v)
	})
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *BeePlatformUpsertBulk) UpdateConcurrency() *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdateConcurrency()
	})
}

// SetQuotaSnapshot sets the "quota_snapshot" field.
func (u *BeePlatformUpsertBulk) SetQuotaSnapshot(v map[string]interface{}) *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetQuotaSnapshot(v)
	})
}

// UpdateQuotaSnapshot sets the "quota_snapshot" field to the value that was provided on create.
func (u *BeePlatformUpsertBulk) UpdateQuotaSnapshot() *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdateQuotaSnapshot()
	})
}

// SetQuotaUpdatedAt sets the "quota_updated_at" field.
func (u *BeePlatformUpsertBulk) SetQuotaUpdatedAt(v time.Time) *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetQuotaUpdatedAt(v)
	})
}

// UpdateQuotaUpdatedAt sets the "quota_updated_at" field to the value that was provided on create.
func (u *BeePlatformUpsertBulk) UpdateQuotaUpdatedAt() *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdateQuotaUpdatedAt()
	})
}

// ClearQuotaUpdatedAt clears the value of the "quota_updated_at" field.
func (u *BeePlatformUpsertBulk) ClearQuotaUpdatedAt() *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.ClearQuotaUpdatedAt()
	})
}

// SetLastTaskAt sets the "last_task_at" field.
func (u *BeePlatformUpsertBulk) SetLastTaskAt(v time.Time) *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetLastTaskAt(v)
	})
}

// UpdateLastTaskAt sets the "last_task_at" field to the value that was provided on create.
func (u *BeePlatformUpsertBulk) UpdateLastTaskAt() *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdateLastTaskAt()
	})
}

// ClearLastTaskAt clears the value of the "last_task_at" field.
func (u *BeePlatformUpsertBulk) ClearLastTaskAt() *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.ClearLastTaskAt()
	})
}

// SetStatus sets the "status" field.
func (u *BeePlatformUpsertBulk) SetStatus(v string) *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BeePlatformUpsertBulk) UpdateStatus() *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdateStatus()
	})
}

// SetExtra sets the "extra" field.
func (u *BeePlatformUpsertBulk) SetExtra(v map[string]interface{}) *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.SetExtra(v)
	})
}

// UpdateExtra sets the "extra" field to the value that was provided on create.
func (u *BeePlatformUpsertBulk) UpdateExtra() *BeePlatformUpsertBulk {
	return u.Update(func(s *BeePlatformUpsert) {
		s.UpdateExtra()
	})
}

// Exec executes the query.
func (u *BeePlatformUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BeePlatformCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BeePlatformCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BeePlatformUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
