// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/bee"
	"github.com/Wei-Shaw/sub2api/ent/beeplatform"
)

// BeePlatform is the model entity for the BeePlatform schema.
type BeePlatform struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// BeeID holds the value of the "bee_id" field.
	BeeID int64 `json:"bee_id,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// UpstreamAccountKey holds the value of the "upstream_account_key" field.
	UpstreamAccountKey string `json:"upstream_account_key,omitempty"`
	// IdentityVersion holds the value of the "identity_version" field.
	IdentityVersion int16 `json:"identity_version,omitempty"`
	// SubscriptionTier holds the value of the "subscription_tier" field.
	SubscriptionTier *string `json:"subscription_tier,omitempty"`
	// Concurrency holds the value of the "concurrency" field.
	Concurrency int `json:"concurrency,omitempty"`
	// QuotaSnapshot holds the value of the "quota_snapshot" field.
	QuotaSnapshot map[string]interface{} `json:"quota_snapshot,omitempty"`
	// QuotaUpdatedAt holds the value of the "quota_updated_at" field.
	QuotaUpdatedAt *time.Time `json:"quota_updated_at,omitempty"`
	// LastTaskAt holds the value of the "last_task_at" field.
	LastTaskAt *time.Time `json:"last_task_at,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Extra holds the value of the "extra" field.
	Extra map[string]interface{} `json:"extra,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BeePlatformQuery when eager-loading is set.
	Edges        BeePlatformEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BeePlatformEdges holds the relations/edges for other nodes in the graph.
type BeePlatformEdges struct {
	// Bee holds the value of the bee edge.
	Bee *Bee `json:"bee,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// BeeOrErr returns the Bee value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BeePlatformEdges) BeeOrErr() (*Bee, error) {
	if e.Bee != nil {
		return e.Bee, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: bee.Label}
	}
	return nil, &NotLoadedError{edge: "bee"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BeePlatform) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case beeplatform.FieldQuotaSnapshot, beeplatform.FieldExtra:
			values[i] = new([]byte)
		case beeplatform.FieldID, beeplatform.FieldBeeID, beeplatform.FieldIdentityVersion, beeplatform.FieldConcurrency:
			values[i] = new(sql.NullInt64)
		case beeplatform.FieldPlatform, beeplatform.FieldUpstreamAccountKey, beeplatform.FieldSubscriptionTier, beeplatform.FieldStatus:
			values[i] = new(sql.NullString)
		case beeplatform.FieldCreatedAt, beeplatform.FieldUpdatedAt, beeplatform.FieldDeletedAt, beeplatform.FieldQuotaUpdatedAt, beeplatform.FieldLastTaskAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BeePlatform fields.
func (_m *BeePlatform) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case beeplatform.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case beeplatform.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case beeplatform.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case beeplatform.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case beeplatform.FieldBeeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bee_id", values[i])
			} else if value.Valid {
				_m.BeeID = value.Int64
			}
		case beeplatform.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case beeplatform.FieldUpstreamAccountKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_account_key", values[i])
			} else if value.Valid {
				_m.UpstreamAccountKey = value.String
			}
		case beeplatform.FieldIdentityVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field identity_version", values[i])
			} else if value.Valid {
				_m.IdentityVersion = int16(value.Int64)
			}
		case beeplatform.FieldSubscriptionTier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_tier", values[i])
			} else if value.Valid {
				_m.SubscriptionTier = new(string)
				*_m.SubscriptionTier = value.String
			}
		case beeplatform.FieldConcurrency:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field concurrency", values[i])
			} else if value.Valid {
				_m.Concurrency = int(value.Int64)
			}
		case beeplatform.FieldQuotaSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field quota_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.QuotaSnapshot); err != nil {
					return fmt.Errorf("unmarshal field quota_snapshot: %w", err)
				}
			}
		case beeplatform.FieldQuotaUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field quota_updated_at", values[i])
			} else if value.Valid {
				_m.QuotaUpdatedAt = new(time.Time)
				*_m.QuotaUpdatedAt = value.Time
			}
		case beeplatform.FieldLastTaskAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_task_at", values[i])
			} else if value.Valid {
				_m.LastTaskAt = new(time.Time)
				*_m.LastTaskAt = value.Time
			}
		case beeplatform.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case beeplatform.FieldExtra:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field extra", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Extra); err != nil {
					return fmt.Errorf("unmarshal field extra: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BeePlatform.
// This includes values selected through modifiers, order, etc.
func (_m *BeePlatform) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryBee queries the "bee" edge of the BeePlatform entity.
func (_m *BeePlatform) QueryBee() *BeeQuery {
	return NewBeePlatformClient(_m.config).QueryBee(_m)
}

// Update returns a builder for updating this BeePlatform.
// Note that you need to call BeePlatform.Unwrap() before calling this method if this BeePlatform
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BeePlatform) Update() *BeePlatformUpdateOne {
	return NewBeePlatformClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BeePlatform entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BeePlatform) Unwrap() *BeePlatform {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BeePlatform is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BeePlatform) String() string {
	var builder strings.Builder
	builder.WriteString("BeePlatform(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("bee_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BeeID))
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("upstream_account_key=")
	builder.WriteString(_m.UpstreamAccountKey)
	builder.WriteString(", ")
	builder.WriteString("identity_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.IdentityVersion))
	builder.WriteString(", ")
	if v := _m.SubscriptionTier; v != nil {
		builder.WriteString("subscription_tier=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("concurrency=")
	builder.WriteString(fmt.Sprintf("%v", _m.Concurrency))
	builder.WriteString(", ")
	builder.WriteString("quota_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.QuotaSnapshot))
	builder.WriteString(", ")
	if v := _m.QuotaUpdatedAt; v != nil {
		builder.WriteString("quota_updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastTaskAt; v != nil {
		builder.WriteString("last_task_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("extra=")
	builder.WriteString(fmt.Sprintf("%v", _m.Extra))
	builder.WriteByte(')')
	return builder.String()
}

// BeePlatforms is a parsable slice of BeePlatform.
type BeePlatforms []*BeePlatform
