// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/web3balancetransfer"
)

// Web3BalanceTransferUpdate is the builder for updating Web3BalanceTransfer entities.
type Web3BalanceTransferUpdate struct {
	config
	hooks    []Hook
	mutation *Web3BalanceTransferMutation
}

// Where appends a list predicates to the Web3BalanceTransferUpdate builder.
func (_u *Web3BalanceTransferUpdate) Where(ps ...predicate.Web3BalanceTransfer) *Web3BalanceTransferUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the Web3BalanceTransferMutation object of the builder.
func (_u *Web3BalanceTransferUpdate) Mutation() *Web3BalanceTransferMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *Web3BalanceTransferUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *Web3BalanceTransferUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *Web3BalanceTransferUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *Web3BalanceTransferUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *Web3BalanceTransferUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(web3balancetransfer.Table, web3balancetransfer.Columns, sqlgraph.NewFieldSpec(web3balancetransfer.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{web3balancetransfer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// Web3BalanceTransferUpdateOne is the builder for updating a single Web3BalanceTransfer entity.
type Web3BalanceTransferUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *Web3BalanceTransferMutation
}

// Mutation returns the Web3BalanceTransferMutation object of the builder.
func (_u *Web3BalanceTransferUpdateOne) Mutation() *Web3BalanceTransferMutation {
	return _u.mutation
}

// Where appends a list predicates to the Web3BalanceTransferUpdate builder.
func (_u *Web3BalanceTransferUpdateOne) Where(ps ...predicate.Web3BalanceTransfer) *Web3BalanceTransferUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *Web3BalanceTransferUpdateOne) Select(field string, fields ...string) *Web3BalanceTransferUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Web3BalanceTransfer entity.
func (_u *Web3BalanceTransferUpdateOne) Save(ctx context.Context) (*Web3BalanceTransfer, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *Web3BalanceTransferUpdateOne) SaveX(ctx context.Context) *Web3BalanceTransfer {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *Web3BalanceTransferUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *Web3BalanceTransferUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *Web3BalanceTransferUpdateOne) sqlSave(ctx context.Context) (_node *Web3BalanceTransfer, err error) {
	_spec := sqlgraph.NewUpdateSpec(web3balancetransfer.Table, web3balancetransfer.Columns, sqlgraph.NewFieldSpec(web3balancetransfer.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Web3BalanceTransfer.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, web3balancetransfer.FieldID)
		for _, f := range fields {
			if !web3balancetransfer.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != web3balancetransfer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &Web3BalanceTransfer{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{web3balancetransfer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
