// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/web3scannercursor"
)

// Web3ScannerCursorDelete is the builder for deleting a Web3ScannerCursor entity.
type Web3ScannerCursorDelete struct {
	config
	hooks    []Hook
	mutation *Web3ScannerCursorMutation
}

// Where appends a list predicates to the Web3ScannerCursorDelete builder.
func (_d *Web3ScannerCursorDelete) Where(ps ...predicate.Web3ScannerCursor) *Web3ScannerCursorDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *Web3ScannerCursorDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *Web3ScannerCursorDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *Web3ScannerCursorDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(web3scannercursor.Table, sqlgraph.NewFieldSpec(web3scannercursor.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// Web3ScannerCursorDeleteOne is the builder for deleting a single Web3ScannerCursor entity.
type Web3ScannerCursorDeleteOne struct {
	_d *Web3ScannerCursorDelete
}

// Where appends a list predicates to the Web3ScannerCursorDelete builder.
func (_d *Web3ScannerCursorDeleteOne) Where(ps ...predicate.Web3ScannerCursor) *Web3ScannerCursorDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *Web3ScannerCursorDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{web3scannercursor.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *Web3ScannerCursorDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
