// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/web3scannercursor"
)

// Web3ScannerCursorCreate is the builder for creating a Web3ScannerCursor entity.
type Web3ScannerCursorCreate struct {
	config
	mutation *Web3ScannerCursorMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *Web3ScannerCursorCreate) SetCreatedAt(v time.Time) *Web3ScannerCursorCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *Web3ScannerCursorCreate) SetNillableCreatedAt(v *time.Time) *Web3ScannerCursorCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *Web3ScannerCursorCreate) SetUpdatedAt(v time.Time) *Web3ScannerCursorCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *Web3ScannerCursorCreate) SetNillableUpdatedAt(v *time.Time) *Web3ScannerCursorCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetScannerKey sets the "scanner_key" field.
func (_c *Web3ScannerCursorCreate) SetScannerKey(v string) *Web3ScannerCursorCreate {
	_c.mutation.SetScannerKey(v)
	return _c
}

// SetChainID sets the "chain_id" field.
func (_c *Web3ScannerCursorCreate) SetChainID(v int64) *Web3ScannerCursorCreate {
	_c.mutation.SetChainID(v)
	return _c
}

// SetTokenContract sets the "token_contract" field.
func (_c *Web3ScannerCursorCreate) SetTokenContract(v string) *Web3ScannerCursorCreate {
	_c.mutation.SetTokenContract(v)
	return _c
}

// SetScanStartBlock sets the "scan_start_block" field.
func (_c *Web3ScannerCursorCreate) SetScanStartBlock(v int64) *Web3ScannerCursorCreate {
	_c.mutation.SetScanStartBlock(v)
	return _c
}

// SetLastScannedBlock sets the "last_scanned_block" field.
func (_c *Web3ScannerCursorCreate) SetLastScannedBlock(v int64) *Web3ScannerCursorCreate {
	_c.mutation.SetLastScannedBlock(v)
	return _c
}

// SetLastFinalizedBlock sets the "last_finalized_block" field.
func (_c *Web3ScannerCursorCreate) SetLastFinalizedBlock(v int64) *Web3ScannerCursorCreate {
	_c.mutation.SetLastFinalizedBlock(v)
	return _c
}

// SetLeaseOwner sets the "lease_owner" field.
func (_c *Web3ScannerCursorCreate) SetLeaseOwner(v string) *Web3ScannerCursorCreate {
	_c.mutation.SetLeaseOwner(v)
	return _c
}

// SetNillableLeaseOwner sets the "lease_owner" field if the given value is not nil.
func (_c *Web3ScannerCursorCreate) SetNillableLeaseOwner(v *string) *Web3ScannerCursorCreate {
	if v != nil {
		_c.SetLeaseOwner(*v)
	}
	return _c
}

// SetLeaseToken sets the "lease_token" field.
func (_c *Web3ScannerCursorCreate) SetLeaseToken(v string) *Web3ScannerCursorCreate {
	_c.mutation.SetLeaseToken(v)
	return _c
}

// SetNillableLeaseToken sets the "lease_token" field if the given value is not nil.
func (_c *Web3ScannerCursorCreate) SetNillableLeaseToken(v *string) *Web3ScannerCursorCreate {
	if v != nil {
		_c.SetLeaseToken(*v)
	}
	return _c
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (_c *Web3ScannerCursorCreate) SetLeaseExpiresAt(v time.Time) *Web3ScannerCursorCreate {
	_c.mutation.SetLeaseExpiresAt(v)
	return _c
}

// SetNillableLeaseExpiresAt sets the "lease_expires_at" field if the given value is not nil.
func (_c *Web3ScannerCursorCreate) SetNillableLeaseExpiresAt(v *time.Time) *Web3ScannerCursorCreate {
	if v != nil {
		_c.SetLeaseExpiresAt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *Web3ScannerCursorCreate) SetLastError(v string) *Web3ScannerCursorCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *Web3ScannerCursorCreate) SetNillableLastError(v *string) *Web3ScannerCursorCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetLastSuccessAt sets the "last_success_at" field.
func (_c *Web3ScannerCursorCreate) SetLastSuccessAt(v time.Time) *Web3ScannerCursorCreate {
	_c.mutation.SetLastSuccessAt(v)
	return _c
}

// SetNillableLastSuccessAt sets the "last_success_at" field if the given value is not nil.
func (_c *Web3ScannerCursorCreate) SetNillableLastSuccessAt(v *time.Time) *Web3ScannerCursorCreate {
	if v != nil {
		_c.SetLastSuccessAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *Web3ScannerCursorCreate) SetID(v int64) *Web3ScannerCursorCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the Web3ScannerCursorMutation object of the builder.
func (_c *Web3ScannerCursorCreate) Mutation() *Web3ScannerCursorMutation {
	return _c.mutation
}

// Save creates the Web3ScannerCursor in the database.
func (_c *Web3ScannerCursorCreate) Save(ctx context.Context) (*Web3ScannerCursor, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *Web3ScannerCursorCreate) SaveX(ctx context.Context) *Web3ScannerCursor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *Web3ScannerCursorCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *Web3ScannerCursorCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *Web3ScannerCursorCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := web3scannercursor.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := web3scannercursor.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *Web3ScannerCursorCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Web3ScannerCursor.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Web3ScannerCursor.updated_at"`)}
	}
	if _, ok := _c.mutation.ScannerKey(); !ok {
		return &ValidationError{Name: "scanner_key", err: errors.New(`ent: missing required field "Web3ScannerCursor.scanner_key"`)}
	}
	if v, ok := _c.mutation.ScannerKey(); ok {
		if err := web3scannercursor.ScannerKeyValidator(v); err != nil {
			return &ValidationError{Name: "scanner_key", err: fmt.Errorf(`ent: validator failed for field "Web3ScannerCursor.scanner_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChainID(); !ok {
		return &ValidationError{Name: "chain_id", err: errors.New(`ent: missing required field "Web3ScannerCursor.chain_id"`)}
	}
	if v, ok := _c.mutation.ChainID(); ok {
		if err := web3scannercursor.ChainIDValidator(v); err != nil {
			return &ValidationError{Name: "chain_id", err: fmt.Errorf(`ent: validator failed for field "Web3ScannerCursor.chain_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenContract(); !ok {
		return &ValidationError{Name: "token_contract", err: errors.New(`ent: missing required field "Web3ScannerCursor.token_contract"`)}
	}
	if v, ok := _c.mutation.TokenContract(); ok {
		if err := web3scannercursor.TokenContractValidator(v); err != nil {
			return &ValidationError{Name: "token_contract", err: fmt.Errorf(`ent: validator failed for field "Web3ScannerCursor.token_contract": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScanStartBlock(); !ok {
		return &ValidationError{Name: "scan_start_block", err: errors.New(`ent: missing required field "Web3ScannerCursor.scan_start_block"`)}
	}
	if v, ok := _c.mutation.ScanStartBlock(); ok {
		if err := web3scannercursor.ScanStartBlockValidator(v); err != nil {
			return &ValidationError{Name: "scan_start_block", err: fmt.Errorf(`ent: validator failed for field "Web3ScannerCursor.scan_start_block": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastScannedBlock(); !ok {
		return &ValidationError{Name: "last_scanned_block", err: errors.New(`ent: missing required field "Web3ScannerCursor.last_scanned_block"`)}
	}
	if v, ok := _c.mutation.LastScannedBlock(); ok {
		if err := web3scannercursor.LastScannedBlockValidator(v); err != nil {
			return &ValidationError{Name: "last_scanned_block", err: fmt.Errorf(`ent: validator failed for field "Web3ScannerCursor.last_scanned_block": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastFinalizedBlock(); !ok {
		return &ValidationError{Name: "last_finalized_block", err: errors.New(`ent: missing required field "Web3ScannerCursor.last_finalized_block"`)}
	}
	if v, ok := _c.mutation.LastFinalizedBlock(); ok {
		if err := web3scannercursor.LastFinalizedBlockValidator(v); err != nil {
			return &ValidationError{Name: "last_finalized_block", err: fmt.Errorf(`ent: validator failed for field "Web3ScannerCursor.last_finalized_block": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LeaseOwner(); ok {
		if err := web3scannercursor.LeaseOwnerValidator(v); err != nil {
			return &ValidationError{Name: "lease_owner", err: fmt.Errorf(`ent: validator failed for field "Web3ScannerCursor.lease_owner": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LeaseToken(); ok {
		if err := web3scannercursor.LeaseTokenValidator(v); err != nil {
			return &ValidationError{Name: "lease_token", err: fmt.Errorf(`ent: validator failed for field "Web3ScannerCursor.lease_token": %w`, err)}
		}
	}
	return nil
}

func (_c *Web3ScannerCursorCreate) sqlSave(ctx context.Context) (*Web3ScannerCursor, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *Web3ScannerCursorCreate) createSpec() (*Web3ScannerCursor, *sqlgraph.CreateSpec) {
	var (
		_node = &Web3ScannerCursor{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(web3scannercursor.Table, sqlgraph.NewFieldSpec(web3scannercursor.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(web3scannercursor.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(web3scannercursor.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ScannerKey(); ok {
		_spec.SetField(web3scannercursor.FieldScannerKey, field.TypeString, value)
		_node.ScannerKey = value
	}
	if value, ok := _c.mutation.ChainID(); ok {
		_spec.SetField(web3scannercursor.FieldChainID, field.TypeInt64, value)
		_node.ChainID = value
	}
	if value, ok := _c.mutation.TokenContract(); ok {
		_spec.SetField(web3scannercursor.FieldTokenContract, field.TypeString, value)
		_node.TokenContract = value
	}
	if value, ok := _c.mutation.ScanStartBlock(); ok {
		_spec.SetField(web3scannercursor.FieldScanStartBlock, field.TypeInt64, value)
		_node.ScanStartBlock = value
	}
	if value, ok := _c.mutation.LastScannedBlock(); ok {
		_spec.SetField(web3scannercursor.FieldLastScannedBlock, field.TypeInt64, value)
		_node.LastScannedBlock = value
	}
	if value, ok := _c.mutation.LastFinalizedBlock(); ok {
		_spec.SetField(web3scannercursor.FieldLastFinalizedBlock, field.TypeInt64, value)
		_node.LastFinalizedBlock = value
	}
	if value, ok := _c.mutation.LeaseOwner(); ok {
		_spec.SetField(web3scannercursor.FieldLeaseOwner, field.TypeString, value)
		_node.LeaseOwner = &value
	}
	if value, ok := _c.mutation.LeaseToken(); ok {
		_spec.SetField(web3scannercursor.FieldLeaseToken, field.TypeString, value)
		_node.LeaseToken = &value
	}
	if value, ok := _c.mutation.LeaseExpiresAt(); ok {
		_spec.SetField(web3scannercursor.FieldLeaseExpiresAt, field.TypeTime, value)
		_node.LeaseExpiresAt = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(web3scannercursor.FieldLastError, field.TypeString, value)
		_node.LastError = &value
	}
	if value, ok := _c.mutation.LastSuccessAt(); ok {
		_spec.SetField(web3scannercursor.FieldLastSuccessAt, field.TypeTime, value)
		_node.LastSuccessAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Web3ScannerCursor.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.Web3ScannerCursorUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *Web3ScannerCursorCreate) OnConflict(opts ...sql.ConflictOption) *Web3ScannerCursorUpsertOne {
	_c.conflict = opts
	return &Web3ScannerCursorUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Web3ScannerCursor.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *Web3ScannerCursorCreate) OnConflictColumns(columns ...string) *Web3ScannerCursorUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &Web3ScannerCursorUpsertOne{
		create: _c,
	}
}

type (
	// Web3ScannerCursorUpsertOne is the builder for "upsert"-ing
	//  one Web3ScannerCursor node.
	Web3ScannerCursorUpsertOne struct {
		create *Web3ScannerCursorCreate
	}

	// Web3ScannerCursorUpsert is the "OnConflict" setter.
	Web3ScannerCursorUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *Web3ScannerCursorUpsert) SetUpdatedAt(v time.Time) *Web3ScannerCursorUpsert {
	u.Set(web3scannercursor.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *Web3ScannerCursorUpsert) UpdateUpdatedAt() *Web3ScannerCursorUpsert {
	u.SetExcluded(web3scannercursor.FieldUpdatedAt)
	return u
}

// SetLastScannedBlock sets the "last_scanned_block" field.
func (u *Web3ScannerCursorUpsert) SetLastScannedBlock(v int64) *Web3ScannerCursorUpsert {
	u.Set(web3scannercursor.FieldLastScannedBlock, v)
	return u
}

// UpdateLastScannedBlock sets the "last_scanned_block" field to the value that was provided on create.
func (u *Web3ScannerCursorUpsert) UpdateLastScannedBlock() *Web3ScannerCursorUpsert {
	u.SetExcluded(web3scannercursor.FieldLastScannedBlock)
	return u
}

// AddLastScannedBlock adds v to the "last_scanned_block" field.
func (u *Web3ScannerCursorUpsert) AddLastScannedBlock(v int64) *Web3ScannerCursorUpsert {
	u.Add(web3scannercursor.FieldLastScannedBlock, v)
	return u
}

// SetLastFinalizedBlock sets the "last_finalized_block" field.
func (u *Web3ScannerCursorUpsert) SetLastFinalizedBlock(v int64) *Web3ScannerCursorUpsert {
	u.Set(web3scannercursor.FieldLastFinalizedBlock, v)
	return u
}

// UpdateLastFinalizedBlock sets the "last_finalized_block" field to the value that was provided on create.
func (u *Web3ScannerCursorUpsert) UpdateLastFinalizedBlock() *Web3ScannerCursorUpsert {
	u.SetExcluded(web3scannercursor.FieldLastFinalizedBlock)
	return u
}

// AddLastFinalizedBlock adds v to the "last_finalized_block" field.
func (u *Web3ScannerCursorUpsert) AddLastFinalizedBlock(v int64) *Web3ScannerCursorUpsert {
	u.Add(web3scannercursor.FieldLastFinalizedBlock, v)
	return u
}

// SetLeaseOwner sets the "lease_owner" field.
func (u *Web3ScannerCursorUpsert) SetLeaseOwner(v string) *Web3ScannerCursorUpsert {
	u.Set(web3scannercursor.FieldLeaseOwner, v)
	return u
}

// UpdateLeaseOwner sets the "lease_owner" field to the value that was provided on create.
func (u *Web3ScannerCursorUpsert) UpdateLeaseOwner() *Web3ScannerCursorUpsert {
	u.SetExcluded(web3scannercursor.FieldLeaseOwner)
	return u
}

// ClearLeaseOwner clears the value of the "lease_owner" field.
func (u *Web3ScannerCursorUpsert) ClearLeaseOwner() *Web3ScannerCursorUpsert {
	u.SetNull(web3scannercursor.FieldLeaseOwner)
	return u
}

// SetLeaseToken sets the "lease_token" field.
func (u *Web3ScannerCursorUpsert) SetLeaseToken(v string) *Web3ScannerCursorUpsert {
	u.Set(web3scannercursor.FieldLeaseToken, v)
	return u
}

// UpdateLeaseToken sets the "lease_token" field to the value that was provided on create.
func (u *Web3ScannerCursorUpsert) UpdateLeaseToken() *Web3ScannerCursorUpsert {
	u.SetExcluded(web3scannercursor.FieldLeaseToken)
	return u
}

// ClearLeaseToken clears the value of the "lease_token" field.
func (u *Web3ScannerCursorUpsert) ClearLeaseToken() *Web3ScannerCursorUpsert {
	u.SetNull(web3scannercursor.FieldLeaseToken)
	return u
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (u *Web3ScannerCursorUpsert) SetLeaseExpiresAt(v time.Time) *Web3ScannerCursorUpsert {
	u.Set(web3scannercursor.FieldLeaseExpiresAt, v)
	return u
}

// UpdateLeaseExpiresAt sets the "lease_expires_at" field to the value that was provided on create.
func (u *Web3ScannerCursorUpsert) UpdateLeaseExpiresAt() *Web3ScannerCursorUpsert {
	u.SetExcluded(web3scannercursor.FieldLeaseExpiresAt)
	return u
}

// ClearLeaseExpiresAt clears the value of the "lease_expires_at" field.
func (u *Web3ScannerCursorUpsert) ClearLeaseExpiresAt() *Web3ScannerCursorUpsert {
	u.SetNull(web3scannercursor.FieldLeaseExpiresAt)
	return u
}

// SetLastError sets the "last_error" field.
func (u *Web3ScannerCursorUpsert) SetLastError(v string) *Web3ScannerCursorUpsert {
	u.Set(web3scannercursor.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *Web3ScannerCursorUpsert) UpdateLastError() *Web3ScannerCursorUpsert {
	u.SetExcluded(web3scannercursor.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *Web3ScannerCursorUpsert) ClearLastError() *Web3ScannerCursorUpsert {
	u.SetNull(web3scannercursor.FieldLastError)
	return u
}

// SetLastSuccessAt sets the "last_success_at" field.
func (u *Web3ScannerCursorUpsert) SetLastSuccessAt(v time.Time) *Web3ScannerCursorUpsert {
	u.Set(web3scannercursor.FieldLastSuccessAt, v)
	return u
}

// UpdateLastSuccessAt sets the "last_success_at" field to the value that was provided on create.
func (u *Web3ScannerCursorUpsert) UpdateLastSuccessAt() *Web3ScannerCursorUpsert {
	u.SetExcluded(web3scannercursor.FieldLastSuccessAt)
	return u
}

// ClearLastSuccessAt clears the value of the "last_success_at" field.
func (u *Web3ScannerCursorUpsert) ClearLastSuccessAt() *Web3ScannerCursorUpsert {
	u.SetNull(web3scannercursor.FieldLastSuccessAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Web3ScannerCursor.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(web3scannercursor.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *Web3ScannerCursorUpsertOne) UpdateNewValues() *Web3ScannerCursorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(web3scannercursor.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(web3scannercursor.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.ScannerKey(); exists {
			s.SetIgnore(web3scannercursor.FieldScannerKey)
		}
		if _, exists := u.create.mutation.ChainID(); exists {
			s.SetIgnore(web3scannercursor.FieldChainID)
		}
		if _, exists := u.create.mutation.TokenContract(); exists {
			s.SetIgnore(web3scannercursor.FieldTokenContract)
		}
		if _, exists := u.create.mutation.ScanStartBlock(); exists {
			s.SetIgnore(web3scannercursor.FieldScanStartBlock)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Web3ScannerCursor.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *Web3ScannerCursorUpsertOne) Ignore() *Web3ScannerCursorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *Web3ScannerCursorUpsertOne) DoNothing() *Web3ScannerCursorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the Web3ScannerCursorCreate.OnConflict
// documentation for more info.
func (u *Web3ScannerCursorUpsertOne) Update(set func(*Web3ScannerCursorUpsert)) *Web3ScannerCursorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&Web3ScannerCursorUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *Web3ScannerCursorUpsertOne) SetUpdatedAt(v time.Time) *Web3ScannerCursorUpsertOne {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *Web3ScannerCursorUpsertOne) UpdateUpdatedAt() *Web3ScannerCursorUpsertOne {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetLastScannedBlock sets the "last_scanned_block" field.
func (u *Web3ScannerCursorUpsertOne) SetLastScannedBlock(v int64) *Web3ScannerCursorUpsertOne {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.SetLastScannedBlock(v)
	})
}

// AddLastScannedBlock adds v to the "last_scanned_block" field.
func (u *Web3ScannerCursorUpsertOne) AddLastScannedBlock(v int64) *Web3ScannerCursorUpsertOne {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.AddLastScannedBlock(v)
	})
}

// UpdateLastScannedBlock sets the "last_scanned_block" field to the value that was provided on create.
func (u *Web3ScannerCursorUpsertOne) UpdateLastScannedBlock() *Web3ScannerCursorUpsertOne {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.UpdateLastScannedBlock()
	})
}

// SetLastFinalizedBlock sets the "last_finalized_block" field.
func (u *Web3ScannerCursorUpsertOne) SetLastFinalizedBlock(v int64) *Web3ScannerCursorUpsertOne {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.SetLastFinalizedBlock(v)
	})
}

// AddLastFinalizedBlock adds v to the "last_finalized_block" field.
func (u *Web3ScannerCursorUpsertOne) AddLastFinalizedBlock(v int64) *Web3ScannerCursorUpsertOne {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.AddLastFinalizedBlock(v)
	})
}

// UpdateLastFinalizedBlock sets the "last_finalized_block" field to the value that was provided on create.
func (u *Web3ScannerCursorUpsertOne) UpdateLastFinalizedBlock() *Web3ScannerCursorUpsertOne {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.UpdateLastFinalizedBlock()
	})
}

// SetLeaseOwner sets the "lease_owner" field.
func (u *Web3ScannerCursorUpsertOne) SetLeaseOwner(v string) *Web3ScannerCursorUpsertOne {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.SetLeaseOwner(v)
	})
}

// UpdateLeaseOwner sets the "lease_owner" field to the value that was provided on create.
func (u *Web3ScannerCursorUpsertOne) UpdateLeaseOwner() *Web3ScannerCursorUpsertOne {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.UpdateLeaseOwner()
	})
}

// ClearLeaseOwner clears the value of the "lease_owner" field.
func (u *Web3ScannerCursorUpsertOne) ClearLeaseOwner() *Web3ScannerCursorUpsertOne {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.ClearLeaseOwner()
	})
}

// SetLeaseToken sets the "lease_token" field.
func (u *Web3ScannerCursorUpsertOne) SetLeaseToken(v string) *Web3ScannerCursorUpsertOne {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.SetLeaseToken(v)
	})
}

// UpdateLeaseToken sets the "lease_token" field to the value that was provided on create.
func (u *Web3ScannerCursorUpsertOne) UpdateLeaseToken() *Web3ScannerCursorUpsertOne {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.UpdateLeaseToken()
	})
}

// ClearLeaseToken clears the value of the "lease_token" field.
func (u *Web3ScannerCursorUpsertOne) ClearLeaseToken() *Web3ScannerCursorUpsertOne {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.ClearLeaseToken()
	})
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (u *Web3ScannerCursorUpsertOne) SetLeaseExpiresAt(v time.Time) *Web3ScannerCursorUpsertOne {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.SetLeaseExpiresAt(v)
	})
}

// UpdateLeaseExpiresAt sets the "lease_expires_at" field to the value that was provided on create.
func (u *Web3ScannerCursorUpsertOne) UpdateLeaseExpiresAt() *Web3ScannerCursorUpsertOne {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.UpdateLeaseExpiresAt()
	})
}

// ClearLeaseExpiresAt clears the value of the "lease_expires_at" field.
func (u *Web3ScannerCursorUpsertOne) ClearLeaseExpiresAt() *Web3ScannerCursorUpsertOne {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.ClearLeaseExpiresAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *Web3ScannerCursorUpsertOne) SetLastError(v string) *Web3ScannerCursorUpsertOne {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *Web3ScannerCursorUpsertOne) UpdateLastError() *Web3ScannerCursorUpsertOne {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *Web3ScannerCursorUpsertOne) ClearLastError() *Web3ScannerCursorUpsertOne {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.ClearLastError()
	})
}

// SetLastSuccessAt sets the "last_success_at" field.
func (u *Web3ScannerCursorUpsertOne) SetLastSuccessAt(v time.Time) *Web3ScannerCursorUpsertOne {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.SetLastSuccessAt(v)
	})
}

// UpdateLastSuccessAt sets the "last_success_at" field to the value that was provided on create.
func (u *Web3ScannerCursorUpsertOne) UpdateLastSuccessAt() *Web3ScannerCursorUpsertOne {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.UpdateLastSuccessAt()
	})
}

// ClearLastSuccessAt clears the value of the "last_success_at" field.
func (u *Web3ScannerCursorUpsertOne) ClearLastSuccessAt() *Web3ScannerCursorUpsertOne {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.ClearLastSuccessAt()
	})
}

// Exec executes the query.
func (u *Web3ScannerCursorUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for Web3ScannerCursorCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *Web3ScannerCursorUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *Web3ScannerCursorUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *Web3ScannerCursorUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// Web3ScannerCursorCreateBulk is the builder for creating many Web3ScannerCursor entities in bulk.
type Web3ScannerCursorCreateBulk struct {
	config
	err      error
	builders []*Web3ScannerCursorCreate
	conflict []sql.ConflictOption
}

// Save creates the Web3ScannerCursor entities in the database.
func (_c *Web3ScannerCursorCreateBulk) Save(ctx context.Context) ([]*Web3ScannerCursor, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Web3ScannerCursor, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*Web3ScannerCursorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *Web3ScannerCursorCreateBulk) SaveX(ctx context.Context) []*Web3ScannerCursor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *Web3ScannerCursorCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *Web3ScannerCursorCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Web3ScannerCursor.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.Web3ScannerCursorUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *Web3ScannerCursorCreateBulk) OnConflict(opts ...sql.ConflictOption) *Web3ScannerCursorUpsertBulk {
	_c.conflict = opts
	return &Web3ScannerCursorUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Web3ScannerCursor.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *Web3ScannerCursorCreateBulk) OnConflictColumns(columns ...string) *Web3ScannerCursorUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &Web3ScannerCursorUpsertBulk{
		create: _c,
	}
}

// Web3ScannerCursorUpsertBulk is the builder for "upsert"-ing
// a bulk of Web3ScannerCursor nodes.
type Web3ScannerCursorUpsertBulk struct {
	create *Web3ScannerCursorCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Web3ScannerCursor.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(web3scannercursor.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *Web3ScannerCursorUpsertBulk) UpdateNewValues() *Web3ScannerCursorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(web3scannercursor.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(web3scannercursor.FieldCreatedAt)
			}
			if _, exists := b.mutation.ScannerKey(); exists {
				s.SetIgnore(web3scannercursor.FieldScannerKey)
			}
			if _, exists := b.mutation.ChainID(); exists {
				s.SetIgnore(web3scannercursor.FieldChainID)
			}
			if _, exists := b.mutation.TokenContract(); exists {
				s.SetIgnore(web3scannercursor.FieldTokenContract)
			}
			if _, exists := b.mutation.ScanStartBlock(); exists {
				s.SetIgnore(web3scannercursor.FieldScanStartBlock)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Web3ScannerCursor.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *Web3ScannerCursorUpsertBulk) Ignore() *Web3ScannerCursorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *Web3ScannerCursorUpsertBulk) DoNothing() *Web3ScannerCursorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the Web3ScannerCursorCreateBulk.OnConflict
// documentation for more info.
func (u *Web3ScannerCursorUpsertBulk) Update(set func(*Web3ScannerCursorUpsert)) *Web3ScannerCursorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&Web3ScannerCursorUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *Web3ScannerCursorUpsertBulk) SetUpdatedAt(v time.Time) *Web3ScannerCursorUpsertBulk {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *Web3ScannerCursorUpsertBulk) UpdateUpdatedAt() *Web3ScannerCursorUpsertBulk {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetLastScannedBlock sets the "last_scanned_block" field.
func (u *Web3ScannerCursorUpsertBulk) SetLastScannedBlock(v int64) *Web3ScannerCursorUpsertBulk {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.SetLastScannedBlock(v)
	})
}

// AddLastScannedBlock adds v to the "last_scanned_block" field.
func (u *Web3ScannerCursorUpsertBulk) AddLastScannedBlock(v int64) *Web3ScannerCursorUpsertBulk {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.AddLastScannedBlock(v)
	})
}

// UpdateLastScannedBlock sets the "last_scanned_block" field to the value that was provided on create.
func (u *Web3ScannerCursorUpsertBulk) UpdateLastScannedBlock() *Web3ScannerCursorUpsertBulk {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.UpdateLastScannedBlock()
	})
}

// SetLastFinalizedBlock sets the "last_finalized_block" field.
func (u *Web3ScannerCursorUpsertBulk) SetLastFinalizedBlock(v int64) *Web3ScannerCursorUpsertBulk {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.SetLastFinalizedBlock(v)
	})
}

// AddLastFinalizedBlock adds v to the "last_finalized_block" field.
func (u *Web3ScannerCursorUpsertBulk) AddLastFinalizedBlock(v int64) *Web3ScannerCursorUpsertBulk {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.AddLastFinalizedBlock(v)
	})
}

// UpdateLastFinalizedBlock sets the "last_finalized_block" field to the value that was provided on create.
func (u *Web3ScannerCursorUpsertBulk) UpdateLastFinalizedBlock() *Web3ScannerCursorUpsertBulk {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.UpdateLastFinalizedBlock()
	})
}

// SetLeaseOwner sets the "lease_owner" field.
func (u *Web3ScannerCursorUpsertBulk) SetLeaseOwner(v string) *Web3ScannerCursorUpsertBulk {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.SetLeaseOwner(v)
	})
}

// UpdateLeaseOwner sets the "lease_owner" field to the value that was provided on create.
func (u *Web3ScannerCursorUpsertBulk) UpdateLeaseOwner() *Web3ScannerCursorUpsertBulk {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.UpdateLeaseOwner()
	})
}

// ClearLeaseOwner clears the value of the "lease_owner" field.
func (u *Web3ScannerCursorUpsertBulk) ClearLeaseOwner() *Web3ScannerCursorUpsertBulk {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.ClearLeaseOwner()
	})
}

// SetLeaseToken sets the "lease_token" field.
func (u *Web3ScannerCursorUpsertBulk) SetLeaseToken(v string) *Web3ScannerCursorUpsertBulk {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.SetLeaseToken(v)
	})
}

// UpdateLeaseToken sets the "lease_token" field to the value that was provided on create.
func (u *Web3ScannerCursorUpsertBulk) UpdateLeaseToken() *Web3ScannerCursorUpsertBulk {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.UpdateLeaseToken()
	})
}

// ClearLeaseToken clears the value of the "lease_token" field.
func (u *Web3ScannerCursorUpsertBulk) ClearLeaseToken() *Web3ScannerCursorUpsertBulk {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.ClearLeaseToken()
	})
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (u *Web3ScannerCursorUpsertBulk) SetLeaseExpiresAt(v time.Time) *Web3ScannerCursorUpsertBulk {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.SetLeaseExpiresAt(v)
	})
}

// UpdateLeaseExpiresAt sets the "lease_expires_at" field to the value that was provided on create.
func (u *Web3ScannerCursorUpsertBulk) UpdateLeaseExpiresAt() *Web3ScannerCursorUpsertBulk {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.UpdateLeaseExpiresAt()
	})
}

// ClearLeaseExpiresAt clears the value of the "lease_expires_at" field.
func (u *Web3ScannerCursorUpsertBulk) ClearLeaseExpiresAt() *Web3ScannerCursorUpsertBulk {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.ClearLeaseExpiresAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *Web3ScannerCursorUpsertBulk) SetLastError(v string) *Web3ScannerCursorUpsertBulk {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *Web3ScannerCursorUpsertBulk) UpdateLastError() *Web3ScannerCursorUpsertBulk {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *Web3ScannerCursorUpsertBulk) ClearLastError() *Web3ScannerCursorUpsertBulk {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.ClearLastError()
	})
}

// SetLastSuccessAt sets the "last_success_at" field.
func (u *Web3ScannerCursorUpsertBulk) SetLastSuccessAt(v time.Time) *Web3ScannerCursorUpsertBulk {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.SetLastSuccessAt(v)
	})
}

// UpdateLastSuccessAt sets the "last_success_at" field to the value that was provided on create.
func (u *Web3ScannerCursorUpsertBulk) UpdateLastSuccessAt() *Web3ScannerCursorUpsertBulk {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.UpdateLastSuccessAt()
	})
}

// ClearLastSuccessAt clears the value of the "last_success_at" field.
func (u *Web3ScannerCursorUpsertBulk) ClearLastSuccessAt() *Web3ScannerCursorUpsertBulk {
	return u.Update(func(s *Web3ScannerCursorUpsert) {
		s.ClearLastSuccessAt()
	})
}

// Exec executes the query.
func (u *Web3ScannerCursorUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the Web3ScannerCursorCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for Web3ScannerCursorCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *Web3ScannerCursorUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
