// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/web3scannercursor"
)

// Web3ScannerCursor is the model entity for the Web3ScannerCursor schema.
type Web3ScannerCursor struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ScannerKey holds the value of the "scanner_key" field.
	ScannerKey string `json:"scanner_key,omitempty"`
	// ChainID holds the value of the "chain_id" field.
	ChainID int64 `json:"chain_id,omitempty"`
	// TokenContract holds the value of the "token_contract" field.
	TokenContract string `json:"token_contract,omitempty"`
	// ScanStartBlock holds the value of the "scan_start_block" field.
	ScanStartBlock int64 `json:"scan_start_block,omitempty"`
	// LastScannedBlock holds the value of the "last_scanned_block" field.
	LastScannedBlock int64 `json:"last_scanned_block,omitempty"`
	// LastFinalizedBlock holds the value of the "last_finalized_block" field.
	LastFinalizedBlock int64 `json:"last_finalized_block,omitempty"`
	// LeaseOwner holds the value of the "lease_owner" field.
	LeaseOwner *string `json:"lease_owner,omitempty"`
	// LeaseToken holds the value of the "lease_token" field.
	LeaseToken *string `json:"lease_token,omitempty"`
	// LeaseExpiresAt holds the value of the "lease_expires_at" field.
	LeaseExpiresAt *time.Time `json:"lease_expires_at,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError *string `json:"last_error,omitempty"`
	// LastSuccessAt holds the value of the "last_success_at" field.
	LastSuccessAt *time.Time `json:"last_success_at,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Web3ScannerCursor) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case web3scannercursor.FieldID, web3scannercursor.FieldChainID, web3scannercursor.FieldScanStartBlock, web3scannercursor.FieldLastScannedBlock, web3scannercursor.FieldLastFinalizedBlock:
			values[i] = new(sql.NullInt64)
		case web3scannercursor.FieldScannerKey, web3scannercursor.FieldTokenContract, web3scannercursor.FieldLeaseOwner, web3scannercursor.FieldLeaseToken, web3scannercursor.FieldLastError:
			values[i] = new(sql.NullString)
		case web3scannercursor.FieldCreatedAt, web3scannercursor.FieldUpdatedAt, web3scannercursor.FieldLeaseExpiresAt, web3scannercursor.FieldLastSuccessAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Web3ScannerCursor fields.
func (_m *Web3ScannerCursor) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case web3scannercursor.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case web3scannercursor.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case web3scannercursor.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case web3scannercursor.FieldScannerKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scanner_key", values[i])
			} else if value.Valid {
				_m.ScannerKey = value.String
			}
		case web3scannercursor.FieldChainID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chain_id", values[i])
			} else if value.Valid {
				_m.ChainID = value.Int64
			}
		case web3scannercursor.FieldTokenContract:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_contract", values[i])
			} else if value.Valid {
				_m.TokenContract = value.String
			}
		case web3scannercursor.FieldScanStartBlock:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field scan_start_block", values[i])
			} else if value.Valid {
				_m.ScanStartBlock = value.Int64
			}
		case web3scannercursor.FieldLastScannedBlock:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_scanned_block", values[i])
			} else if value.Valid {
				_m.LastScannedBlock = value.Int64
			}
		case web3scannercursor.FieldLastFinalizedBlock:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_finalized_block", values[i])
			} else if value.Valid {
				_m.LastFinalizedBlock = value.Int64
			}
		case web3scannercursor.FieldLeaseOwner:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lease_owner", values[i])
			} else if value.Valid {
				_m.LeaseOwner = new(string)
				*_m.LeaseOwner = value.String
			}
		case web3scannercursor.FieldLeaseToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lease_token", values[i])
			} else if value.Valid {
				_m.LeaseToken = new(string)
				*_m.LeaseToken = value.String
			}
		case web3scannercursor.FieldLeaseExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field lease_expires_at", values[i])
			} else if value.Valid {
				_m.LeaseExpiresAt = new(time.Time)
				*_m.LeaseExpiresAt = value.Time
			}
		case web3scannercursor.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		case web3scannercursor.FieldLastSuccessAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_success_at", values[i])
			} else if value.Valid {
				_m.LastSuccessAt = new(time.Time)
				*_m.LastSuccessAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Web3ScannerCursor.
// This includes values selected through modifiers, order, etc.
func (_m *Web3ScannerCursor) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Web3ScannerCursor.
// Note that you need to call Web3ScannerCursor.Unwrap() before calling this method if this Web3ScannerCursor
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Web3ScannerCursor) Update() *Web3ScannerCursorUpdateOne {
	return NewWeb3ScannerCursorClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Web3ScannerCursor entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Web3ScannerCursor) Unwrap() *Web3ScannerCursor {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Web3ScannerCursor is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Web3ScannerCursor) String() string {
	var builder strings.Builder
	builder.WriteString("Web3ScannerCursor(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("scanner_key=")
	builder.WriteString(_m.ScannerKey)
	builder.WriteString(", ")
	builder.WriteString("chain_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChainID))
	builder.WriteString(", ")
	builder.WriteString("token_contract=")
	builder.WriteString(_m.TokenContract)
	builder.WriteString(", ")
	builder.WriteString("scan_start_block=")
	builder.WriteString(fmt.Sprintf("%v", _m.ScanStartBlock))
	builder.WriteString(", ")
	builder.WriteString("last_scanned_block=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastScannedBlock))
	builder.WriteString(", ")
	builder.WriteString("last_finalized_block=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastFinalizedBlock))
	builder.WriteString(", ")
	if v := _m.LeaseOwner; v != nil {
		builder.WriteString("lease_owner=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LeaseToken; v != nil {
		builder.WriteString("lease_token=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LeaseExpiresAt; v != nil {
		builder.WriteString("lease_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("last_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastSuccessAt; v != nil {
		builder.WriteString("last_success_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Web3ScannerCursors is a parsable slice of Web3ScannerCursor.
type Web3ScannerCursors []*Web3ScannerCursor
