// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/web3depositwallet"
)

// Web3DepositWalletUpdate is the builder for updating Web3DepositWallet entities.
type Web3DepositWalletUpdate struct {
	config
	hooks    []Hook
	mutation *Web3DepositWalletMutation
}

// Where appends a list predicates to the Web3DepositWalletUpdate builder.
func (_u *Web3DepositWalletUpdate) Where(ps ...predicate.Web3DepositWallet) *Web3DepositWalletUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *Web3DepositWalletUpdate) SetUpdatedAt(v time.Time) *Web3DepositWalletUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNextDerivationIndex sets the "next_derivation_index" field.
func (_u *Web3DepositWalletUpdate) SetNextDerivationIndex(v int64) *Web3DepositWalletUpdate {
	_u.mutation.ResetNextDerivationIndex()
	_u.mutation.SetNextDerivationIndex(v)
	return _u
}

// SetNillableNextDerivationIndex sets the "next_derivation_index" field if the given value is not nil.
func (_u *Web3DepositWalletUpdate) SetNillableNextDerivationIndex(v *int64) *Web3DepositWalletUpdate {
	if v != nil {
		_u.SetNextDerivationIndex(*v)
	}
	return _u
}

// AddNextDerivationIndex adds value to the "next_derivation_index" field.
func (_u *Web3DepositWalletUpdate) AddNextDerivationIndex(v int64) *Web3DepositWalletUpdate {
	_u.mutation.AddNextDerivationIndex(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *Web3DepositWalletUpdate) SetStatus(v string) *Web3DepositWalletUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *Web3DepositWalletUpdate) SetNillableStatus(v *string) *Web3DepositWalletUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the Web3DepositWalletMutation object of the builder.
func (_u *Web3DepositWalletUpdate) Mutation() *Web3DepositWalletMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *Web3DepositWalletUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *Web3DepositWalletUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *Web3DepositWalletUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *Web3DepositWalletUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *Web3DepositWalletUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := web3depositwallet.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *Web3DepositWalletUpdate) check() error {
	if v, ok := _u.mutation.NextDerivationIndex(); ok {
		if err := web3depositwallet.NextDerivationIndexValidator(v); err != nil {
			return &ValidationError{Name: "next_derivation_index", err: fmt.Errorf(`ent: validator failed for field "Web3DepositWallet.next_derivation_index": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := web3depositwallet.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Web3DepositWallet.status": %w`, err)}
		}
	}
	return nil
}

func (_u *Web3DepositWalletUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(web3depositwallet.Table, web3depositwallet.Columns, sqlgraph.NewFieldSpec(web3depositwallet.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(web3depositwallet.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.NextDerivationIndex(); ok {
		_spec.SetField(web3depositwallet.FieldNextDerivationIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNextDerivationIndex(); ok {
		_spec.AddField(web3depositwallet.FieldNextDerivationIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(web3depositwallet.FieldStatus, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{web3depositwallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// Web3DepositWalletUpdateOne is the builder for updating a single Web3DepositWallet entity.
type Web3DepositWalletUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *Web3DepositWalletMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *Web3DepositWalletUpdateOne) SetUpdatedAt(v time.Time) *Web3DepositWalletUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNextDerivationIndex sets the "next_derivation_index" field.
func (_u *Web3DepositWalletUpdateOne) SetNextDerivationIndex(v int64) *Web3DepositWalletUpdateOne {
	_u.mutation.ResetNextDerivationIndex()
	_u.mutation.SetNextDerivationIndex(v)
	return _u
}

// SetNillableNextDerivationIndex sets the "next_derivation_index" field if the given value is not nil.
func (_u *Web3DepositWalletUpdateOne) SetNillableNextDerivationIndex(v *int64) *Web3DepositWalletUpdateOne {
	if v != nil {
		_u.SetNextDerivationIndex(*v)
	}
	return _u
}

// AddNextDerivationIndex adds value to the "next_derivation_index" field.
func (_u *Web3DepositWalletUpdateOne) AddNextDerivationIndex(v int64) *Web3DepositWalletUpdateOne {
	_u.mutation.AddNextDerivationIndex(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *Web3DepositWalletUpdateOne) SetStatus(v string) *Web3DepositWalletUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *Web3DepositWalletUpdateOne) SetNillableStatus(v *string) *Web3DepositWalletUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the Web3DepositWalletMutation object of the builder.
func (_u *Web3DepositWalletUpdateOne) Mutation() *Web3DepositWalletMutation {
	return _u.mutation
}

// Where appends a list predicates to the Web3DepositWalletUpdate builder.
func (_u *Web3DepositWalletUpdateOne) Where(ps ...predicate.Web3DepositWallet) *Web3DepositWalletUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *Web3DepositWalletUpdateOne) Select(field string, fields ...string) *Web3DepositWalletUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Web3DepositWallet entity.
func (_u *Web3DepositWalletUpdateOne) Save(ctx context.Context) (*Web3DepositWallet, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *Web3DepositWalletUpdateOne) SaveX(ctx context.Context) *Web3DepositWallet {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *Web3DepositWalletUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *Web3DepositWalletUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *Web3DepositWalletUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := web3depositwallet.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *Web3DepositWalletUpdateOne) check() error {
	if v, ok := _u.mutation.NextDerivationIndex(); ok {
		if err := web3depositwallet.NextDerivationIndexValidator(v); err != nil {
			return &ValidationError{Name: "next_derivation_index", err: fmt.Errorf(`ent: validator failed for field "Web3DepositWallet.next_derivation_index": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := web3depositwallet.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Web3DepositWallet.status": %w`, err)}
		}
	}
	return nil
}

func (_u *Web3DepositWalletUpdateOne) sqlSave(ctx context.Context) (_node *Web3DepositWallet, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(web3depositwallet.Table, web3depositwallet.Columns, sqlgraph.NewFieldSpec(web3depositwallet.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Web3DepositWallet.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, web3depositwallet.FieldID)
		for _, f := range fields {
			if !web3depositwallet.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != web3depositwallet.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(web3depositwallet.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.NextDerivationIndex(); ok {
		_spec.SetField(web3depositwallet.FieldNextDerivationIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNextDerivationIndex(); ok {
		_spec.AddField(web3depositwallet.FieldNextDerivationIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(web3depositwallet.FieldStatus, field.TypeString, value)
	}
	_node = &Web3DepositWallet{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{web3depositwallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
