// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/web3depositwallet"
)

// Web3DepositWalletCreate is the builder for creating a Web3DepositWallet entity.
type Web3DepositWalletCreate struct {
	config
	mutation *Web3DepositWalletMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *Web3DepositWalletCreate) SetCreatedAt(v time.Time) *Web3DepositWalletCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *Web3DepositWalletCreate) SetNillableCreatedAt(v *time.Time) *Web3DepositWalletCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *Web3DepositWalletCreate) SetUpdatedAt(v time.Time) *Web3DepositWalletCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *Web3DepositWalletCreate) SetNillableUpdatedAt(v *time.Time) *Web3DepositWalletCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetWalletID sets the "wallet_id" field.
func (_c *Web3DepositWalletCreate) SetWalletID(v string) *Web3DepositWalletCreate {
	_c.mutation.SetWalletID(v)
	return _c
}

// SetAccountPath sets the "account_path" field.
func (_c *Web3DepositWalletCreate) SetAccountPath(v string) *Web3DepositWalletCreate {
	_c.mutation.SetAccountPath(v)
	return _c
}

// SetXpubFingerprint sets the "xpub_fingerprint" field.
func (_c *Web3DepositWalletCreate) SetXpubFingerprint(v string) *Web3DepositWalletCreate {
	_c.mutation.SetXpubFingerprint(v)
	return _c
}

// SetNextDerivationIndex sets the "next_derivation_index" field.
func (_c *Web3DepositWalletCreate) SetNextDerivationIndex(v int64) *Web3DepositWalletCreate {
	_c.mutation.SetNextDerivationIndex(v)
	return _c
}

// SetNillableNextDerivationIndex sets the "next_derivation_index" field if the given value is not nil.
func (_c *Web3DepositWalletCreate) SetNillableNextDerivationIndex(v *int64) *Web3DepositWalletCreate {
	if v != nil {
		_c.SetNextDerivationIndex(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *Web3DepositWalletCreate) SetStatus(v string) *Web3DepositWalletCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *Web3DepositWalletCreate) SetNillableStatus(v *string) *Web3DepositWalletCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *Web3DepositWalletCreate) SetID(v int64) *Web3DepositWalletCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the Web3DepositWalletMutation object of the builder.
func (_c *Web3DepositWalletCreate) Mutation() *Web3DepositWalletMutation {
	return _c.mutation
}

// Save creates the Web3DepositWallet in the database.
func (_c *Web3DepositWalletCreate) Save(ctx context.Context) (*Web3DepositWallet, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *Web3DepositWalletCreate) SaveX(ctx context.Context) *Web3DepositWallet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *Web3DepositWalletCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *Web3DepositWalletCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *Web3DepositWalletCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := web3depositwallet.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := web3depositwallet.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.NextDerivationIndex(); !ok {
		v := web3depositwallet.DefaultNextDerivationIndex
		_c.mutation.SetNextDerivationIndex(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := web3depositwallet.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *Web3DepositWalletCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Web3DepositWallet.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Web3DepositWallet.updated_at"`)}
	}
	if _, ok := _c.mutation.WalletID(); !ok {
		return &ValidationError{Name: "wallet_id", err: errors.New(`ent: missing required field "Web3DepositWallet.wallet_id"`)}
	}
	if v, ok := _c.mutation.WalletID(); ok {
		if err := web3depositwallet.WalletIDValidator(v); err != nil {
			return &ValidationError{Name: "wallet_id", err: fmt.Errorf(`ent: validator failed for field "Web3DepositWallet.wallet_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountPath(); !ok {
		return &ValidationError{Name: "account_path", err: errors.New(`ent: missing required field "Web3DepositWallet.account_path"`)}
	}
	if v, ok := _c.mutation.AccountPath(); ok {
		if err := web3depositwallet.AccountPathValidator(v); err != nil {
			return &ValidationError{Name: "account_path", err: fmt.Errorf(`ent: validator failed for field "Web3DepositWallet.account_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.XpubFingerprint(); !ok {
		return &ValidationError{Name: "xpub_fingerprint", err: errors.New(`ent: missing required field "Web3DepositWallet.xpub_fingerprint"`)}
	}
	if v, ok := _c.mutation.XpubFingerprint(); ok {
		if err := web3depositwallet.XpubFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "xpub_fingerprint", err: fmt.Errorf(`ent: validator failed for field "Web3DepositWallet.xpub_fingerprint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NextDerivationIndex(); !ok {
		return &ValidationError{Name: "next_derivation_index", err: errors.New(`ent: missing required field "Web3DepositWallet.next_derivation_index"`)}
	}
	if v, ok := _c.mutation.NextDerivationIndex(); ok {
		if err := web3depositwallet.NextDerivationIndexValidator(v); err != nil {
			return &ValidationError{Name: "next_derivation_index", err: fmt.Errorf(`ent: validator failed for field "Web3DepositWallet.next_derivation_index": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Web3DepositWallet.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := web3depositwallet.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Web3DepositWallet.status": %w`, err)}
		}
	}
	return nil
}

func (_c *Web3DepositWalletCreate) sqlSave(ctx context.Context) (*Web3DepositWallet, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *Web3DepositWalletCreate) createSpec() (*Web3DepositWallet, *sqlgraph.CreateSpec) {
	var (
		_node = &Web3DepositWallet{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(web3depositwallet.Table, sqlgraph.NewFieldSpec(web3depositwallet.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(web3depositwallet.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(web3depositwallet.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.WalletID(); ok {
		_spec.SetField(web3depositwallet.FieldWalletID, field.TypeString, value)
		_node.WalletID = value
	}
	if value, ok := _c.mutation.AccountPath(); ok {
		_spec.SetField(web3depositwallet.FieldAccountPath, field.TypeString, value)
		_node.AccountPath = value
	}
	if value, ok := _c.mutation.XpubFingerprint(); ok {
		_spec.SetField(web3depositwallet.FieldXpubFingerprint, field.TypeString, value)
		_node.XpubFingerprint = value
	}
	if value, ok := _c.mutation.NextDerivationIndex(); ok {
		_spec.SetField(web3depositwallet.FieldNextDerivationIndex, field.TypeInt64, value)
		_node.NextDerivationIndex = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(web3depositwallet.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Web3DepositWallet.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.Web3DepositWalletUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *Web3DepositWalletCreate) OnConflict(opts ...sql.ConflictOption) *Web3DepositWalletUpsertOne {
	_c.conflict = opts
	return &Web3DepositWalletUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Web3DepositWallet.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *Web3DepositWalletCreate) OnConflictColumns(columns ...string) *Web3DepositWalletUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &Web3DepositWalletUpsertOne{
		create: _c,
	}
}

type (
	// Web3DepositWalletUpsertOne is the builder for "upsert"-ing
	//  one Web3DepositWallet node.
	Web3DepositWalletUpsertOne struct {
		create *Web3DepositWalletCreate
	}

	// Web3DepositWalletUpsert is the "OnConflict" setter.
	Web3DepositWalletUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *Web3DepositWalletUpsert) SetUpdatedAt(v time.Time) *Web3DepositWalletUpsert {
	u.Set(web3depositwallet.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *Web3DepositWalletUpsert) UpdateUpdatedAt() *Web3DepositWalletUpsert {
	u.SetExcluded(web3depositwallet.FieldUpdatedAt)
	return u
}

// SetNextDerivationIndex sets the "next_derivation_index" field.
func (u *Web3DepositWalletUpsert) SetNextDerivationIndex(v int64) *Web3DepositWalletUpsert {
	u.Set(web3depositwallet.FieldNextDerivationIndex, v)
	return u
}

// UpdateNextDerivationIndex sets the "next_derivation_index" field to the value that was provided on create.
func (u *Web3DepositWalletUpsert) UpdateNextDerivationIndex() *Web3DepositWalletUpsert {
	u.SetExcluded(web3depositwallet.FieldNextDerivationIndex)
	return u
}

// AddNextDerivationIndex adds v to the "next_derivation_index" field.
func (u *Web3DepositWalletUpsert) AddNextDerivationIndex(v int64) *Web3DepositWalletUpsert {
	u.Add(web3depositwallet.FieldNextDerivationIndex, v)
	return u
}

// SetStatus sets the "status" field.
func (u *Web3DepositWalletUpsert) SetStatus(v string) *Web3DepositWalletUpsert {
	u.Set(web3depositwallet.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *Web3DepositWalletUpsert) UpdateStatus() *Web3DepositWalletUpsert {
	u.SetExcluded(web3depositwallet.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Web3DepositWallet.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(web3depositwallet.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *Web3DepositWalletUpsertOne) UpdateNewValues() *Web3DepositWalletUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(web3depositwallet.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(web3depositwallet.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.WalletID(); exists {
			s.SetIgnore(web3depositwallet.FieldWalletID)
		}
		if _, exists := u.create.mutation.AccountPath(); exists {
			s.SetIgnore(web3depositwallet.FieldAccountPath)
		}
		if _, exists := u.create.mutation.XpubFingerprint(); exists {
			s.SetIgnore(web3depositwallet.FieldXpubFingerprint)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Web3DepositWallet.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *Web3DepositWalletUpsertOne) Ignore() *Web3DepositWalletUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *Web3DepositWalletUpsertOne) DoNothing() *Web3DepositWalletUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the Web3DepositWalletCreate.OnConflict
// documentation for more info.
func (u *Web3DepositWalletUpsertOne) Update(set func(*Web3DepositWalletUpsert)) *Web3DepositWalletUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&Web3DepositWalletUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *Web3DepositWalletUpsertOne) SetUpdatedAt(v time.Time) *Web3DepositWalletUpsertOne {
	return u.Update(func(s *Web3DepositWalletUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *Web3DepositWalletUpsertOne) UpdateUpdatedAt() *Web3DepositWalletUpsertOne {
	return u.Update(func(s *Web3DepositWalletUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetNextDerivationIndex sets the "next_derivation_index" field.
func (u *Web3DepositWalletUpsertOne) SetNextDerivationIndex(v int64) *Web3DepositWalletUpsertOne {
	return u.Update(func(s *Web3DepositWalletUpsert) {
		s.SetNextDerivationIndex(v)
	})
}

// AddNextDerivationIndex adds v to the "next_derivation_index" field.
func (u *Web3DepositWalletUpsertOne) AddNextDerivationIndex(v int64) *Web3DepositWalletUpsertOne {
	return u.Update(func(s *Web3DepositWalletUpsert) {
		s.AddNextDerivationIndex(v)
	})
}

// UpdateNextDerivationIndex sets the "next_derivation_index" field to the value that was provided on create.
func (u *Web3DepositWalletUpsertOne) UpdateNextDerivationIndex() *Web3DepositWalletUpsertOne {
	return u.Update(func(s *Web3DepositWalletUpsert) {
		s.UpdateNextDerivationIndex()
	})
}

// SetStatus sets the "status" field.
func (u *Web3DepositWalletUpsertOne) SetStatus(v string) *Web3DepositWalletUpsertOne {
	return u.Update(func(s *Web3DepositWalletUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *Web3DepositWalletUpsertOne) UpdateStatus() *Web3DepositWalletUpsertOne {
	return u.Update(func(s *Web3DepositWalletUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *Web3DepositWalletUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for Web3DepositWalletCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *Web3DepositWalletUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *Web3DepositWalletUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *Web3DepositWalletUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// Web3DepositWalletCreateBulk is the builder for creating many Web3DepositWallet entities in bulk.
type Web3DepositWalletCreateBulk struct {
	config
	err      error
	builders []*Web3DepositWalletCreate
	conflict []sql.ConflictOption
}

// Save creates the Web3DepositWallet entities in the database.
func (_c *Web3DepositWalletCreateBulk) Save(ctx context.Context) ([]*Web3DepositWallet, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Web3DepositWallet, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*Web3DepositWalletMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *Web3DepositWalletCreateBulk) SaveX(ctx context.Context) []*Web3DepositWallet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *Web3DepositWalletCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *Web3DepositWalletCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Web3DepositWallet.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.Web3DepositWalletUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *Web3DepositWalletCreateBulk) OnConflict(opts ...sql.ConflictOption) *Web3DepositWalletUpsertBulk {
	_c.conflict = opts
	return &Web3DepositWalletUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Web3DepositWallet.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *Web3DepositWalletCreateBulk) OnConflictColumns(columns ...string) *Web3DepositWalletUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &Web3DepositWalletUpsertBulk{
		create: _c,
	}
}

// Web3DepositWalletUpsertBulk is the builder for "upsert"-ing
// a bulk of Web3DepositWallet nodes.
type Web3DepositWalletUpsertBulk struct {
	create *Web3DepositWalletCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Web3DepositWallet.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(web3depositwallet.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *Web3DepositWalletUpsertBulk) UpdateNewValues() *Web3DepositWalletUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(web3depositwallet.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(web3depositwallet.FieldCreatedAt)
			}
			if _, exists := b.mutation.WalletID(); exists {
				s.SetIgnore(web3depositwallet.FieldWalletID)
			}
			if _, exists := b.mutation.AccountPath(); exists {
				s.SetIgnore(web3depositwallet.FieldAccountPath)
			}
			if _, exists := b.mutation.XpubFingerprint(); exists {
				s.SetIgnore(web3depositwallet.FieldXpubFingerprint)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Web3DepositWallet.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *Web3DepositWalletUpsertBulk) Ignore() *Web3DepositWalletUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *Web3DepositWalletUpsertBulk) DoNothing() *Web3DepositWalletUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the Web3DepositWalletCreateBulk.OnConflict
// documentation for more info.
func (u *Web3DepositWalletUpsertBulk) Update(set func(*Web3DepositWalletUpsert)) *Web3DepositWalletUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&Web3DepositWalletUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *Web3DepositWalletUpsertBulk) SetUpdatedAt(v time.Time) *Web3DepositWalletUpsertBulk {
	return u.Update(func(s *Web3DepositWalletUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *Web3DepositWalletUpsertBulk) UpdateUpdatedAt() *Web3DepositWalletUpsertBulk {
	return u.Update(func(s *Web3DepositWalletUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetNextDerivationIndex sets the "next_derivation_index" field.
func (u *Web3DepositWalletUpsertBulk) SetNextDerivationIndex(v int64) *Web3DepositWalletUpsertBulk {
	return u.Update(func(s *Web3DepositWalletUpsert) {
		s.SetNextDerivationIndex(v)
	})
}

// AddNextDerivationIndex adds v to the "next_derivation_index" field.
func (u *Web3DepositWalletUpsertBulk) AddNextDerivationIndex(v int64) *Web3DepositWalletUpsertBulk {
	return u.Update(func(s *Web3DepositWalletUpsert) {
		s.AddNextDerivationIndex(v)
	})
}

// UpdateNextDerivationIndex sets the "next_derivation_index" field to the value that was provided on create.
func (u *Web3DepositWalletUpsertBulk) UpdateNextDerivationIndex() *Web3DepositWalletUpsertBulk {
	return u.Update(func(s *Web3DepositWalletUpsert) {
		s.UpdateNextDerivationIndex()
	})
}

// SetStatus sets the "status" field.
func (u *Web3DepositWalletUpsertBulk) SetStatus(v string) *Web3DepositWalletUpsertBulk {
	return u.Update(func(s *Web3DepositWalletUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *Web3DepositWalletUpsertBulk) UpdateStatus() *Web3DepositWalletUpsertBulk {
	return u.Update(func(s *Web3DepositWalletUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *Web3DepositWalletUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the Web3DepositWalletCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for Web3DepositWalletCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *Web3DepositWalletUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
