// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/web3balancetransfer"
)

// Web3BalanceTransferCreate is the builder for creating a Web3BalanceTransfer entity.
type Web3BalanceTransferCreate struct {
	config
	mutation *Web3BalanceTransferMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *Web3BalanceTransferCreate) SetUserID(v int64) *Web3BalanceTransferCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetWeb3BalanceID sets the "web3_balance_id" field.
func (_c *Web3BalanceTransferCreate) SetWeb3BalanceID(v int64) *Web3BalanceTransferCreate {
	_c.mutation.SetWeb3BalanceID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *Web3BalanceTransferCreate) SetAmount(v string) *Web3BalanceTransferCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetWeb3BalanceBefore sets the "web3_balance_before" field.
func (_c *Web3BalanceTransferCreate) SetWeb3BalanceBefore(v string) *Web3BalanceTransferCreate {
	_c.mutation.SetWeb3BalanceBefore(v)
	return _c
}

// SetWeb3BalanceAfter sets the "web3_balance_after" field.
func (_c *Web3BalanceTransferCreate) SetWeb3BalanceAfter(v string) *Web3BalanceTransferCreate {
	_c.mutation.SetWeb3BalanceAfter(v)
	return _c
}

// SetUserBalanceBefore sets the "user_balance_before" field.
func (_c *Web3BalanceTransferCreate) SetUserBalanceBefore(v string) *Web3BalanceTransferCreate {
	_c.mutation.SetUserBalanceBefore(v)
	return _c
}

// SetUserBalanceAfter sets the "user_balance_after" field.
func (_c *Web3BalanceTransferCreate) SetUserBalanceAfter(v string) *Web3BalanceTransferCreate {
	_c.mutation.SetUserBalanceAfter(v)
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *Web3BalanceTransferCreate) SetIdempotencyKey(v string) *Web3BalanceTransferCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *Web3BalanceTransferCreate) SetMetadata(v map[string]interface{}) *Web3BalanceTransferCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *Web3BalanceTransferCreate) SetCreatedAt(v time.Time) *Web3BalanceTransferCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *Web3BalanceTransferCreate) SetNillableCreatedAt(v *time.Time) *Web3BalanceTransferCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *Web3BalanceTransferCreate) SetID(v int64) *Web3BalanceTransferCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the Web3BalanceTransferMutation object of the builder.
func (_c *Web3BalanceTransferCreate) Mutation() *Web3BalanceTransferMutation {
	return _c.mutation
}

// Save creates the Web3BalanceTransfer in the database.
func (_c *Web3BalanceTransferCreate) Save(ctx context.Context) (*Web3BalanceTransfer, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *Web3BalanceTransferCreate) SaveX(ctx context.Context) *Web3BalanceTransfer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *Web3BalanceTransferCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *Web3BalanceTransferCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *Web3BalanceTransferCreate) defaults() {
	if _, ok := _c.mutation.Metadata(); !ok {
		v := web3balancetransfer.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := web3balancetransfer.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *Web3BalanceTransferCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Web3BalanceTransfer.user_id"`)}
	}
	if _, ok := _c.mutation.Web3BalanceID(); !ok {
		return &ValidationError{Name: "web3_balance_id", err: errors.New(`ent: missing required field "Web3BalanceTransfer.web3_balance_id"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Web3BalanceTransfer.amount"`)}
	}
	if v, ok := _c.mutation.Amount(); ok {
		if err := web3balancetransfer.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "Web3BalanceTransfer.amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Web3BalanceBefore(); !ok {
		return &ValidationError{Name: "web3_balance_before", err: errors.New(`ent: missing required field "Web3BalanceTransfer.web3_balance_before"`)}
	}
	if v, ok := _c.mutation.Web3BalanceBefore(); ok {
		if err := web3balancetransfer.Web3BalanceBeforeValidator(v); err != nil {
			return &ValidationError{Name: "web3_balance_before", err: fmt.Errorf(`ent: validator failed for field "Web3BalanceTransfer.web3_balance_before": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Web3BalanceAfter(); !ok {
		return &ValidationError{Name: "web3_balance_after", err: errors.New(`ent: missing required field "Web3BalanceTransfer.web3_balance_after"`)}
	}
	if v, ok := _c.mutation.Web3BalanceAfter(); ok {
		if err := web3balancetransfer.Web3BalanceAfterValidator(v); err != nil {
			return &ValidationError{Name: "web3_balance_after", err: fmt.Errorf(`ent: validator failed for field "Web3BalanceTransfer.web3_balance_after": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserBalanceBefore(); !ok {
		return &ValidationError{Name: "user_balance_before", err: errors.New(`ent: missing required field "Web3BalanceTransfer.user_balance_before"`)}
	}
	if v, ok := _c.mutation.UserBalanceBefore(); ok {
		if err := web3balancetransfer.UserBalanceBeforeValidator(v); err != nil {
			return &ValidationError{Name: "user_balance_before", err: fmt.Errorf(`ent: validator failed for field "Web3BalanceTransfer.user_balance_before": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserBalanceAfter(); !ok {
		return &ValidationError{Name: "user_balance_after", err: errors.New(`ent: missing required field "Web3BalanceTransfer.user_balance_after"`)}
	}
	if v, ok := _c.mutation.UserBalanceAfter(); ok {
		if err := web3balancetransfer.UserBalanceAfterValidator(v); err != nil {
			return &ValidationError{Name: "user_balance_after", err: fmt.Errorf(`ent: validator failed for field "Web3BalanceTransfer.user_balance_after": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "Web3BalanceTransfer.idempotency_key"`)}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := web3balancetransfer.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "Web3BalanceTransfer.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "Web3BalanceTransfer.metadata"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Web3BalanceTransfer.created_at"`)}
	}
	return nil
}

func (_c *Web3BalanceTransferCreate) sqlSave(ctx context.Context) (*Web3BalanceTransfer, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *Web3BalanceTransferCreate) createSpec() (*Web3BalanceTransfer, *sqlgraph.CreateSpec) {
	var (
		_node = &Web3BalanceTransfer{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(web3balancetransfer.Table, sqlgraph.NewFieldSpec(web3balancetransfer.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(web3balancetransfer.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Web3BalanceID(); ok {
		_spec.SetField(web3balancetransfer.FieldWeb3BalanceID, field.TypeInt64, value)
		_node.Web3BalanceID = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(web3balancetransfer.FieldAmount, field.TypeString, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Web3BalanceBefore(); ok {
		_spec.SetField(web3balancetransfer.FieldWeb3BalanceBefore, field.TypeString, value)
		_node.Web3BalanceBefore = value
	}
	if value, ok := _c.mutation.Web3BalanceAfter(); ok {
		_spec.SetField(web3balancetransfer.FieldWeb3BalanceAfter, field.TypeString, value)
		_node.Web3BalanceAfter = value
	}
	if value, ok := _c.mutation.UserBalanceBefore(); ok {
		_spec.SetField(web3balancetransfer.FieldUserBalanceBefore, field.TypeString, value)
		_node.UserBalanceBefore = value
	}
	if value, ok := _c.mutation.UserBalanceAfter(); ok {
		_spec.SetField(web3balancetransfer.FieldUserBalanceAfter, field.TypeString, value)
		_node.UserBalanceAfter = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(web3balancetransfer.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(web3balancetransfer.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(web3balancetransfer.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Web3BalanceTransfer.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.Web3BalanceTransferUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *Web3BalanceTransferCreate) OnConflict(opts ...sql.ConflictOption) *Web3BalanceTransferUpsertOne {
	_c.conflict = opts
	return &Web3BalanceTransferUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Web3BalanceTransfer.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *Web3BalanceTransferCreate) OnConflictColumns(columns ...string) *Web3BalanceTransferUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &Web3BalanceTransferUpsertOne{
		create: _c,
	}
}

type (
	// Web3BalanceTransferUpsertOne is the builder for "upsert"-ing
	//  one Web3BalanceTransfer node.
	Web3BalanceTransferUpsertOne struct {
		create *Web3BalanceTransferCreate
	}

	// Web3BalanceTransferUpsert is the "OnConflict" setter.
	Web3BalanceTransferUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Web3BalanceTransfer.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(web3balancetransfer.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *Web3BalanceTransferUpsertOne) UpdateNewValues() *Web3BalanceTransferUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(web3balancetransfer.FieldID)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(web3balancetransfer.FieldUserID)
		}
		if _, exists := u.create.mutation.Web3BalanceID(); exists {
			s.SetIgnore(web3balancetransfer.FieldWeb3BalanceID)
		}
		if _, exists := u.create.mutation.Amount(); exists {
			s.SetIgnore(web3balancetransfer.FieldAmount)
		}
		if _, exists := u.create.mutation.Web3BalanceBefore(); exists {
			s.SetIgnore(web3balancetransfer.FieldWeb3BalanceBefore)
		}
		if _, exists := u.create.mutation.Web3BalanceAfter(); exists {
			s.SetIgnore(web3balancetransfer.FieldWeb3BalanceAfter)
		}
		if _, exists := u.create.mutation.UserBalanceBefore(); exists {
			s.SetIgnore(web3balancetransfer.FieldUserBalanceBefore)
		}
		if _, exists := u.create.mutation.UserBalanceAfter(); exists {
			s.SetIgnore(web3balancetransfer.FieldUserBalanceAfter)
		}
		if _, exists := u.create.mutation.IdempotencyKey(); exists {
			s.SetIgnore(web3balancetransfer.FieldIdempotencyKey)
		}
		if _, exists := u.create.mutation.Metadata(); exists {
			s.SetIgnore(web3balancetransfer.FieldMetadata)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(web3balancetransfer.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Web3BalanceTransfer.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *Web3BalanceTransferUpsertOne) Ignore() *Web3BalanceTransferUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *Web3BalanceTransferUpsertOne) DoNothing() *Web3BalanceTransferUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the Web3BalanceTransferCreate.OnConflict
// documentation for more info.
func (u *Web3BalanceTransferUpsertOne) Update(set func(*Web3BalanceTransferUpsert)) *Web3BalanceTransferUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&Web3BalanceTransferUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *Web3BalanceTransferUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for Web3BalanceTransferCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *Web3BalanceTransferUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *Web3BalanceTransferUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *Web3BalanceTransferUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// Web3BalanceTransferCreateBulk is the builder for creating many Web3BalanceTransfer entities in bulk.
type Web3BalanceTransferCreateBulk struct {
	config
	err      error
	builders []*Web3BalanceTransferCreate
	conflict []sql.ConflictOption
}

// Save creates the Web3BalanceTransfer entities in the database.
func (_c *Web3BalanceTransferCreateBulk) Save(ctx context.Context) ([]*Web3BalanceTransfer, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Web3BalanceTransfer, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*Web3BalanceTransferMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *Web3BalanceTransferCreateBulk) SaveX(ctx context.Context) []*Web3BalanceTransfer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *Web3BalanceTransferCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *Web3BalanceTransferCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Web3BalanceTransfer.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.Web3BalanceTransferUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *Web3BalanceTransferCreateBulk) OnConflict(opts ...sql.ConflictOption) *Web3BalanceTransferUpsertBulk {
	_c.conflict = opts
	return &Web3BalanceTransferUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Web3BalanceTransfer.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *Web3BalanceTransferCreateBulk) OnConflictColumns(columns ...string) *Web3BalanceTransferUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &Web3BalanceTransferUpsertBulk{
		create: _c,
	}
}

// Web3BalanceTransferUpsertBulk is the builder for "upsert"-ing
// a bulk of Web3BalanceTransfer nodes.
type Web3BalanceTransferUpsertBulk struct {
	create *Web3BalanceTransferCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Web3BalanceTransfer.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(web3balancetransfer.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *Web3BalanceTransferUpsertBulk) UpdateNewValues() *Web3BalanceTransferUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(web3balancetransfer.FieldID)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(web3balancetransfer.FieldUserID)
			}
			if _, exists := b.mutation.Web3BalanceID(); exists {
				s.SetIgnore(web3balancetransfer.FieldWeb3BalanceID)
			}
			if _, exists := b.mutation.Amount(); exists {
				s.SetIgnore(web3balancetransfer.FieldAmount)
			}
			if _, exists := b.mutation.Web3BalanceBefore(); exists {
				s.SetIgnore(web3balancetransfer.FieldWeb3BalanceBefore)
			}
			if _, exists := b.mutation.Web3BalanceAfter(); exists {
				s.SetIgnore(web3balancetransfer.FieldWeb3BalanceAfter)
			}
			if _, exists := b.mutation.UserBalanceBefore(); exists {
				s.SetIgnore(web3balancetransfer.FieldUserBalanceBefore)
			}
			if _, exists := b.mutation.UserBalanceAfter(); exists {
				s.SetIgnore(web3balancetransfer.FieldUserBalanceAfter)
			}
			if _, exists := b.mutation.IdempotencyKey(); exists {
				s.SetIgnore(web3balancetransfer.FieldIdempotencyKey)
			}
			if _, exists := b.mutation.Metadata(); exists {
				s.SetIgnore(web3balancetransfer.FieldMetadata)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(web3balancetransfer.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Web3BalanceTransfer.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *Web3BalanceTransferUpsertBulk) Ignore() *Web3BalanceTransferUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *Web3BalanceTransferUpsertBulk) DoNothing() *Web3BalanceTransferUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the Web3BalanceTransferCreateBulk.OnConflict
// documentation for more info.
func (u *Web3BalanceTransferUpsertBulk) Update(set func(*Web3BalanceTransferUpsert)) *Web3BalanceTransferUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&Web3BalanceTransferUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *Web3BalanceTransferUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the Web3BalanceTransferCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for Web3BalanceTransferCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *Web3BalanceTransferUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
