// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/web3deposit"
)

// Web3DepositUpdate is the builder for updating Web3Deposit entities.
type Web3DepositUpdate struct {
	config
	hooks    []Hook
	mutation *Web3DepositMutation
}

// Where appends a list predicates to the Web3DepositUpdate builder.
func (_u *Web3DepositUpdate) Where(ps ...predicate.Web3Deposit) *Web3DepositUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *Web3DepositUpdate) SetUpdatedAt(v time.Time) *Web3DepositUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreditedAmount sets the "credited_amount" field.
func (_u *Web3DepositUpdate) SetCreditedAmount(v string) *Web3DepositUpdate {
	_u.mutation.SetCreditedAmount(v)
	return _u
}

// SetNillableCreditedAmount sets the "credited_amount" field if the given value is not nil.
func (_u *Web3DepositUpdate) SetNillableCreditedAmount(v *string) *Web3DepositUpdate {
	if v != nil {
		_u.SetCreditedAmount(*v)
	}
	return _u
}

// ClearCreditedAmount clears the value of the "credited_amount" field.
func (_u *Web3DepositUpdate) ClearCreditedAmount() *Web3DepositUpdate {
	_u.mutation.ClearCreditedAmount()
	return _u
}

// SetStatus sets the "status" field.
func (_u *Web3DepositUpdate) SetStatus(v string) *Web3DepositUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *Web3DepositUpdate) SetNillableStatus(v *string) *Web3DepositUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReviewReason sets the "review_reason" field.
func (_u *Web3DepositUpdate) SetReviewReason(v string) *Web3DepositUpdate {
	_u.mutation.SetReviewReason(v)
	return _u
}

// SetNillableReviewReason sets the "review_reason" field if the given value is not nil.
func (_u *Web3DepositUpdate) SetNillableReviewReason(v *string) *Web3DepositUpdate {
	if v != nil {
		_u.SetReviewReason(*v)
	}
	return _u
}

// ClearReviewReason clears the value of the "review_reason" field.
func (_u *Web3DepositUpdate) ClearReviewReason() *Web3DepositUpdate {
	_u.mutation.ClearReviewReason()
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *Web3DepositUpdate) SetFailureReason(v string) *Web3DepositUpdate {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *Web3DepositUpdate) SetNillableFailureReason(v *string) *Web3DepositUpdate {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *Web3DepositUpdate) ClearFailureReason() *Web3DepositUpdate {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *Web3DepositUpdate) SetRetryCount(v int32) *Web3DepositUpdate {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *Web3DepositUpdate) SetNillableRetryCount(v *int32) *Web3DepositUpdate {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *Web3DepositUpdate) AddRetryCount(v int32) *Web3DepositUpdate {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetNextRetryAt sets the "next_retry_at" field.
func (_u *Web3DepositUpdate) SetNextRetryAt(v time.Time) *Web3DepositUpdate {
	_u.mutation.SetNextRetryAt(v)
	return _u
}

// SetNillableNextRetryAt sets the "next_retry_at" field if the given value is not nil.
func (_u *Web3DepositUpdate) SetNillableNextRetryAt(v *time.Time) *Web3DepositUpdate {
	if v != nil {
		_u.SetNextRetryAt(*v)
	}
	return _u
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (_u *Web3DepositUpdate) ClearNextRetryAt() *Web3DepositUpdate {
	_u.mutation.ClearNextRetryAt()
	return _u
}

// SetFinalizedAt sets the "finalized_at" field.
func (_u *Web3DepositUpdate) SetFinalizedAt(v time.Time) *Web3DepositUpdate {
	_u.mutation.SetFinalizedAt(v)
	return _u
}

// SetNillableFinalizedAt sets the "finalized_at" field if the given value is not nil.
func (_u *Web3DepositUpdate) SetNillableFinalizedAt(v *time.Time) *Web3DepositUpdate {
	if v != nil {
		_u.SetFinalizedAt(*v)
	}
	return _u
}

// ClearFinalizedAt clears the value of the "finalized_at" field.
func (_u *Web3DepositUpdate) ClearFinalizedAt() *Web3DepositUpdate {
	_u.mutation.ClearFinalizedAt()
	return _u
}

// SetCreditedAt sets the "credited_at" field.
func (_u *Web3DepositUpdate) SetCreditedAt(v time.Time) *Web3DepositUpdate {
	_u.mutation.SetCreditedAt(v)
	return _u
}

// SetNillableCreditedAt sets the "credited_at" field if the given value is not nil.
func (_u *Web3DepositUpdate) SetNillableCreditedAt(v *time.Time) *Web3DepositUpdate {
	if v != nil {
		_u.SetCreditedAt(*v)
	}
	return _u
}

// ClearCreditedAt clears the value of the "credited_at" field.
func (_u *Web3DepositUpdate) ClearCreditedAt() *Web3DepositUpdate {
	_u.mutation.ClearCreditedAt()
	return _u
}

// Mutation returns the Web3DepositMutation object of the builder.
func (_u *Web3DepositUpdate) Mutation() *Web3DepositMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *Web3DepositUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *Web3DepositUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *Web3DepositUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *Web3DepositUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *Web3DepositUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := web3deposit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *Web3DepositUpdate) check() error {
	if v, ok := _u.mutation.CreditedAmount(); ok {
		if err := web3deposit.CreditedAmountValidator(v); err != nil {
			return &ValidationError{Name: "credited_amount", err: fmt.Errorf(`ent: validator failed for field "Web3Deposit.credited_amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := web3deposit.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Web3Deposit.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RetryCount(); ok {
		if err := web3deposit.RetryCountValidator(v); err != nil {
			return &ValidationError{Name: "retry_count", err: fmt.Errorf(`ent: validator failed for field "Web3Deposit.retry_count": %w`, err)}
		}
	}
	return nil
}

func (_u *Web3DepositUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(web3deposit.Table, web3deposit.Columns, sqlgraph.NewFieldSpec(web3deposit.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(web3deposit.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreditedAmount(); ok {
		_spec.SetField(web3deposit.FieldCreditedAmount, field.TypeString, value)
	}
	if _u.mutation.CreditedAmountCleared() {
		_spec.ClearField(web3deposit.FieldCreditedAmount, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(web3deposit.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReviewReason(); ok {
		_spec.SetField(web3deposit.FieldReviewReason, field.TypeString, value)
	}
	if _u.mutation.ReviewReasonCleared() {
		_spec.ClearField(web3deposit.FieldReviewReason, field.TypeString)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(web3deposit.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(web3deposit.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(web3deposit.FieldRetryCount, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(web3deposit.FieldRetryCount, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.NextRetryAt(); ok {
		_spec.SetField(web3deposit.FieldNextRetryAt, field.TypeTime, value)
	}
	if _u.mutation.NextRetryAtCleared() {
		_spec.ClearField(web3deposit.FieldNextRetryAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinalizedAt(); ok {
		_spec.SetField(web3deposit.FieldFinalizedAt, field.TypeTime, value)
	}
	if _u.mutation.FinalizedAtCleared() {
		_spec.ClearField(web3deposit.FieldFinalizedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreditedAt(); ok {
		_spec.SetField(web3deposit.FieldCreditedAt, field.TypeTime, value)
	}
	if _u.mutation.CreditedAtCleared() {
		_spec.ClearField(web3deposit.FieldCreditedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{web3deposit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// Web3DepositUpdateOne is the builder for updating a single Web3Deposit entity.
type Web3DepositUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *Web3DepositMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *Web3DepositUpdateOne) SetUpdatedAt(v time.Time) *Web3DepositUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreditedAmount sets the "credited_amount" field.
func (_u *Web3DepositUpdateOne) SetCreditedAmount(v string) *Web3DepositUpdateOne {
	_u.mutation.SetCreditedAmount(v)
	return _u
}

// SetNillableCreditedAmount sets the "credited_amount" field if the given value is not nil.
func (_u *Web3DepositUpdateOne) SetNillableCreditedAmount(v *string) *Web3DepositUpdateOne {
	if v != nil {
		_u.SetCreditedAmount(*v)
	}
	return _u
}

// ClearCreditedAmount clears the value of the "credited_amount" field.
func (_u *Web3DepositUpdateOne) ClearCreditedAmount() *Web3DepositUpdateOne {
	_u.mutation.ClearCreditedAmount()
	return _u
}

// SetStatus sets the "status" field.
func (_u *Web3DepositUpdateOne) SetStatus(v string) *Web3DepositUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *Web3DepositUpdateOne) SetNillableStatus(v *string) *Web3DepositUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReviewReason sets the "review_reason" field.
func (_u *Web3DepositUpdateOne) SetReviewReason(v string) *Web3DepositUpdateOne {
	_u.mutation.SetReviewReason(v)
	return _u
}

// SetNillableReviewReason sets the "review_reason" field if the given value is not nil.
func (_u *Web3DepositUpdateOne) SetNillableReviewReason(v *string) *Web3DepositUpdateOne {
	if v != nil {
		_u.SetReviewReason(*v)
	}
	return _u
}

// ClearReviewReason clears the value of the "review_reason" field.
func (_u *Web3DepositUpdateOne) ClearReviewReason() *Web3DepositUpdateOne {
	_u.mutation.ClearReviewReason()
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *Web3DepositUpdateOne) SetFailureReason(v string) *Web3DepositUpdateOne {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *Web3DepositUpdateOne) SetNillableFailureReason(v *string) *Web3DepositUpdateOne {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *Web3DepositUpdateOne) ClearFailureReason() *Web3DepositUpdateOne {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *Web3DepositUpdateOne) SetRetryCount(v int32) *Web3DepositUpdateOne {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *Web3DepositUpdateOne) SetNillableRetryCount(v *int32) *Web3DepositUpdateOne {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *Web3DepositUpdateOne) AddRetryCount(v int32) *Web3DepositUpdateOne {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetNextRetryAt sets the "next_retry_at" field.
func (_u *Web3DepositUpdateOne) SetNextRetryAt(v time.Time) *Web3DepositUpdateOne {
	_u.mutation.SetNextRetryAt(v)
	return _u
}

// SetNillableNextRetryAt sets the "next_retry_at" field if the given value is not nil.
func (_u *Web3DepositUpdateOne) SetNillableNextRetryAt(v *time.Time) *Web3DepositUpdateOne {
	if v != nil {
		_u.SetNextRetryAt(*v)
	}
	return _u
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (_u *Web3DepositUpdateOne) ClearNextRetryAt() *Web3DepositUpdateOne {
	_u.mutation.ClearNextRetryAt()
	return _u
}

// SetFinalizedAt sets the "finalized_at" field.
func (_u *Web3DepositUpdateOne) SetFinalizedAt(v time.Time) *Web3DepositUpdateOne {
	_u.mutation.SetFinalizedAt(v)
	return _u
}

// SetNillableFinalizedAt sets the "finalized_at" field if the given value is not nil.
func (_u *Web3DepositUpdateOne) SetNillableFinalizedAt(v *time.Time) *Web3DepositUpdateOne {
	if v != nil {
		_u.SetFinalizedAt(*v)
	}
	return _u
}

// ClearFinalizedAt clears the value of the "finalized_at" field.
func (_u *Web3DepositUpdateOne) ClearFinalizedAt() *Web3DepositUpdateOne {
	_u.mutation.ClearFinalizedAt()
	return _u
}

// SetCreditedAt sets the "credited_at" field.
func (_u *Web3DepositUpdateOne) SetCreditedAt(v time.Time) *Web3DepositUpdateOne {
	_u.mutation.SetCreditedAt(v)
	return _u
}

// SetNillableCreditedAt sets the "credited_at" field if the given value is not nil.
func (_u *Web3DepositUpdateOne) SetNillableCreditedAt(v *time.Time) *Web3DepositUpdateOne {
	if v != nil {
		_u.SetCreditedAt(*v)
	}
	return _u
}

// ClearCreditedAt clears the value of the "credited_at" field.
func (_u *Web3DepositUpdateOne) ClearCreditedAt() *Web3DepositUpdateOne {
	_u.mutation.ClearCreditedAt()
	return _u
}

// Mutation returns the Web3DepositMutation object of the builder.
func (_u *Web3DepositUpdateOne) Mutation() *Web3DepositMutation {
	return _u.mutation
}

// Where appends a list predicates to the Web3DepositUpdate builder.
func (_u *Web3DepositUpdateOne) Where(ps ...predicate.Web3Deposit) *Web3DepositUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *Web3DepositUpdateOne) Select(field string, fields ...string) *Web3DepositUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Web3Deposit entity.
func (_u *Web3DepositUpdateOne) Save(ctx context.Context) (*Web3Deposit, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *Web3DepositUpdateOne) SaveX(ctx context.Context) *Web3Deposit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *Web3DepositUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *Web3DepositUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *Web3DepositUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := web3deposit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *Web3DepositUpdateOne) check() error {
	if v, ok := _u.mutation.CreditedAmount(); ok {
		if err := web3deposit.CreditedAmountValidator(v); err != nil {
			return &ValidationError{Name: "credited_amount", err: fmt.Errorf(`ent: validator failed for field "Web3Deposit.credited_amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := web3deposit.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Web3Deposit.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RetryCount(); ok {
		if err := web3deposit.RetryCountValidator(v); err != nil {
			return &ValidationError{Name: "retry_count", err: fmt.Errorf(`ent: validator failed for field "Web3Deposit.retry_count": %w`, err)}
		}
	}
	return nil
}

func (_u *Web3DepositUpdateOne) sqlSave(ctx context.Context) (_node *Web3Deposit, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(web3deposit.Table, web3deposit.Columns, sqlgraph.NewFieldSpec(web3deposit.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Web3Deposit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, web3deposit.FieldID)
		for _, f := range fields {
			if !web3deposit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != web3deposit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(web3deposit.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreditedAmount(); ok {
		_spec.SetField(web3deposit.FieldCreditedAmount, field.TypeString, value)
	}
	if _u.mutation.CreditedAmountCleared() {
		_spec.ClearField(web3deposit.FieldCreditedAmount, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(web3deposit.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReviewReason(); ok {
		_spec.SetField(web3deposit.FieldReviewReason, field.TypeString, value)
	}
	if _u.mutation.ReviewReasonCleared() {
		_spec.ClearField(web3deposit.FieldReviewReason, field.TypeString)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(web3deposit.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(web3deposit.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(web3deposit.FieldRetryCount, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(web3deposit.FieldRetryCount, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.NextRetryAt(); ok {
		_spec.SetField(web3deposit.FieldNextRetryAt, field.TypeTime, value)
	}
	if _u.mutation.NextRetryAtCleared() {
		_spec.ClearField(web3deposit.FieldNextRetryAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinalizedAt(); ok {
		_spec.SetField(web3deposit.FieldFinalizedAt, field.TypeTime, value)
	}
	if _u.mutation.FinalizedAtCleared() {
		_spec.ClearField(web3deposit.FieldFinalizedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreditedAt(); ok {
		_spec.SetField(web3deposit.FieldCreditedAt, field.TypeTime, value)
	}
	if _u.mutation.CreditedAtCleared() {
		_spec.ClearField(web3deposit.FieldCreditedAt, field.TypeTime)
	}
	_node = &Web3Deposit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{web3deposit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
