// Code generated by ent, DO NOT EDIT.

package web3depositwallet

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the web3depositwallet type in the database.
	Label = "web3deposit_wallet"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldWalletID holds the string denoting the wallet_id field in the database.
	FieldWalletID = "wallet_id"
	// FieldAccountPath holds the string denoting the account_path field in the database.
	FieldAccountPath = "account_path"
	// FieldXpubFingerprint holds the string denoting the xpub_fingerprint field in the database.
	FieldXpubFingerprint = "xpub_fingerprint"
	// FieldNextDerivationIndex holds the string denoting the next_derivation_index field in the database.
	FieldNextDerivationIndex = "next_derivation_index"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// Table holds the table name of the web3depositwallet in the database.
	Table = "web3_deposit_wallets"
)

// Columns holds all SQL columns for web3depositwallet fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldWalletID,
	FieldAccountPath,
	FieldXpubFingerprint,
	FieldNextDerivationIndex,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// WalletIDValidator is a validator for the "wallet_id" field. It is called by the builders before save.
	WalletIDValidator func(string) error
	// AccountPathValidator is a validator for the "account_path" field. It is called by the builders before save.
	AccountPathValidator func(string) error
	// XpubFingerprintValidator is a validator for the "xpub_fingerprint" field. It is called by the builders before save.
	XpubFingerprintValidator func(string) error
	// DefaultNextDerivationIndex holds the default value on creation for the "next_derivation_index" field.
	DefaultNextDerivationIndex int64
	// NextDerivationIndexValidator is a validator for the "next_derivation_index" field. It is called by the builders before save.
	NextDerivationIndexValidator func(int64) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
)

// OrderOption defines the ordering options for the Web3DepositWallet queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByWalletID orders the results by the wallet_id field.
func ByWalletID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWalletID, opts...).ToFunc()
}

// ByAccountPath orders the results by the account_path field.
func ByAccountPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountPath, opts...).ToFunc()
}

// ByXpubFingerprint orders the results by the xpub_fingerprint field.
func ByXpubFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldXpubFingerprint, opts...).ToFunc()
}

// ByNextDerivationIndex orders the results by the next_derivation_index field.
func ByNextDerivationIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextDerivationIndex, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}
