// Code generated by ent, DO NOT EDIT.

package web3depositwallet

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldEQ(FieldUpdatedAt, v))
}

// WalletID applies equality check predicate on the "wallet_id" field. It's identical to WalletIDEQ.
func WalletID(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldEQ(FieldWalletID, v))
}

// AccountPath applies equality check predicate on the "account_path" field. It's identical to AccountPathEQ.
func AccountPath(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldEQ(FieldAccountPath, v))
}

// XpubFingerprint applies equality check predicate on the "xpub_fingerprint" field. It's identical to XpubFingerprintEQ.
func XpubFingerprint(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldEQ(FieldXpubFingerprint, v))
}

// NextDerivationIndex applies equality check predicate on the "next_derivation_index" field. It's identical to NextDerivationIndexEQ.
func NextDerivationIndex(v int64) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldEQ(FieldNextDerivationIndex, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldEQ(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldLTE(FieldUpdatedAt, v))
}

// WalletIDEQ applies the EQ predicate on the "wallet_id" field.
func WalletIDEQ(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldEQ(FieldWalletID, v))
}

// WalletIDNEQ applies the NEQ predicate on the "wallet_id" field.
func WalletIDNEQ(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldNEQ(FieldWalletID, v))
}

// WalletIDIn applies the In predicate on the "wallet_id" field.
func WalletIDIn(vs ...string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldIn(FieldWalletID, vs...))
}

// WalletIDNotIn applies the NotIn predicate on the "wallet_id" field.
func WalletIDNotIn(vs ...string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldNotIn(FieldWalletID, vs...))
}

// WalletIDGT applies the GT predicate on the "wallet_id" field.
func WalletIDGT(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldGT(FieldWalletID, v))
}

// WalletIDGTE applies the GTE predicate on the "wallet_id" field.
func WalletIDGTE(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldGTE(FieldWalletID, v))
}

// WalletIDLT applies the LT predicate on the "wallet_id" field.
func WalletIDLT(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldLT(FieldWalletID, v))
}

// WalletIDLTE applies the LTE predicate on the "wallet_id" field.
func WalletIDLTE(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldLTE(FieldWalletID, v))
}

// WalletIDContains applies the Contains predicate on the "wallet_id" field.
func WalletIDContains(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldContains(FieldWalletID, v))
}

// WalletIDHasPrefix applies the HasPrefix predicate on the "wallet_id" field.
func WalletIDHasPrefix(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldHasPrefix(FieldWalletID, v))
}

// WalletIDHasSuffix applies the HasSuffix predicate on the "wallet_id" field.
func WalletIDHasSuffix(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldHasSuffix(FieldWalletID, v))
}

// WalletIDEqualFold applies the EqualFold predicate on the "wallet_id" field.
func WalletIDEqualFold(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldEqualFold(FieldWalletID, v))
}

// WalletIDContainsFold applies the ContainsFold predicate on the "wallet_id" field.
func WalletIDContainsFold(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldContainsFold(FieldWalletID, v))
}

// AccountPathEQ applies the EQ predicate on the "account_path" field.
func AccountPathEQ(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldEQ(FieldAccountPath, v))
}

// AccountPathNEQ applies the NEQ predicate on the "account_path" field.
func AccountPathNEQ(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldNEQ(FieldAccountPath, v))
}

// AccountPathIn applies the In predicate on the "account_path" field.
func AccountPathIn(vs ...string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldIn(FieldAccountPath, vs...))
}

// AccountPathNotIn applies the NotIn predicate on the "account_path" field.
func AccountPathNotIn(vs ...string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldNotIn(FieldAccountPath, vs...))
}

// AccountPathGT applies the GT predicate on the "account_path" field.
func AccountPathGT(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldGT(FieldAccountPath, v))
}

// AccountPathGTE applies the GTE predicate on the "account_path" field.
func AccountPathGTE(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldGTE(FieldAccountPath, v))
}

// AccountPathLT applies the LT predicate on the "account_path" field.
func AccountPathLT(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldLT(FieldAccountPath, v))
}

// AccountPathLTE applies the LTE predicate on the "account_path" field.
func AccountPathLTE(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldLTE(FieldAccountPath, v))
}

// AccountPathContains applies the Contains predicate on the "account_path" field.
func AccountPathContains(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldContains(FieldAccountPath, v))
}

// AccountPathHasPrefix applies the HasPrefix predicate on the "account_path" field.
func AccountPathHasPrefix(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldHasPrefix(FieldAccountPath, v))
}

// AccountPathHasSuffix applies the HasSuffix predicate on the "account_path" field.
func AccountPathHasSuffix(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldHasSuffix(FieldAccountPath, v))
}

// AccountPathEqualFold applies the EqualFold predicate on the "account_path" field.
func AccountPathEqualFold(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldEqualFold(FieldAccountPath, v))
}

// AccountPathContainsFold applies the ContainsFold predicate on the "account_path" field.
func AccountPathContainsFold(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldContainsFold(FieldAccountPath, v))
}

// XpubFingerprintEQ applies the EQ predicate on the "xpub_fingerprint" field.
func XpubFingerprintEQ(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldEQ(FieldXpubFingerprint, v))
}

// XpubFingerprintNEQ applies the NEQ predicate on the "xpub_fingerprint" field.
func XpubFingerprintNEQ(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldNEQ(FieldXpubFingerprint, v))
}

// XpubFingerprintIn applies the In predicate on the "xpub_fingerprint" field.
func XpubFingerprintIn(vs ...string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldIn(FieldXpubFingerprint, vs...))
}

// XpubFingerprintNotIn applies the NotIn predicate on the "xpub_fingerprint" field.
func XpubFingerprintNotIn(vs ...string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldNotIn(FieldXpubFingerprint, vs...))
}

// XpubFingerprintGT applies the GT predicate on the "xpub_fingerprint" field.
func XpubFingerprintGT(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldGT(FieldXpubFingerprint, v))
}

// XpubFingerprintGTE applies the GTE predicate on the "xpub_fingerprint" field.
func XpubFingerprintGTE(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldGTE(FieldXpubFingerprint, v))
}

// XpubFingerprintLT applies the LT predicate on the "xpub_fingerprint" field.
func XpubFingerprintLT(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldLT(FieldXpubFingerprint, v))
}

// XpubFingerprintLTE applies the LTE predicate on the "xpub_fingerprint" field.
func XpubFingerprintLTE(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldLTE(FieldXpubFingerprint, v))
}

// XpubFingerprintContains applies the Contains predicate on the "xpub_fingerprint" field.
func XpubFingerprintContains(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldContains(FieldXpubFingerprint, v))
}

// XpubFingerprintHasPrefix applies the HasPrefix predicate on the "xpub_fingerprint" field.
func XpubFingerprintHasPrefix(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldHasPrefix(FieldXpubFingerprint, v))
}

// XpubFingerprintHasSuffix applies the HasSuffix predicate on the "xpub_fingerprint" field.
func XpubFingerprintHasSuffix(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldHasSuffix(FieldXpubFingerprint, v))
}

// XpubFingerprintEqualFold applies the EqualFold predicate on the "xpub_fingerprint" field.
func XpubFingerprintEqualFold(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldEqualFold(FieldXpubFingerprint, v))
}

// XpubFingerprintContainsFold applies the ContainsFold predicate on the "xpub_fingerprint" field.
func XpubFingerprintContainsFold(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldContainsFold(FieldXpubFingerprint, v))
}

// NextDerivationIndexEQ applies the EQ predicate on the "next_derivation_index" field.
func NextDerivationIndexEQ(v int64) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldEQ(FieldNextDerivationIndex, v))
}

// NextDerivationIndexNEQ applies the NEQ predicate on the "next_derivation_index" field.
func NextDerivationIndexNEQ(v int64) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldNEQ(FieldNextDerivationIndex, v))
}

// NextDerivationIndexIn applies the In predicate on the "next_derivation_index" field.
func NextDerivationIndexIn(vs ...int64) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldIn(FieldNextDerivationIndex, vs...))
}

// NextDerivationIndexNotIn applies the NotIn predicate on the "next_derivation_index" field.
func NextDerivationIndexNotIn(vs ...int64) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldNotIn(FieldNextDerivationIndex, vs...))
}

// NextDerivationIndexGT applies the GT predicate on the "next_derivation_index" field.
func NextDerivationIndexGT(v int64) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldGT(FieldNextDerivationIndex, v))
}

// NextDerivationIndexGTE applies the GTE predicate on the "next_derivation_index" field.
func NextDerivationIndexGTE(v int64) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldGTE(FieldNextDerivationIndex, v))
}

// NextDerivationIndexLT applies the LT predicate on the "next_derivation_index" field.
func NextDerivationIndexLT(v int64) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldLT(FieldNextDerivationIndex, v))
}

// NextDerivationIndexLTE applies the LTE predicate on the "next_derivation_index" field.
func NextDerivationIndexLTE(v int64) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldLTE(FieldNextDerivationIndex, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.FieldContainsFold(FieldStatus, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Web3DepositWallet) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Web3DepositWallet) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Web3DepositWallet) predicate.Web3DepositWallet {
	return predicate.Web3DepositWallet(sql.NotPredicates(p))
}
