// Code generated by ent, DO NOT EDIT.

package web3balancetransfer

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the web3balancetransfer type in the database.
	Label = "web3balance_transfer"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldWeb3BalanceID holds the string denoting the web3_balance_id field in the database.
	FieldWeb3BalanceID = "web3_balance_id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldWeb3BalanceBefore holds the string denoting the web3_balance_before field in the database.
	FieldWeb3BalanceBefore = "web3_balance_before"
	// FieldWeb3BalanceAfter holds the string denoting the web3_balance_after field in the database.
	FieldWeb3BalanceAfter = "web3_balance_after"
	// FieldUserBalanceBefore holds the string denoting the user_balance_before field in the database.
	FieldUserBalanceBefore = "user_balance_before"
	// FieldUserBalanceAfter holds the string denoting the user_balance_after field in the database.
	FieldUserBalanceAfter = "user_balance_after"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the web3balancetransfer in the database.
	Table = "web3_balance_transfers"
)

// Columns holds all SQL columns for web3balancetransfer fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldWeb3BalanceID,
	FieldAmount,
	FieldWeb3BalanceBefore,
	FieldWeb3BalanceAfter,
	FieldUserBalanceBefore,
	FieldUserBalanceAfter,
	FieldIdempotencyKey,
	FieldMetadata,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	AmountValidator func(string) error
	// Web3BalanceBeforeValidator is a validator for the "web3_balance_before" field. It is called by the builders before save.
	Web3BalanceBeforeValidator func(string) error
	// Web3BalanceAfterValidator is a validator for the "web3_balance_after" field. It is called by the builders before save.
	Web3BalanceAfterValidator func(string) error
	// UserBalanceBeforeValidator is a validator for the "user_balance_before" field. It is called by the builders before save.
	UserBalanceBeforeValidator func(string) error
	// UserBalanceAfterValidator is a validator for the "user_balance_after" field. It is called by the builders before save.
	UserBalanceAfterValidator func(string) error
	// IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	IdempotencyKeyValidator func(string) error
	// DefaultMetadata holds the default value on creation for the "metadata" field.
	DefaultMetadata map[string]interface{}
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the Web3BalanceTransfer queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByWeb3BalanceID orders the results by the web3_balance_id field.
func ByWeb3BalanceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeb3BalanceID, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByWeb3BalanceBefore orders the results by the web3_balance_before field.
func ByWeb3BalanceBefore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeb3BalanceBefore, opts...).ToFunc()
}

// ByWeb3BalanceAfter orders the results by the web3_balance_after field.
func ByWeb3BalanceAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeb3BalanceAfter, opts...).ToFunc()
}

// ByUserBalanceBefore orders the results by the user_balance_before field.
func ByUserBalanceBefore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserBalanceBefore, opts...).ToFunc()
}

// ByUserBalanceAfter orders the results by the user_balance_after field.
func ByUserBalanceAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserBalanceAfter, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
