// Code generated by ent, DO NOT EDIT.

package bee

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Bee {
	return predicate.Bee(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Bee {
	return predicate.Bee(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Bee {
	return predicate.Bee(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Bee {
	return predicate.Bee(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Bee {
	return predicate.Bee(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Bee {
	return predicate.Bee(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Bee {
	return predicate.Bee(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldDeletedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldUserID, v))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v uuid.UUID) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldDeviceID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldName, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldStatus, v))
}

// CredentialHash applies equality check predicate on the "credential_hash" field. It's identical to CredentialHashEQ.
func CredentialHash(v string) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldCredentialHash, v))
}

// CredentialCreatedAt applies equality check predicate on the "credential_created_at" field. It's identical to CredentialCreatedAtEQ.
func CredentialCreatedAt(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldCredentialCreatedAt, v))
}

// AppVersion applies equality check predicate on the "app_version" field. It's identical to AppVersionEQ.
func AppVersion(v string) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldAppVersion, v))
}

// LastConnectedAt applies equality check predicate on the "last_connected_at" field. It's identical to LastConnectedAtEQ.
func LastConnectedAt(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldLastConnectedAt, v))
}

// LastDisconnectedAt applies equality check predicate on the "last_disconnected_at" field. It's identical to LastDisconnectedAtEQ.
func LastDisconnectedAt(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldLastDisconnectedAt, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldLastSeenAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Bee {
	return predicate.Bee(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Bee {
	return predicate.Bee(sql.FieldNotNull(FieldDeletedAt))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.Bee {
	return predicate.Bee(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.Bee {
	return predicate.Bee(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.Bee {
	return predicate.Bee(sql.FieldNotIn(FieldUserID, vs...))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v uuid.UUID) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v uuid.UUID) predicate.Bee {
	return predicate.Bee(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...uuid.UUID) predicate.Bee {
	return predicate.Bee(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...uuid.UUID) predicate.Bee {
	return predicate.Bee(sql.FieldNotIn(FieldDeviceID, vs...))
}

// DeviceIDGT applies the GT predicate on the "device_id" field.
func DeviceIDGT(v uuid.UUID) predicate.Bee {
	return predicate.Bee(sql.FieldGT(FieldDeviceID, v))
}

// DeviceIDGTE applies the GTE predicate on the "device_id" field.
func DeviceIDGTE(v uuid.UUID) predicate.Bee {
	return predicate.Bee(sql.FieldGTE(FieldDeviceID, v))
}

// DeviceIDLT applies the LT predicate on the "device_id" field.
func DeviceIDLT(v uuid.UUID) predicate.Bee {
	return predicate.Bee(sql.FieldLT(FieldDeviceID, v))
}

// DeviceIDLTE applies the LTE predicate on the "device_id" field.
func DeviceIDLTE(v uuid.UUID) predicate.Bee {
	return predicate.Bee(sql.FieldLTE(FieldDeviceID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Bee {
	return predicate.Bee(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Bee {
	return predicate.Bee(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Bee {
	return predicate.Bee(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Bee {
	return predicate.Bee(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Bee {
	return predicate.Bee(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Bee {
	return predicate.Bee(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Bee {
	return predicate.Bee(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Bee {
	return predicate.Bee(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Bee {
	return predicate.Bee(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Bee {
	return predicate.Bee(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Bee {
	return predicate.Bee(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Bee {
	return predicate.Bee(sql.FieldContainsFold(FieldName, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Bee {
	return predicate.Bee(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Bee {
	return predicate.Bee(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Bee {
	return predicate.Bee(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Bee {
	return predicate.Bee(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Bee {
	return predicate.Bee(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Bee {
	return predicate.Bee(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Bee {
	return predicate.Bee(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Bee {
	return predicate.Bee(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Bee {
	return predicate.Bee(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Bee {
	return predicate.Bee(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Bee {
	return predicate.Bee(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Bee {
	return predicate.Bee(sql.FieldContainsFold(FieldStatus, v))
}

// CredentialHashEQ applies the EQ predicate on the "credential_hash" field.
func CredentialHashEQ(v string) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldCredentialHash, v))
}

// CredentialHashNEQ applies the NEQ predicate on the "credential_hash" field.
func CredentialHashNEQ(v string) predicate.Bee {
	return predicate.Bee(sql.FieldNEQ(FieldCredentialHash, v))
}

// CredentialHashIn applies the In predicate on the "credential_hash" field.
func CredentialHashIn(vs ...string) predicate.Bee {
	return predicate.Bee(sql.FieldIn(FieldCredentialHash, vs...))
}

// CredentialHashNotIn applies the NotIn predicate on the "credential_hash" field.
func CredentialHashNotIn(vs ...string) predicate.Bee {
	return predicate.Bee(sql.FieldNotIn(FieldCredentialHash, vs...))
}

// CredentialHashGT applies the GT predicate on the "credential_hash" field.
func CredentialHashGT(v string) predicate.Bee {
	return predicate.Bee(sql.FieldGT(FieldCredentialHash, v))
}

// CredentialHashGTE applies the GTE predicate on the "credential_hash" field.
func CredentialHashGTE(v string) predicate.Bee {
	return predicate.Bee(sql.FieldGTE(FieldCredentialHash, v))
}

// CredentialHashLT applies the LT predicate on the "credential_hash" field.
func CredentialHashLT(v string) predicate.Bee {
	return predicate.Bee(sql.FieldLT(FieldCredentialHash, v))
}

// CredentialHashLTE applies the LTE predicate on the "credential_hash" field.
func CredentialHashLTE(v string) predicate.Bee {
	return predicate.Bee(sql.FieldLTE(FieldCredentialHash, v))
}

// CredentialHashContains applies the Contains predicate on the "credential_hash" field.
func CredentialHashContains(v string) predicate.Bee {
	return predicate.Bee(sql.FieldContains(FieldCredentialHash, v))
}

// CredentialHashHasPrefix applies the HasPrefix predicate on the "credential_hash" field.
func CredentialHashHasPrefix(v string) predicate.Bee {
	return predicate.Bee(sql.FieldHasPrefix(FieldCredentialHash, v))
}

// CredentialHashHasSuffix applies the HasSuffix predicate on the "credential_hash" field.
func CredentialHashHasSuffix(v string) predicate.Bee {
	return predicate.Bee(sql.FieldHasSuffix(FieldCredentialHash, v))
}

// CredentialHashEqualFold applies the EqualFold predicate on the "credential_hash" field.
func CredentialHashEqualFold(v string) predicate.Bee {
	return predicate.Bee(sql.FieldEqualFold(FieldCredentialHash, v))
}

// CredentialHashContainsFold applies the ContainsFold predicate on the "credential_hash" field.
func CredentialHashContainsFold(v string) predicate.Bee {
	return predicate.Bee(sql.FieldContainsFold(FieldCredentialHash, v))
}

// CredentialCreatedAtEQ applies the EQ predicate on the "credential_created_at" field.
func CredentialCreatedAtEQ(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldCredentialCreatedAt, v))
}

// CredentialCreatedAtNEQ applies the NEQ predicate on the "credential_created_at" field.
func CredentialCreatedAtNEQ(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldNEQ(FieldCredentialCreatedAt, v))
}

// CredentialCreatedAtIn applies the In predicate on the "credential_created_at" field.
func CredentialCreatedAtIn(vs ...time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldIn(FieldCredentialCreatedAt, vs...))
}

// CredentialCreatedAtNotIn applies the NotIn predicate on the "credential_created_at" field.
func CredentialCreatedAtNotIn(vs ...time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldNotIn(FieldCredentialCreatedAt, vs...))
}

// CredentialCreatedAtGT applies the GT predicate on the "credential_created_at" field.
func CredentialCreatedAtGT(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldGT(FieldCredentialCreatedAt, v))
}

// CredentialCreatedAtGTE applies the GTE predicate on the "credential_created_at" field.
func CredentialCreatedAtGTE(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldGTE(FieldCredentialCreatedAt, v))
}

// CredentialCreatedAtLT applies the LT predicate on the "credential_created_at" field.
func CredentialCreatedAtLT(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldLT(FieldCredentialCreatedAt, v))
}

// CredentialCreatedAtLTE applies the LTE predicate on the "credential_created_at" field.
func CredentialCreatedAtLTE(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldLTE(FieldCredentialCreatedAt, v))
}

// AppVersionEQ applies the EQ predicate on the "app_version" field.
func AppVersionEQ(v string) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldAppVersion, v))
}

// AppVersionNEQ applies the NEQ predicate on the "app_version" field.
func AppVersionNEQ(v string) predicate.Bee {
	return predicate.Bee(sql.FieldNEQ(FieldAppVersion, v))
}

// AppVersionIn applies the In predicate on the "app_version" field.
func AppVersionIn(vs ...string) predicate.Bee {
	return predicate.Bee(sql.FieldIn(FieldAppVersion, vs...))
}

// AppVersionNotIn applies the NotIn predicate on the "app_version" field.
func AppVersionNotIn(vs ...string) predicate.Bee {
	return predicate.Bee(sql.FieldNotIn(FieldAppVersion, vs...))
}

// AppVersionGT applies the GT predicate on the "app_version" field.
func AppVersionGT(v string) predicate.Bee {
	return predicate.Bee(sql.FieldGT(FieldAppVersion, v))
}

// AppVersionGTE applies the GTE predicate on the "app_version" field.
func AppVersionGTE(v string) predicate.Bee {
	return predicate.Bee(sql.FieldGTE(FieldAppVersion, v))
}

// AppVersionLT applies the LT predicate on the "app_version" field.
func AppVersionLT(v string) predicate.Bee {
	return predicate.Bee(sql.FieldLT(FieldAppVersion, v))
}

// AppVersionLTE applies the LTE predicate on the "app_version" field.
func AppVersionLTE(v string) predicate.Bee {
	return predicate.Bee(sql.FieldLTE(FieldAppVersion, v))
}

// AppVersionContains applies the Contains predicate on the "app_version" field.
func AppVersionContains(v string) predicate.Bee {
	return predicate.Bee(sql.FieldContains(FieldAppVersion, v))
}

// AppVersionHasPrefix applies the HasPrefix predicate on the "app_version" field.
func AppVersionHasPrefix(v string) predicate.Bee {
	return predicate.Bee(sql.FieldHasPrefix(FieldAppVersion, v))
}

// AppVersionHasSuffix applies the HasSuffix predicate on the "app_version" field.
func AppVersionHasSuffix(v string) predicate.Bee {
	return predicate.Bee(sql.FieldHasSuffix(FieldAppVersion, v))
}

// AppVersionIsNil applies the IsNil predicate on the "app_version" field.
func AppVersionIsNil() predicate.Bee {
	return predicate.Bee(sql.FieldIsNull(FieldAppVersion))
}

// AppVersionNotNil applies the NotNil predicate on the "app_version" field.
func AppVersionNotNil() predicate.Bee {
	return predicate.Bee(sql.FieldNotNull(FieldAppVersion))
}

// AppVersionEqualFold applies the EqualFold predicate on the "app_version" field.
func AppVersionEqualFold(v string) predicate.Bee {
	return predicate.Bee(sql.FieldEqualFold(FieldAppVersion, v))
}

// AppVersionContainsFold applies the ContainsFold predicate on the "app_version" field.
func AppVersionContainsFold(v string) predicate.Bee {
	return predicate.Bee(sql.FieldContainsFold(FieldAppVersion, v))
}

// LastConnectedAtEQ applies the EQ predicate on the "last_connected_at" field.
func LastConnectedAtEQ(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldLastConnectedAt, v))
}

// LastConnectedAtNEQ applies the NEQ predicate on the "last_connected_at" field.
func LastConnectedAtNEQ(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldNEQ(FieldLastConnectedAt, v))
}

// LastConnectedAtIn applies the In predicate on the "last_connected_at" field.
func LastConnectedAtIn(vs ...time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldIn(FieldLastConnectedAt, vs...))
}

// LastConnectedAtNotIn applies the NotIn predicate on the "last_connected_at" field.
func LastConnectedAtNotIn(vs ...time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldNotIn(FieldLastConnectedAt, vs...))
}

// LastConnectedAtGT applies the GT predicate on the "last_connected_at" field.
func LastConnectedAtGT(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldGT(FieldLastConnectedAt, v))
}

// LastConnectedAtGTE applies the GTE predicate on the "last_connected_at" field.
func LastConnectedAtGTE(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldGTE(FieldLastConnectedAt, v))
}

// LastConnectedAtLT applies the LT predicate on the "last_connected_at" field.
func LastConnectedAtLT(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldLT(FieldLastConnectedAt, v))
}

// LastConnectedAtLTE applies the LTE predicate on the "last_connected_at" field.
func LastConnectedAtLTE(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldLTE(FieldLastConnectedAt, v))
}

// LastConnectedAtIsNil applies the IsNil predicate on the "last_connected_at" field.
func LastConnectedAtIsNil() predicate.Bee {
	return predicate.Bee(sql.FieldIsNull(FieldLastConnectedAt))
}

// LastConnectedAtNotNil applies the NotNil predicate on the "last_connected_at" field.
func LastConnectedAtNotNil() predicate.Bee {
	return predicate.Bee(sql.FieldNotNull(FieldLastConnectedAt))
}

// LastDisconnectedAtEQ applies the EQ predicate on the "last_disconnected_at" field.
func LastDisconnectedAtEQ(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldLastDisconnectedAt, v))
}

// LastDisconnectedAtNEQ applies the NEQ predicate on the "last_disconnected_at" field.
func LastDisconnectedAtNEQ(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldNEQ(FieldLastDisconnectedAt, v))
}

// LastDisconnectedAtIn applies the In predicate on the "last_disconnected_at" field.
func LastDisconnectedAtIn(vs ...time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldIn(FieldLastDisconnectedAt, vs...))
}

// LastDisconnectedAtNotIn applies the NotIn predicate on the "last_disconnected_at" field.
func LastDisconnectedAtNotIn(vs ...time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldNotIn(FieldLastDisconnectedAt, vs...))
}

// LastDisconnectedAtGT applies the GT predicate on the "last_disconnected_at" field.
func LastDisconnectedAtGT(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldGT(FieldLastDisconnectedAt, v))
}

// LastDisconnectedAtGTE applies the GTE predicate on the "last_disconnected_at" field.
func LastDisconnectedAtGTE(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldGTE(FieldLastDisconnectedAt, v))
}

// LastDisconnectedAtLT applies the LT predicate on the "last_disconnected_at" field.
func LastDisconnectedAtLT(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldLT(FieldLastDisconnectedAt, v))
}

// LastDisconnectedAtLTE applies the LTE predicate on the "last_disconnected_at" field.
func LastDisconnectedAtLTE(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldLTE(FieldLastDisconnectedAt, v))
}

// LastDisconnectedAtIsNil applies the IsNil predicate on the "last_disconnected_at" field.
func LastDisconnectedAtIsNil() predicate.Bee {
	return predicate.Bee(sql.FieldIsNull(FieldLastDisconnectedAt))
}

// LastDisconnectedAtNotNil applies the NotNil predicate on the "last_disconnected_at" field.
func LastDisconnectedAtNotNil() predicate.Bee {
	return predicate.Bee(sql.FieldNotNull(FieldLastDisconnectedAt))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.Bee {
	return predicate.Bee(sql.FieldLTE(FieldLastSeenAt, v))
}

// LastSeenAtIsNil applies the IsNil predicate on the "last_seen_at" field.
func LastSeenAtIsNil() predicate.Bee {
	return predicate.Bee(sql.FieldIsNull(FieldLastSeenAt))
}

// LastSeenAtNotNil applies the NotNil predicate on the "last_seen_at" field.
func LastSeenAtNotNil() predicate.Bee {
	return predicate.Bee(sql.FieldNotNull(FieldLastSeenAt))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Bee {
	return predicate.Bee(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Bee {
	return predicate.Bee(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPlatforms applies the HasEdge predicate on the "platforms" edge.
func HasPlatforms() predicate.Bee {
	return predicate.Bee(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PlatformsTable, PlatformsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlatformsWith applies the HasEdge predicate on the "platforms" edge with a given conditions (other predicates).
func HasPlatformsWith(preds ...predicate.BeePlatform) predicate.Bee {
	return predicate.Bee(func(s *sql.Selector) {
		step := newPlatformsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Bee) predicate.Bee {
	return predicate.Bee(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Bee) predicate.Bee {
	return predicate.Bee(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Bee) predicate.Bee {
	return predicate.Bee(sql.NotPredicates(p))
}
