// Code generated by ent, DO NOT EDIT.

package web3deposit

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldUserID, v))
}

// DepositAddressID applies equality check predicate on the "deposit_address_id" field. It's identical to DepositAddressIDEQ.
func DepositAddressID(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldDepositAddressID, v))
}

// ChainID applies equality check predicate on the "chain_id" field. It's identical to ChainIDEQ.
func ChainID(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldChainID, v))
}

// TokenContract applies equality check predicate on the "token_contract" field. It's identical to TokenContractEQ.
func TokenContract(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldTokenContract, v))
}

// TxHash applies equality check predicate on the "tx_hash" field. It's identical to TxHashEQ.
func TxHash(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldTxHash, v))
}

// LogIndex applies equality check predicate on the "log_index" field. It's identical to LogIndexEQ.
func LogIndex(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldLogIndex, v))
}

// BlockNumber applies equality check predicate on the "block_number" field. It's identical to BlockNumberEQ.
func BlockNumber(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldBlockNumber, v))
}

// BlockHash applies equality check predicate on the "block_hash" field. It's identical to BlockHashEQ.
func BlockHash(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldBlockHash, v))
}

// FromAddress applies equality check predicate on the "from_address" field. It's identical to FromAddressEQ.
func FromAddress(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldFromAddress, v))
}

// ToAddress applies equality check predicate on the "to_address" field. It's identical to ToAddressEQ.
func ToAddress(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldToAddress, v))
}

// RawAmount applies equality check predicate on the "raw_amount" field. It's identical to RawAmountEQ.
func RawAmount(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldRawAmount, v))
}

// TokenDecimals applies equality check predicate on the "token_decimals" field. It's identical to TokenDecimalsEQ.
func TokenDecimals(v int16) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldTokenDecimals, v))
}

// TokenAmount applies equality check predicate on the "token_amount" field. It's identical to TokenAmountEQ.
func TokenAmount(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldTokenAmount, v))
}

// CreditedAmount applies equality check predicate on the "credited_amount" field. It's identical to CreditedAmountEQ.
func CreditedAmount(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldCreditedAmount, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldStatus, v))
}

// ReviewReason applies equality check predicate on the "review_reason" field. It's identical to ReviewReasonEQ.
func ReviewReason(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldReviewReason, v))
}

// FailureReason applies equality check predicate on the "failure_reason" field. It's identical to FailureReasonEQ.
func FailureReason(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldFailureReason, v))
}

// RetryCount applies equality check predicate on the "retry_count" field. It's identical to RetryCountEQ.
func RetryCount(v int32) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldRetryCount, v))
}

// NextRetryAt applies equality check predicate on the "next_retry_at" field. It's identical to NextRetryAtEQ.
func NextRetryAt(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldNextRetryAt, v))
}

// DetectedAt applies equality check predicate on the "detected_at" field. It's identical to DetectedAtEQ.
func DetectedAt(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldDetectedAt, v))
}

// FinalizedAt applies equality check predicate on the "finalized_at" field. It's identical to FinalizedAtEQ.
func FinalizedAt(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldFinalizedAt, v))
}

// CreditedAt applies equality check predicate on the "credited_at" field. It's identical to CreditedAtEQ.
func CreditedAt(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldCreditedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLTE(FieldUserID, v))
}

// DepositAddressIDEQ applies the EQ predicate on the "deposit_address_id" field.
func DepositAddressIDEQ(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldDepositAddressID, v))
}

// DepositAddressIDNEQ applies the NEQ predicate on the "deposit_address_id" field.
func DepositAddressIDNEQ(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNEQ(FieldDepositAddressID, v))
}

// DepositAddressIDIn applies the In predicate on the "deposit_address_id" field.
func DepositAddressIDIn(vs ...int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIn(FieldDepositAddressID, vs...))
}

// DepositAddressIDNotIn applies the NotIn predicate on the "deposit_address_id" field.
func DepositAddressIDNotIn(vs ...int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotIn(FieldDepositAddressID, vs...))
}

// DepositAddressIDGT applies the GT predicate on the "deposit_address_id" field.
func DepositAddressIDGT(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGT(FieldDepositAddressID, v))
}

// DepositAddressIDGTE applies the GTE predicate on the "deposit_address_id" field.
func DepositAddressIDGTE(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGTE(FieldDepositAddressID, v))
}

// DepositAddressIDLT applies the LT predicate on the "deposit_address_id" field.
func DepositAddressIDLT(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLT(FieldDepositAddressID, v))
}

// DepositAddressIDLTE applies the LTE predicate on the "deposit_address_id" field.
func DepositAddressIDLTE(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLTE(FieldDepositAddressID, v))
}

// ChainIDEQ applies the EQ predicate on the "chain_id" field.
func ChainIDEQ(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldChainID, v))
}

// ChainIDNEQ applies the NEQ predicate on the "chain_id" field.
func ChainIDNEQ(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNEQ(FieldChainID, v))
}

// ChainIDIn applies the In predicate on the "chain_id" field.
func ChainIDIn(vs ...int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIn(FieldChainID, vs...))
}

// ChainIDNotIn applies the NotIn predicate on the "chain_id" field.
func ChainIDNotIn(vs ...int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotIn(FieldChainID, vs...))
}

// ChainIDGT applies the GT predicate on the "chain_id" field.
func ChainIDGT(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGT(FieldChainID, v))
}

// ChainIDGTE applies the GTE predicate on the "chain_id" field.
func ChainIDGTE(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGTE(FieldChainID, v))
}

// ChainIDLT applies the LT predicate on the "chain_id" field.
func ChainIDLT(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLT(FieldChainID, v))
}

// ChainIDLTE applies the LTE predicate on the "chain_id" field.
func ChainIDLTE(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLTE(FieldChainID, v))
}

// TokenContractEQ applies the EQ predicate on the "token_contract" field.
func TokenContractEQ(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldTokenContract, v))
}

// TokenContractNEQ applies the NEQ predicate on the "token_contract" field.
func TokenContractNEQ(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNEQ(FieldTokenContract, v))
}

// TokenContractIn applies the In predicate on the "token_contract" field.
func TokenContractIn(vs ...string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIn(FieldTokenContract, vs...))
}

// TokenContractNotIn applies the NotIn predicate on the "token_contract" field.
func TokenContractNotIn(vs ...string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotIn(FieldTokenContract, vs...))
}

// TokenContractGT applies the GT predicate on the "token_contract" field.
func TokenContractGT(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGT(FieldTokenContract, v))
}

// TokenContractGTE applies the GTE predicate on the "token_contract" field.
func TokenContractGTE(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGTE(FieldTokenContract, v))
}

// TokenContractLT applies the LT predicate on the "token_contract" field.
func TokenContractLT(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLT(FieldTokenContract, v))
}

// TokenContractLTE applies the LTE predicate on the "token_contract" field.
func TokenContractLTE(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLTE(FieldTokenContract, v))
}

// TokenContractContains applies the Contains predicate on the "token_contract" field.
func TokenContractContains(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldContains(FieldTokenContract, v))
}

// TokenContractHasPrefix applies the HasPrefix predicate on the "token_contract" field.
func TokenContractHasPrefix(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldHasPrefix(FieldTokenContract, v))
}

// TokenContractHasSuffix applies the HasSuffix predicate on the "token_contract" field.
func TokenContractHasSuffix(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldHasSuffix(FieldTokenContract, v))
}

// TokenContractEqualFold applies the EqualFold predicate on the "token_contract" field.
func TokenContractEqualFold(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEqualFold(FieldTokenContract, v))
}

// TokenContractContainsFold applies the ContainsFold predicate on the "token_contract" field.
func TokenContractContainsFold(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldContainsFold(FieldTokenContract, v))
}

// TxHashEQ applies the EQ predicate on the "tx_hash" field.
func TxHashEQ(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldTxHash, v))
}

// TxHashNEQ applies the NEQ predicate on the "tx_hash" field.
func TxHashNEQ(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNEQ(FieldTxHash, v))
}

// TxHashIn applies the In predicate on the "tx_hash" field.
func TxHashIn(vs ...string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIn(FieldTxHash, vs...))
}

// TxHashNotIn applies the NotIn predicate on the "tx_hash" field.
func TxHashNotIn(vs ...string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotIn(FieldTxHash, vs...))
}

// TxHashGT applies the GT predicate on the "tx_hash" field.
func TxHashGT(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGT(FieldTxHash, v))
}

// TxHashGTE applies the GTE predicate on the "tx_hash" field.
func TxHashGTE(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGTE(FieldTxHash, v))
}

// TxHashLT applies the LT predicate on the "tx_hash" field.
func TxHashLT(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLT(FieldTxHash, v))
}

// TxHashLTE applies the LTE predicate on the "tx_hash" field.
func TxHashLTE(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLTE(FieldTxHash, v))
}

// TxHashContains applies the Contains predicate on the "tx_hash" field.
func TxHashContains(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldContains(FieldTxHash, v))
}

// TxHashHasPrefix applies the HasPrefix predicate on the "tx_hash" field.
func TxHashHasPrefix(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldHasPrefix(FieldTxHash, v))
}

// TxHashHasSuffix applies the HasSuffix predicate on the "tx_hash" field.
func TxHashHasSuffix(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldHasSuffix(FieldTxHash, v))
}

// TxHashEqualFold applies the EqualFold predicate on the "tx_hash" field.
func TxHashEqualFold(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEqualFold(FieldTxHash, v))
}

// TxHashContainsFold applies the ContainsFold predicate on the "tx_hash" field.
func TxHashContainsFold(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldContainsFold(FieldTxHash, v))
}

// LogIndexEQ applies the EQ predicate on the "log_index" field.
func LogIndexEQ(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldLogIndex, v))
}

// LogIndexNEQ applies the NEQ predicate on the "log_index" field.
func LogIndexNEQ(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNEQ(FieldLogIndex, v))
}

// LogIndexIn applies the In predicate on the "log_index" field.
func LogIndexIn(vs ...int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIn(FieldLogIndex, vs...))
}

// LogIndexNotIn applies the NotIn predicate on the "log_index" field.
func LogIndexNotIn(vs ...int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotIn(FieldLogIndex, vs...))
}

// LogIndexGT applies the GT predicate on the "log_index" field.
func LogIndexGT(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGT(FieldLogIndex, v))
}

// LogIndexGTE applies the GTE predicate on the "log_index" field.
func LogIndexGTE(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGTE(FieldLogIndex, v))
}

// LogIndexLT applies the LT predicate on the "log_index" field.
func LogIndexLT(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLT(FieldLogIndex, v))
}

// LogIndexLTE applies the LTE predicate on the "log_index" field.
func LogIndexLTE(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLTE(FieldLogIndex, v))
}

// BlockNumberEQ applies the EQ predicate on the "block_number" field.
func BlockNumberEQ(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldBlockNumber, v))
}

// BlockNumberNEQ applies the NEQ predicate on the "block_number" field.
func BlockNumberNEQ(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNEQ(FieldBlockNumber, v))
}

// BlockNumberIn applies the In predicate on the "block_number" field.
func BlockNumberIn(vs ...int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIn(FieldBlockNumber, vs...))
}

// BlockNumberNotIn applies the NotIn predicate on the "block_number" field.
func BlockNumberNotIn(vs ...int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotIn(FieldBlockNumber, vs...))
}

// BlockNumberGT applies the GT predicate on the "block_number" field.
func BlockNumberGT(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGT(FieldBlockNumber, v))
}

// BlockNumberGTE applies the GTE predicate on the "block_number" field.
func BlockNumberGTE(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGTE(FieldBlockNumber, v))
}

// BlockNumberLT applies the LT predicate on the "block_number" field.
func BlockNumberLT(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLT(FieldBlockNumber, v))
}

// BlockNumberLTE applies the LTE predicate on the "block_number" field.
func BlockNumberLTE(v int64) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLTE(FieldBlockNumber, v))
}

// BlockHashEQ applies the EQ predicate on the "block_hash" field.
func BlockHashEQ(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldBlockHash, v))
}

// BlockHashNEQ applies the NEQ predicate on the "block_hash" field.
func BlockHashNEQ(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNEQ(FieldBlockHash, v))
}

// BlockHashIn applies the In predicate on the "block_hash" field.
func BlockHashIn(vs ...string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIn(FieldBlockHash, vs...))
}

// BlockHashNotIn applies the NotIn predicate on the "block_hash" field.
func BlockHashNotIn(vs ...string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotIn(FieldBlockHash, vs...))
}

// BlockHashGT applies the GT predicate on the "block_hash" field.
func BlockHashGT(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGT(FieldBlockHash, v))
}

// BlockHashGTE applies the GTE predicate on the "block_hash" field.
func BlockHashGTE(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGTE(FieldBlockHash, v))
}

// BlockHashLT applies the LT predicate on the "block_hash" field.
func BlockHashLT(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLT(FieldBlockHash, v))
}

// BlockHashLTE applies the LTE predicate on the "block_hash" field.
func BlockHashLTE(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLTE(FieldBlockHash, v))
}

// BlockHashContains applies the Contains predicate on the "block_hash" field.
func BlockHashContains(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldContains(FieldBlockHash, v))
}

// BlockHashHasPrefix applies the HasPrefix predicate on the "block_hash" field.
func BlockHashHasPrefix(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldHasPrefix(FieldBlockHash, v))
}

// BlockHashHasSuffix applies the HasSuffix predicate on the "block_hash" field.
func BlockHashHasSuffix(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldHasSuffix(FieldBlockHash, v))
}

// BlockHashEqualFold applies the EqualFold predicate on the "block_hash" field.
func BlockHashEqualFold(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEqualFold(FieldBlockHash, v))
}

// BlockHashContainsFold applies the ContainsFold predicate on the "block_hash" field.
func BlockHashContainsFold(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldContainsFold(FieldBlockHash, v))
}

// FromAddressEQ applies the EQ predicate on the "from_address" field.
func FromAddressEQ(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldFromAddress, v))
}

// FromAddressNEQ applies the NEQ predicate on the "from_address" field.
func FromAddressNEQ(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNEQ(FieldFromAddress, v))
}

// FromAddressIn applies the In predicate on the "from_address" field.
func FromAddressIn(vs ...string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIn(FieldFromAddress, vs...))
}

// FromAddressNotIn applies the NotIn predicate on the "from_address" field.
func FromAddressNotIn(vs ...string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotIn(FieldFromAddress, vs...))
}

// FromAddressGT applies the GT predicate on the "from_address" field.
func FromAddressGT(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGT(FieldFromAddress, v))
}

// FromAddressGTE applies the GTE predicate on the "from_address" field.
func FromAddressGTE(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGTE(FieldFromAddress, v))
}

// FromAddressLT applies the LT predicate on the "from_address" field.
func FromAddressLT(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLT(FieldFromAddress, v))
}

// FromAddressLTE applies the LTE predicate on the "from_address" field.
func FromAddressLTE(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLTE(FieldFromAddress, v))
}

// FromAddressContains applies the Contains predicate on the "from_address" field.
func FromAddressContains(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldContains(FieldFromAddress, v))
}

// FromAddressHasPrefix applies the HasPrefix predicate on the "from_address" field.
func FromAddressHasPrefix(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldHasPrefix(FieldFromAddress, v))
}

// FromAddressHasSuffix applies the HasSuffix predicate on the "from_address" field.
func FromAddressHasSuffix(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldHasSuffix(FieldFromAddress, v))
}

// FromAddressEqualFold applies the EqualFold predicate on the "from_address" field.
func FromAddressEqualFold(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEqualFold(FieldFromAddress, v))
}

// FromAddressContainsFold applies the ContainsFold predicate on the "from_address" field.
func FromAddressContainsFold(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldContainsFold(FieldFromAddress, v))
}

// ToAddressEQ applies the EQ predicate on the "to_address" field.
func ToAddressEQ(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldToAddress, v))
}

// ToAddressNEQ applies the NEQ predicate on the "to_address" field.
func ToAddressNEQ(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNEQ(FieldToAddress, v))
}

// ToAddressIn applies the In predicate on the "to_address" field.
func ToAddressIn(vs ...string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIn(FieldToAddress, vs...))
}

// ToAddressNotIn applies the NotIn predicate on the "to_address" field.
func ToAddressNotIn(vs ...string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotIn(FieldToAddress, vs...))
}

// ToAddressGT applies the GT predicate on the "to_address" field.
func ToAddressGT(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGT(FieldToAddress, v))
}

// ToAddressGTE applies the GTE predicate on the "to_address" field.
func ToAddressGTE(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGTE(FieldToAddress, v))
}

// ToAddressLT applies the LT predicate on the "to_address" field.
func ToAddressLT(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLT(FieldToAddress, v))
}

// ToAddressLTE applies the LTE predicate on the "to_address" field.
func ToAddressLTE(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLTE(FieldToAddress, v))
}

// ToAddressContains applies the Contains predicate on the "to_address" field.
func ToAddressContains(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldContains(FieldToAddress, v))
}

// ToAddressHasPrefix applies the HasPrefix predicate on the "to_address" field.
func ToAddressHasPrefix(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldHasPrefix(FieldToAddress, v))
}

// ToAddressHasSuffix applies the HasSuffix predicate on the "to_address" field.
func ToAddressHasSuffix(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldHasSuffix(FieldToAddress, v))
}

// ToAddressEqualFold applies the EqualFold predicate on the "to_address" field.
func ToAddressEqualFold(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEqualFold(FieldToAddress, v))
}

// ToAddressContainsFold applies the ContainsFold predicate on the "to_address" field.
func ToAddressContainsFold(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldContainsFold(FieldToAddress, v))
}

// RawAmountEQ applies the EQ predicate on the "raw_amount" field.
func RawAmountEQ(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldRawAmount, v))
}

// RawAmountNEQ applies the NEQ predicate on the "raw_amount" field.
func RawAmountNEQ(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNEQ(FieldRawAmount, v))
}

// RawAmountIn applies the In predicate on the "raw_amount" field.
func RawAmountIn(vs ...string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIn(FieldRawAmount, vs...))
}

// RawAmountNotIn applies the NotIn predicate on the "raw_amount" field.
func RawAmountNotIn(vs ...string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotIn(FieldRawAmount, vs...))
}

// RawAmountGT applies the GT predicate on the "raw_amount" field.
func RawAmountGT(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGT(FieldRawAmount, v))
}

// RawAmountGTE applies the GTE predicate on the "raw_amount" field.
func RawAmountGTE(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGTE(FieldRawAmount, v))
}

// RawAmountLT applies the LT predicate on the "raw_amount" field.
func RawAmountLT(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLT(FieldRawAmount, v))
}

// RawAmountLTE applies the LTE predicate on the "raw_amount" field.
func RawAmountLTE(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLTE(FieldRawAmount, v))
}

// RawAmountContains applies the Contains predicate on the "raw_amount" field.
func RawAmountContains(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldContains(FieldRawAmount, v))
}

// RawAmountHasPrefix applies the HasPrefix predicate on the "raw_amount" field.
func RawAmountHasPrefix(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldHasPrefix(FieldRawAmount, v))
}

// RawAmountHasSuffix applies the HasSuffix predicate on the "raw_amount" field.
func RawAmountHasSuffix(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldHasSuffix(FieldRawAmount, v))
}

// RawAmountEqualFold applies the EqualFold predicate on the "raw_amount" field.
func RawAmountEqualFold(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEqualFold(FieldRawAmount, v))
}

// RawAmountContainsFold applies the ContainsFold predicate on the "raw_amount" field.
func RawAmountContainsFold(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldContainsFold(FieldRawAmount, v))
}

// TokenDecimalsEQ applies the EQ predicate on the "token_decimals" field.
func TokenDecimalsEQ(v int16) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldTokenDecimals, v))
}

// TokenDecimalsNEQ applies the NEQ predicate on the "token_decimals" field.
func TokenDecimalsNEQ(v int16) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNEQ(FieldTokenDecimals, v))
}

// TokenDecimalsIn applies the In predicate on the "token_decimals" field.
func TokenDecimalsIn(vs ...int16) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIn(FieldTokenDecimals, vs...))
}

// TokenDecimalsNotIn applies the NotIn predicate on the "token_decimals" field.
func TokenDecimalsNotIn(vs ...int16) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotIn(FieldTokenDecimals, vs...))
}

// TokenDecimalsGT applies the GT predicate on the "token_decimals" field.
func TokenDecimalsGT(v int16) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGT(FieldTokenDecimals, v))
}

// TokenDecimalsGTE applies the GTE predicate on the "token_decimals" field.
func TokenDecimalsGTE(v int16) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGTE(FieldTokenDecimals, v))
}

// TokenDecimalsLT applies the LT predicate on the "token_decimals" field.
func TokenDecimalsLT(v int16) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLT(FieldTokenDecimals, v))
}

// TokenDecimalsLTE applies the LTE predicate on the "token_decimals" field.
func TokenDecimalsLTE(v int16) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLTE(FieldTokenDecimals, v))
}

// TokenAmountEQ applies the EQ predicate on the "token_amount" field.
func TokenAmountEQ(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldTokenAmount, v))
}

// TokenAmountNEQ applies the NEQ predicate on the "token_amount" field.
func TokenAmountNEQ(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNEQ(FieldTokenAmount, v))
}

// TokenAmountIn applies the In predicate on the "token_amount" field.
func TokenAmountIn(vs ...string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIn(FieldTokenAmount, vs...))
}

// TokenAmountNotIn applies the NotIn predicate on the "token_amount" field.
func TokenAmountNotIn(vs ...string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotIn(FieldTokenAmount, vs...))
}

// TokenAmountGT applies the GT predicate on the "token_amount" field.
func TokenAmountGT(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGT(FieldTokenAmount, v))
}

// TokenAmountGTE applies the GTE predicate on the "token_amount" field.
func TokenAmountGTE(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGTE(FieldTokenAmount, v))
}

// TokenAmountLT applies the LT predicate on the "token_amount" field.
func TokenAmountLT(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLT(FieldTokenAmount, v))
}

// TokenAmountLTE applies the LTE predicate on the "token_amount" field.
func TokenAmountLTE(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLTE(FieldTokenAmount, v))
}

// TokenAmountContains applies the Contains predicate on the "token_amount" field.
func TokenAmountContains(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldContains(FieldTokenAmount, v))
}

// TokenAmountHasPrefix applies the HasPrefix predicate on the "token_amount" field.
func TokenAmountHasPrefix(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldHasPrefix(FieldTokenAmount, v))
}

// TokenAmountHasSuffix applies the HasSuffix predicate on the "token_amount" field.
func TokenAmountHasSuffix(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldHasSuffix(FieldTokenAmount, v))
}

// TokenAmountEqualFold applies the EqualFold predicate on the "token_amount" field.
func TokenAmountEqualFold(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEqualFold(FieldTokenAmount, v))
}

// TokenAmountContainsFold applies the ContainsFold predicate on the "token_amount" field.
func TokenAmountContainsFold(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldContainsFold(FieldTokenAmount, v))
}

// CreditedAmountEQ applies the EQ predicate on the "credited_amount" field.
func CreditedAmountEQ(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldCreditedAmount, v))
}

// CreditedAmountNEQ applies the NEQ predicate on the "credited_amount" field.
func CreditedAmountNEQ(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNEQ(FieldCreditedAmount, v))
}

// CreditedAmountIn applies the In predicate on the "credited_amount" field.
func CreditedAmountIn(vs ...string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIn(FieldCreditedAmount, vs...))
}

// CreditedAmountNotIn applies the NotIn predicate on the "credited_amount" field.
func CreditedAmountNotIn(vs ...string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotIn(FieldCreditedAmount, vs...))
}

// CreditedAmountGT applies the GT predicate on the "credited_amount" field.
func CreditedAmountGT(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGT(FieldCreditedAmount, v))
}

// CreditedAmountGTE applies the GTE predicate on the "credited_amount" field.
func CreditedAmountGTE(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGTE(FieldCreditedAmount, v))
}

// CreditedAmountLT applies the LT predicate on the "credited_amount" field.
func CreditedAmountLT(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLT(FieldCreditedAmount, v))
}

// CreditedAmountLTE applies the LTE predicate on the "credited_amount" field.
func CreditedAmountLTE(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLTE(FieldCreditedAmount, v))
}

// CreditedAmountContains applies the Contains predicate on the "credited_amount" field.
func CreditedAmountContains(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldContains(FieldCreditedAmount, v))
}

// CreditedAmountHasPrefix applies the HasPrefix predicate on the "credited_amount" field.
func CreditedAmountHasPrefix(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldHasPrefix(FieldCreditedAmount, v))
}

// CreditedAmountHasSuffix applies the HasSuffix predicate on the "credited_amount" field.
func CreditedAmountHasSuffix(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldHasSuffix(FieldCreditedAmount, v))
}

// CreditedAmountIsNil applies the IsNil predicate on the "credited_amount" field.
func CreditedAmountIsNil() predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIsNull(FieldCreditedAmount))
}

// CreditedAmountNotNil applies the NotNil predicate on the "credited_amount" field.
func CreditedAmountNotNil() predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotNull(FieldCreditedAmount))
}

// CreditedAmountEqualFold applies the EqualFold predicate on the "credited_amount" field.
func CreditedAmountEqualFold(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEqualFold(FieldCreditedAmount, v))
}

// CreditedAmountContainsFold applies the ContainsFold predicate on the "credited_amount" field.
func CreditedAmountContainsFold(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldContainsFold(FieldCreditedAmount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldContainsFold(FieldStatus, v))
}

// ReviewReasonEQ applies the EQ predicate on the "review_reason" field.
func ReviewReasonEQ(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldReviewReason, v))
}

// ReviewReasonNEQ applies the NEQ predicate on the "review_reason" field.
func ReviewReasonNEQ(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNEQ(FieldReviewReason, v))
}

// ReviewReasonIn applies the In predicate on the "review_reason" field.
func ReviewReasonIn(vs ...string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIn(FieldReviewReason, vs...))
}

// ReviewReasonNotIn applies the NotIn predicate on the "review_reason" field.
func ReviewReasonNotIn(vs ...string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotIn(FieldReviewReason, vs...))
}

// ReviewReasonGT applies the GT predicate on the "review_reason" field.
func ReviewReasonGT(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGT(FieldReviewReason, v))
}

// ReviewReasonGTE applies the GTE predicate on the "review_reason" field.
func ReviewReasonGTE(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGTE(FieldReviewReason, v))
}

// ReviewReasonLT applies the LT predicate on the "review_reason" field.
func ReviewReasonLT(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLT(FieldReviewReason, v))
}

// ReviewReasonLTE applies the LTE predicate on the "review_reason" field.
func ReviewReasonLTE(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLTE(FieldReviewReason, v))
}

// ReviewReasonContains applies the Contains predicate on the "review_reason" field.
func ReviewReasonContains(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldContains(FieldReviewReason, v))
}

// ReviewReasonHasPrefix applies the HasPrefix predicate on the "review_reason" field.
func ReviewReasonHasPrefix(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldHasPrefix(FieldReviewReason, v))
}

// ReviewReasonHasSuffix applies the HasSuffix predicate on the "review_reason" field.
func ReviewReasonHasSuffix(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldHasSuffix(FieldReviewReason, v))
}

// ReviewReasonIsNil applies the IsNil predicate on the "review_reason" field.
func ReviewReasonIsNil() predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIsNull(FieldReviewReason))
}

// ReviewReasonNotNil applies the NotNil predicate on the "review_reason" field.
func ReviewReasonNotNil() predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotNull(FieldReviewReason))
}

// ReviewReasonEqualFold applies the EqualFold predicate on the "review_reason" field.
func ReviewReasonEqualFold(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEqualFold(FieldReviewReason, v))
}

// ReviewReasonContainsFold applies the ContainsFold predicate on the "review_reason" field.
func ReviewReasonContainsFold(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldContainsFold(FieldReviewReason, v))
}

// FailureReasonEQ applies the EQ predicate on the "failure_reason" field.
func FailureReasonEQ(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldFailureReason, v))
}

// FailureReasonNEQ applies the NEQ predicate on the "failure_reason" field.
func FailureReasonNEQ(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNEQ(FieldFailureReason, v))
}

// FailureReasonIn applies the In predicate on the "failure_reason" field.
func FailureReasonIn(vs ...string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIn(FieldFailureReason, vs...))
}

// FailureReasonNotIn applies the NotIn predicate on the "failure_reason" field.
func FailureReasonNotIn(vs ...string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotIn(FieldFailureReason, vs...))
}

// FailureReasonGT applies the GT predicate on the "failure_reason" field.
func FailureReasonGT(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGT(FieldFailureReason, v))
}

// FailureReasonGTE applies the GTE predicate on the "failure_reason" field.
func FailureReasonGTE(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGTE(FieldFailureReason, v))
}

// FailureReasonLT applies the LT predicate on the "failure_reason" field.
func FailureReasonLT(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLT(FieldFailureReason, v))
}

// FailureReasonLTE applies the LTE predicate on the "failure_reason" field.
func FailureReasonLTE(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLTE(FieldFailureReason, v))
}

// FailureReasonContains applies the Contains predicate on the "failure_reason" field.
func FailureReasonContains(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldContains(FieldFailureReason, v))
}

// FailureReasonHasPrefix applies the HasPrefix predicate on the "failure_reason" field.
func FailureReasonHasPrefix(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldHasPrefix(FieldFailureReason, v))
}

// FailureReasonHasSuffix applies the HasSuffix predicate on the "failure_reason" field.
func FailureReasonHasSuffix(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldHasSuffix(FieldFailureReason, v))
}

// FailureReasonIsNil applies the IsNil predicate on the "failure_reason" field.
func FailureReasonIsNil() predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIsNull(FieldFailureReason))
}

// FailureReasonNotNil applies the NotNil predicate on the "failure_reason" field.
func FailureReasonNotNil() predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotNull(FieldFailureReason))
}

// FailureReasonEqualFold applies the EqualFold predicate on the "failure_reason" field.
func FailureReasonEqualFold(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEqualFold(FieldFailureReason, v))
}

// FailureReasonContainsFold applies the ContainsFold predicate on the "failure_reason" field.
func FailureReasonContainsFold(v string) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldContainsFold(FieldFailureReason, v))
}

// RetryCountEQ applies the EQ predicate on the "retry_count" field.
func RetryCountEQ(v int32) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldRetryCount, v))
}

// RetryCountNEQ applies the NEQ predicate on the "retry_count" field.
func RetryCountNEQ(v int32) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNEQ(FieldRetryCount, v))
}

// RetryCountIn applies the In predicate on the "retry_count" field.
func RetryCountIn(vs ...int32) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIn(FieldRetryCount, vs...))
}

// RetryCountNotIn applies the NotIn predicate on the "retry_count" field.
func RetryCountNotIn(vs ...int32) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotIn(FieldRetryCount, vs...))
}

// RetryCountGT applies the GT predicate on the "retry_count" field.
func RetryCountGT(v int32) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGT(FieldRetryCount, v))
}

// RetryCountGTE applies the GTE predicate on the "retry_count" field.
func RetryCountGTE(v int32) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGTE(FieldRetryCount, v))
}

// RetryCountLT applies the LT predicate on the "retry_count" field.
func RetryCountLT(v int32) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLT(FieldRetryCount, v))
}

// RetryCountLTE applies the LTE predicate on the "retry_count" field.
func RetryCountLTE(v int32) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLTE(FieldRetryCount, v))
}

// NextRetryAtEQ applies the EQ predicate on the "next_retry_at" field.
func NextRetryAtEQ(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldNextRetryAt, v))
}

// NextRetryAtNEQ applies the NEQ predicate on the "next_retry_at" field.
func NextRetryAtNEQ(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNEQ(FieldNextRetryAt, v))
}

// NextRetryAtIn applies the In predicate on the "next_retry_at" field.
func NextRetryAtIn(vs ...time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIn(FieldNextRetryAt, vs...))
}

// NextRetryAtNotIn applies the NotIn predicate on the "next_retry_at" field.
func NextRetryAtNotIn(vs ...time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotIn(FieldNextRetryAt, vs...))
}

// NextRetryAtGT applies the GT predicate on the "next_retry_at" field.
func NextRetryAtGT(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGT(FieldNextRetryAt, v))
}

// NextRetryAtGTE applies the GTE predicate on the "next_retry_at" field.
func NextRetryAtGTE(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGTE(FieldNextRetryAt, v))
}

// NextRetryAtLT applies the LT predicate on the "next_retry_at" field.
func NextRetryAtLT(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLT(FieldNextRetryAt, v))
}

// NextRetryAtLTE applies the LTE predicate on the "next_retry_at" field.
func NextRetryAtLTE(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLTE(FieldNextRetryAt, v))
}

// NextRetryAtIsNil applies the IsNil predicate on the "next_retry_at" field.
func NextRetryAtIsNil() predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIsNull(FieldNextRetryAt))
}

// NextRetryAtNotNil applies the NotNil predicate on the "next_retry_at" field.
func NextRetryAtNotNil() predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotNull(FieldNextRetryAt))
}

// DetectedAtEQ applies the EQ predicate on the "detected_at" field.
func DetectedAtEQ(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldDetectedAt, v))
}

// DetectedAtNEQ applies the NEQ predicate on the "detected_at" field.
func DetectedAtNEQ(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNEQ(FieldDetectedAt, v))
}

// DetectedAtIn applies the In predicate on the "detected_at" field.
func DetectedAtIn(vs ...time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIn(FieldDetectedAt, vs...))
}

// DetectedAtNotIn applies the NotIn predicate on the "detected_at" field.
func DetectedAtNotIn(vs ...time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotIn(FieldDetectedAt, vs...))
}

// DetectedAtGT applies the GT predicate on the "detected_at" field.
func DetectedAtGT(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGT(FieldDetectedAt, v))
}

// DetectedAtGTE applies the GTE predicate on the "detected_at" field.
func DetectedAtGTE(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGTE(FieldDetectedAt, v))
}

// DetectedAtLT applies the LT predicate on the "detected_at" field.
func DetectedAtLT(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLT(FieldDetectedAt, v))
}

// DetectedAtLTE applies the LTE predicate on the "detected_at" field.
func DetectedAtLTE(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLTE(FieldDetectedAt, v))
}

// FinalizedAtEQ applies the EQ predicate on the "finalized_at" field.
func FinalizedAtEQ(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldFinalizedAt, v))
}

// FinalizedAtNEQ applies the NEQ predicate on the "finalized_at" field.
func FinalizedAtNEQ(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNEQ(FieldFinalizedAt, v))
}

// FinalizedAtIn applies the In predicate on the "finalized_at" field.
func FinalizedAtIn(vs ...time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIn(FieldFinalizedAt, vs...))
}

// FinalizedAtNotIn applies the NotIn predicate on the "finalized_at" field.
func FinalizedAtNotIn(vs ...time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotIn(FieldFinalizedAt, vs...))
}

// FinalizedAtGT applies the GT predicate on the "finalized_at" field.
func FinalizedAtGT(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGT(FieldFinalizedAt, v))
}

// FinalizedAtGTE applies the GTE predicate on the "finalized_at" field.
func FinalizedAtGTE(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGTE(FieldFinalizedAt, v))
}

// FinalizedAtLT applies the LT predicate on the "finalized_at" field.
func FinalizedAtLT(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLT(FieldFinalizedAt, v))
}

// FinalizedAtLTE applies the LTE predicate on the "finalized_at" field.
func FinalizedAtLTE(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLTE(FieldFinalizedAt, v))
}

// FinalizedAtIsNil applies the IsNil predicate on the "finalized_at" field.
func FinalizedAtIsNil() predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIsNull(FieldFinalizedAt))
}

// FinalizedAtNotNil applies the NotNil predicate on the "finalized_at" field.
func FinalizedAtNotNil() predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotNull(FieldFinalizedAt))
}

// CreditedAtEQ applies the EQ predicate on the "credited_at" field.
func CreditedAtEQ(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldEQ(FieldCreditedAt, v))
}

// CreditedAtNEQ applies the NEQ predicate on the "credited_at" field.
func CreditedAtNEQ(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNEQ(FieldCreditedAt, v))
}

// CreditedAtIn applies the In predicate on the "credited_at" field.
func CreditedAtIn(vs ...time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIn(FieldCreditedAt, vs...))
}

// CreditedAtNotIn applies the NotIn predicate on the "credited_at" field.
func CreditedAtNotIn(vs ...time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotIn(FieldCreditedAt, vs...))
}

// CreditedAtGT applies the GT predicate on the "credited_at" field.
func CreditedAtGT(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGT(FieldCreditedAt, v))
}

// CreditedAtGTE applies the GTE predicate on the "credited_at" field.
func CreditedAtGTE(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldGTE(FieldCreditedAt, v))
}

// CreditedAtLT applies the LT predicate on the "credited_at" field.
func CreditedAtLT(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLT(FieldCreditedAt, v))
}

// CreditedAtLTE applies the LTE predicate on the "credited_at" field.
func CreditedAtLTE(v time.Time) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldLTE(FieldCreditedAt, v))
}

// CreditedAtIsNil applies the IsNil predicate on the "credited_at" field.
func CreditedAtIsNil() predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldIsNull(FieldCreditedAt))
}

// CreditedAtNotNil applies the NotNil predicate on the "credited_at" field.
func CreditedAtNotNil() predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.FieldNotNull(FieldCreditedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Web3Deposit) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Web3Deposit) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Web3Deposit) predicate.Web3Deposit {
	return predicate.Web3Deposit(sql.NotPredicates(p))
}
