// Code generated by ent, DO NOT EDIT.

package web3depositaddress

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEQ(FieldUserID, v))
}

// WalletID applies equality check predicate on the "wallet_id" field. It's identical to WalletIDEQ.
func WalletID(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEQ(FieldWalletID, v))
}

// DerivationIndex applies equality check predicate on the "derivation_index" field. It's identical to DerivationIndexEQ.
func DerivationIndex(v int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEQ(FieldDerivationIndex, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEQ(FieldAddress, v))
}

// NormalizedAddress applies equality check predicate on the "normalized_address" field. It's identical to NormalizedAddressEQ.
func NormalizedAddress(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEQ(FieldNormalizedAddress, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEQ(FieldStatus, v))
}

// AllocatedAt applies equality check predicate on the "allocated_at" field. It's identical to AllocatedAtEQ.
func AllocatedAt(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEQ(FieldAllocatedAt, v))
}

// DisabledAt applies equality check predicate on the "disabled_at" field. It's identical to DisabledAtEQ.
func DisabledAt(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEQ(FieldDisabledAt, v))
}

// LastDepositAt applies equality check predicate on the "last_deposit_at" field. It's identical to LastDepositAtEQ.
func LastDepositAt(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEQ(FieldLastDepositAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldLTE(FieldUserID, v))
}

// WalletIDEQ applies the EQ predicate on the "wallet_id" field.
func WalletIDEQ(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEQ(FieldWalletID, v))
}

// WalletIDNEQ applies the NEQ predicate on the "wallet_id" field.
func WalletIDNEQ(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNEQ(FieldWalletID, v))
}

// WalletIDIn applies the In predicate on the "wallet_id" field.
func WalletIDIn(vs ...string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldIn(FieldWalletID, vs...))
}

// WalletIDNotIn applies the NotIn predicate on the "wallet_id" field.
func WalletIDNotIn(vs ...string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNotIn(FieldWalletID, vs...))
}

// WalletIDGT applies the GT predicate on the "wallet_id" field.
func WalletIDGT(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldGT(FieldWalletID, v))
}

// WalletIDGTE applies the GTE predicate on the "wallet_id" field.
func WalletIDGTE(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldGTE(FieldWalletID, v))
}

// WalletIDLT applies the LT predicate on the "wallet_id" field.
func WalletIDLT(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldLT(FieldWalletID, v))
}

// WalletIDLTE applies the LTE predicate on the "wallet_id" field.
func WalletIDLTE(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldLTE(FieldWalletID, v))
}

// WalletIDContains applies the Contains predicate on the "wallet_id" field.
func WalletIDContains(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldContains(FieldWalletID, v))
}

// WalletIDHasPrefix applies the HasPrefix predicate on the "wallet_id" field.
func WalletIDHasPrefix(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldHasPrefix(FieldWalletID, v))
}

// WalletIDHasSuffix applies the HasSuffix predicate on the "wallet_id" field.
func WalletIDHasSuffix(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldHasSuffix(FieldWalletID, v))
}

// WalletIDEqualFold applies the EqualFold predicate on the "wallet_id" field.
func WalletIDEqualFold(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEqualFold(FieldWalletID, v))
}

// WalletIDContainsFold applies the ContainsFold predicate on the "wallet_id" field.
func WalletIDContainsFold(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldContainsFold(FieldWalletID, v))
}

// DerivationIndexEQ applies the EQ predicate on the "derivation_index" field.
func DerivationIndexEQ(v int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEQ(FieldDerivationIndex, v))
}

// DerivationIndexNEQ applies the NEQ predicate on the "derivation_index" field.
func DerivationIndexNEQ(v int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNEQ(FieldDerivationIndex, v))
}

// DerivationIndexIn applies the In predicate on the "derivation_index" field.
func DerivationIndexIn(vs ...int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldIn(FieldDerivationIndex, vs...))
}

// DerivationIndexNotIn applies the NotIn predicate on the "derivation_index" field.
func DerivationIndexNotIn(vs ...int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNotIn(FieldDerivationIndex, vs...))
}

// DerivationIndexGT applies the GT predicate on the "derivation_index" field.
func DerivationIndexGT(v int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldGT(FieldDerivationIndex, v))
}

// DerivationIndexGTE applies the GTE predicate on the "derivation_index" field.
func DerivationIndexGTE(v int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldGTE(FieldDerivationIndex, v))
}

// DerivationIndexLT applies the LT predicate on the "derivation_index" field.
func DerivationIndexLT(v int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldLT(FieldDerivationIndex, v))
}

// DerivationIndexLTE applies the LTE predicate on the "derivation_index" field.
func DerivationIndexLTE(v int64) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldLTE(FieldDerivationIndex, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldContainsFold(FieldAddress, v))
}

// NormalizedAddressEQ applies the EQ predicate on the "normalized_address" field.
func NormalizedAddressEQ(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEQ(FieldNormalizedAddress, v))
}

// NormalizedAddressNEQ applies the NEQ predicate on the "normalized_address" field.
func NormalizedAddressNEQ(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNEQ(FieldNormalizedAddress, v))
}

// NormalizedAddressIn applies the In predicate on the "normalized_address" field.
func NormalizedAddressIn(vs ...string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldIn(FieldNormalizedAddress, vs...))
}

// NormalizedAddressNotIn applies the NotIn predicate on the "normalized_address" field.
func NormalizedAddressNotIn(vs ...string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNotIn(FieldNormalizedAddress, vs...))
}

// NormalizedAddressGT applies the GT predicate on the "normalized_address" field.
func NormalizedAddressGT(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldGT(FieldNormalizedAddress, v))
}

// NormalizedAddressGTE applies the GTE predicate on the "normalized_address" field.
func NormalizedAddressGTE(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldGTE(FieldNormalizedAddress, v))
}

// NormalizedAddressLT applies the LT predicate on the "normalized_address" field.
func NormalizedAddressLT(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldLT(FieldNormalizedAddress, v))
}

// NormalizedAddressLTE applies the LTE predicate on the "normalized_address" field.
func NormalizedAddressLTE(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldLTE(FieldNormalizedAddress, v))
}

// NormalizedAddressContains applies the Contains predicate on the "normalized_address" field.
func NormalizedAddressContains(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldContains(FieldNormalizedAddress, v))
}

// NormalizedAddressHasPrefix applies the HasPrefix predicate on the "normalized_address" field.
func NormalizedAddressHasPrefix(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldHasPrefix(FieldNormalizedAddress, v))
}

// NormalizedAddressHasSuffix applies the HasSuffix predicate on the "normalized_address" field.
func NormalizedAddressHasSuffix(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldHasSuffix(FieldNormalizedAddress, v))
}

// NormalizedAddressEqualFold applies the EqualFold predicate on the "normalized_address" field.
func NormalizedAddressEqualFold(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEqualFold(FieldNormalizedAddress, v))
}

// NormalizedAddressContainsFold applies the ContainsFold predicate on the "normalized_address" field.
func NormalizedAddressContainsFold(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldContainsFold(FieldNormalizedAddress, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldContainsFold(FieldStatus, v))
}

// AllocatedAtEQ applies the EQ predicate on the "allocated_at" field.
func AllocatedAtEQ(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEQ(FieldAllocatedAt, v))
}

// AllocatedAtNEQ applies the NEQ predicate on the "allocated_at" field.
func AllocatedAtNEQ(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNEQ(FieldAllocatedAt, v))
}

// AllocatedAtIn applies the In predicate on the "allocated_at" field.
func AllocatedAtIn(vs ...time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldIn(FieldAllocatedAt, vs...))
}

// AllocatedAtNotIn applies the NotIn predicate on the "allocated_at" field.
func AllocatedAtNotIn(vs ...time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNotIn(FieldAllocatedAt, vs...))
}

// AllocatedAtGT applies the GT predicate on the "allocated_at" field.
func AllocatedAtGT(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldGT(FieldAllocatedAt, v))
}

// AllocatedAtGTE applies the GTE predicate on the "allocated_at" field.
func AllocatedAtGTE(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldGTE(FieldAllocatedAt, v))
}

// AllocatedAtLT applies the LT predicate on the "allocated_at" field.
func AllocatedAtLT(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldLT(FieldAllocatedAt, v))
}

// AllocatedAtLTE applies the LTE predicate on the "allocated_at" field.
func AllocatedAtLTE(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldLTE(FieldAllocatedAt, v))
}

// DisabledAtEQ applies the EQ predicate on the "disabled_at" field.
func DisabledAtEQ(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEQ(FieldDisabledAt, v))
}

// DisabledAtNEQ applies the NEQ predicate on the "disabled_at" field.
func DisabledAtNEQ(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNEQ(FieldDisabledAt, v))
}

// DisabledAtIn applies the In predicate on the "disabled_at" field.
func DisabledAtIn(vs ...time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldIn(FieldDisabledAt, vs...))
}

// DisabledAtNotIn applies the NotIn predicate on the "disabled_at" field.
func DisabledAtNotIn(vs ...time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNotIn(FieldDisabledAt, vs...))
}

// DisabledAtGT applies the GT predicate on the "disabled_at" field.
func DisabledAtGT(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldGT(FieldDisabledAt, v))
}

// DisabledAtGTE applies the GTE predicate on the "disabled_at" field.
func DisabledAtGTE(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldGTE(FieldDisabledAt, v))
}

// DisabledAtLT applies the LT predicate on the "disabled_at" field.
func DisabledAtLT(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldLT(FieldDisabledAt, v))
}

// DisabledAtLTE applies the LTE predicate on the "disabled_at" field.
func DisabledAtLTE(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldLTE(FieldDisabledAt, v))
}

// DisabledAtIsNil applies the IsNil predicate on the "disabled_at" field.
func DisabledAtIsNil() predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldIsNull(FieldDisabledAt))
}

// DisabledAtNotNil applies the NotNil predicate on the "disabled_at" field.
func DisabledAtNotNil() predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNotNull(FieldDisabledAt))
}

// LastDepositAtEQ applies the EQ predicate on the "last_deposit_at" field.
func LastDepositAtEQ(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldEQ(FieldLastDepositAt, v))
}

// LastDepositAtNEQ applies the NEQ predicate on the "last_deposit_at" field.
func LastDepositAtNEQ(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNEQ(FieldLastDepositAt, v))
}

// LastDepositAtIn applies the In predicate on the "last_deposit_at" field.
func LastDepositAtIn(vs ...time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldIn(FieldLastDepositAt, vs...))
}

// LastDepositAtNotIn applies the NotIn predicate on the "last_deposit_at" field.
func LastDepositAtNotIn(vs ...time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNotIn(FieldLastDepositAt, vs...))
}

// LastDepositAtGT applies the GT predicate on the "last_deposit_at" field.
func LastDepositAtGT(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldGT(FieldLastDepositAt, v))
}

// LastDepositAtGTE applies the GTE predicate on the "last_deposit_at" field.
func LastDepositAtGTE(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldGTE(FieldLastDepositAt, v))
}

// LastDepositAtLT applies the LT predicate on the "last_deposit_at" field.
func LastDepositAtLT(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldLT(FieldLastDepositAt, v))
}

// LastDepositAtLTE applies the LTE predicate on the "last_deposit_at" field.
func LastDepositAtLTE(v time.Time) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldLTE(FieldLastDepositAt, v))
}

// LastDepositAtIsNil applies the IsNil predicate on the "last_deposit_at" field.
func LastDepositAtIsNil() predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldIsNull(FieldLastDepositAt))
}

// LastDepositAtNotNil applies the NotNil predicate on the "last_deposit_at" field.
func LastDepositAtNotNil() predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.FieldNotNull(FieldLastDepositAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Web3DepositAddress) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Web3DepositAddress) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Web3DepositAddress) predicate.Web3DepositAddress {
	return predicate.Web3DepositAddress(sql.NotPredicates(p))
}
